In [1]:
%matplotlib inline
import pandas as pd

* This file contains a running list of all of the schools in the Philadelphia School District.  Each of these schools is divided into a row for "All Grades" and a row for each of the grades served.

In [2]:
enrollment_demographics = pd.read_csv('../data/enrollment_demographics.csv')

In [3]:
print(enrollment_demographics.columns)

Index(['School Year', 'SRC School ID', 'School Name', 'Learning Network',
       'Grade Level', 'Student Enrollment', 'ELL Count', 'ELL Pct',
       'Not ELL Count', 'Not ELL Pct', 'IEP Count', 'IEP Pct', 'Not IEP Count',
       'Not IEP Pct', 'Female Count', 'Female Pct', 'Male Count', 'Male Pct',
       'American Indian Count', 'American Indian Pct', 'Asian Count',
       'Asian Pct', 'Black/African American Count',
       'Black/African American Pct', 'Hispanic Count', 'Hispanic Pct',
       'Multi-Race Count', 'Multi-Race Pct', 'Pacific Islander Count',
       'Pacific Islander Pct', 'White Count', 'White Pct',
       'CEP Economically Disadvantaged Rate'],
      dtype='object')

In [4]:
enrollment_demographics.shape

(1673, 33)

In [5]:
enrollment_demographics.describe

<bound method NDFrame.describe of      School Year  SRC School ID                                  School Name  \
0      2018-2019            101                     John Bartram High School
1      2018-2019            101                     John Bartram High School
2      2018-2019            101                     John Bartram High School
3      2018-2019            101                     John Bartram High School
4      2018-2019            101                     John Bartram High School
5      2018-2019            102                West Philadelphia High School
6      2018-2019            102                West Philadelphia High School
7      2018-2019            102                West Philadelphia High School
8      2018-2019            102                West Philadelphia High School
9      2018-2019            102                West Philadelphia High School
10     2018-2019            103                    High School of the Future
11     2018-2019            103                    High School of the Future
12     2018-2019            103                    High School of the Future
13     2018-2019            103                    High School of the Future
14     2018-2019            103                    High School of the Future
15     2018-2019            105  Paul Robeson High School for Human Services
16     2018-2019            105  Paul Robeson High School for Human Services
17     2018-2019            105  Paul Robeson High School for Human Services
18     2018-2019            105  Paul Robeson High School for Human Services
19     2018-2019            105  Paul Robeson High School for Human Services
20     2018-2019            110                 William L. Sayre High School
21     2018-2019            110                 William L. Sayre High School
22     2018-2019            110                 William L. Sayre High School
23     2018-2019            110                 William L. Sayre High School
24     2018-2019            110                 William L. Sayre High School
25     2018-2019            113                     William T. Tilden School
26     2018-2019            113                     William T. Tilden School
27     2018-2019            113                     William T. Tilden School
28     2018-2019            113                     William T. Tilden School
29     2018-2019            113                     William T. Tilden School
...          ...            ...                                          ...
1643   2018-2019            844                    William H. Loesche School
1644   2018-2019            844                    William H. Loesche School
1645   2018-2019            844                    William H. Loesche School
1646   2018-2019            844                    William H. Loesche School
1647   2018-2019            844                    William H. Loesche School
1648   2018-2019            844                    William H. Loesche School
1649   2018-2019            844                    William H. Loesche School
1650   2018-2019            856                          The Workshop School
1651   2018-2019            856                          The Workshop School
1652   2018-2019            856                          The Workshop School
1653   2018-2019            856                          The Workshop School
1654   2018-2019            856                          The Workshop School
1655   2018-2019            877            John Hancock Demonstration School
1656   2018-2019            877            John Hancock Demonstration School
1657   2018-2019            877            John Hancock Demonstration School
1658   2018-2019            877            John Hancock Demonstration School
1659   2018-2019            877            John Hancock Demonstration School
1660   2018-2019            877            John Hancock Demonstration School
1661   2018-2019            877            John Hancock Demonstration School
1662   2018-2019            877            John Hancock Demonstration School
1663   2018-2019            877            John Hancock Demonstration School
1664   2018-2019            877            John Hancock Demonstration School
1665   2018-2019            878                 Philadelphia Virtual Academy
1666   2018-2019            878                 Philadelphia Virtual Academy
1667   2018-2019            878                 Philadelphia Virtual Academy
1668   2018-2019            878                 Philadelphia Virtual Academy
1669   2018-2019            878                 Philadelphia Virtual Academy
1670   2018-2019            878                 Philadelphia Virtual Academy
1671   2018-2019            878                 Philadelphia Virtual Academy
1672   2018-2019            878                 Philadelphia Virtual Academy

     Learning Network Grade Level  Student Enrollment  ELL Count  ELL Pct  \
0          Network 13          09                 142          7     4.93
1          Network 13          10                 145         10     6.90
2          Network 13          11                 153         11     7.19
3          Network 13          12                  94          9     9.57
4          Network 13  All Grades                 534         37     6.93
5        Acceleration          09                 134          2     1.49
6        Acceleration          10                 106          1     0.94
7        Acceleration          11                 106          2     1.89
8        Acceleration          12                 102          1     0.98
9        Acceleration  All Grades                 448          6     1.34
10          Network 1          09                 200          6     3.00
11          Network 1          10                 136          2     1.47
12          Network 1          11                 119          2     1.68
13          Network 1          12                  96          2     2.08
14          Network 1  All Grades                 551         12     2.18
15          Network 1          09                  75          3     4.00
16          Network 1          10                  77          2     2.60
17          Network 1          11                  75          3     4.00
18          Network 1          12                  80          1     1.25
19          Network 1  All Grades                 307          9     2.93
20         Network 13          09                 113          1     0.88
21         Network 13          10                 110          1     0.91
22         Network 13          11                 102          0     0.00
23         Network 13          12                  87          1     1.15
24         Network 13  All Grades                 412          3     0.73
25         Network 10          05                  41          9    21.95
26         Network 10          06                 113         17    15.04
27         Network 10          07                 116         27    23.28
28         Network 10          08                  90          9    10.00
29         Network 10  All Grades                 360         62    17.22
...               ...         ...                 ...        ...      ...
1643        Network 8          00                 153         43    28.10
1644        Network 8          01                 175         69    39.43
1645        Network 8          02                 146         57    39.04
1646        Network 8          03                 141         61    43.26
1647        Network 8          04                 124         54    43.55
1648        Network 8          05                 146         45    30.82
1649        Network 8  All Grades                 885        329    37.18
1650       Innovation          09                  72          3     4.17
1651       Innovation          10                  64          2     3.13
1652       Innovation          11                  52          1     1.92
1653       Innovation          12                  68          3     4.41
1654       Innovation  All Grades                 256          9     3.52
1655        Network 8          00                  80          2     2.50
1656        Network 8          01                  77          0     0.00
1657        Network 8          02                  86          4     4.65
1658        Network 8          03                  78          5     6.41
1659        Network 8          04                  78          4     5.13
1660        Network 8          05                  77          4     5.19
1661        Network 8          06                  92          7     7.61
1662        Network 8          07                 100          7     7.00
1663        Network 8          08                 101          8     7.92
1664        Network 8  All Grades                 769         41     5.33
1665       Innovation          06                   9          0     0.00
1666       Innovation          07                  20          0     0.00
1667       Innovation          08                  30          2     6.67
1668       Innovation          09                  85          1     1.18
1669       Innovation          10                 115          1     0.87
1670       Innovation          11                 129          3     2.33
1671       Innovation          12                 163          3     1.84
1672       Innovation  All Grades                 551         10     1.81

      Not ELL Count  Not ELL Pct  ...  Black/African American Pct  \
0               135        95.07  ...                       83.80
1               135        93.10  ...                       86.90
2               142        92.81  ...                       88.89
3                85        90.43  ...                       93.62
4               497        93.07  ...                       87.83
5               132        98.51  ...                       89.55
6               105        99.06  ...                       92.45
7               104        98.11  ...                       94.34
8               101        99.02  ...                       98.04
9               442        98.66  ...                       93.30
10              194        97.00  ...                       87.00
11              134        98.53  ...                       94.12
12              117        98.32  ...                       87.39
13               94        97.92  ...                       91.67
14              539        97.82  ...                       89.66
15               72        96.00  ...                       90.67
16               75        97.40  ...                       96.10
17               72        96.00  ...                       96.00
18               79        98.75  ...                       95.00
19              298        97.07  ...                       94.46
20              112        99.12  ...                       86.73
21              109        99.09  ...                       94.55
22              102       100.00  ...                       98.04
23               86        98.85  ...                       93.10
24              409        99.27  ...                       92.96
25               32        78.05  ...                       75.61
26               96        84.96  ...                       83.19
27               89        76.72  ...                       81.90
28               81        90.00  ...                       74.44
29              298        82.78  ...                       79.72
...             ...          ...  ...                         ...
1643            110        71.90  ...                       11.11
1644            106        60.57  ...                        8.00
1645             89        60.96  ...                       14.38
1646             80        56.74  ...                        7.09
1647             70        56.45  ...                        9.68
1648            101        69.18  ...                       10.96
1649            556        62.82  ...                       10.17
1650             69        95.83  ...                       86.11
1651             62        96.88  ...                       85.94
1652             51        98.08  ...                       82.69
1653             65        95.59  ...                       86.76
1654            247        96.48  ...                       85.55
1655             78        97.50  ...                       12.50
1656             77       100.00  ...                       10.39
1657             82        95.35  ...                       20.93
1658             73        93.59  ...                       20.51
1659             74        94.87  ...                       10.26
1660             73        94.81  ...                       10.39
1661             85        92.39  ...                       14.13
1662             93        93.00  ...                        6.00
1663             93        92.08  ...                       14.85
1664            728        94.67  ...                       13.26
1665              9       100.00  ...                       88.89
1666             20       100.00  ...                       75.00
1667             28        93.33  ...                       53.33
1668             84        98.82  ...                       69.41
1669            114        99.13  ...                       68.70
1670            126        97.67  ...                       68.99
1671            160        98.16  ...                       57.67
1672            541        98.19  ...                       65.34

      Hispanic Count  Hispanic Pct  Multi-Race Count  Multi-Race Pct  \
0                  8          5.63                 6            4.23
1                  8          5.52                 3            2.07
2                  4          2.61                 2            1.31
3                  3          3.19                 2            2.13
4                 23          4.31                13            2.43
5                  6          4.48                 7            5.22
6                  0          0.00                 5            4.72
7                  1          0.94                 3            2.83
8                  0          0.00                 0            0.00
9                  7          1.56                15            3.35
10                 8          4.00                16            8.00
11                 1          0.74                 6            4.41
12                 7          5.88                 1            0.84
13                 4          4.17                 0            0.00
14                20          3.63                23            4.17
15                 0          0.00                 7            9.33
16                 0          0.00                 1            1.30
17                 2          2.67                 0            0.00
18                 2          2.50                 2            2.50
19                 4          1.30                10            3.26
20                 3          2.65                10            8.85
21                 2          1.82                 4            3.64
22                 1          0.98                 1            0.98
23                 2          2.30                 1            1.15
24                 8          1.94                16            3.88
25                 4          9.76                 2            4.88
26                 7          6.19                 7            6.19
27                12         10.34                 2            1.72
28                 4          4.44                 7            7.78
29                27          7.50                18            5.00
...              ...           ...               ...             ...
1643               8          5.23                 3            1.96
1644               8          4.57                 3            1.71
1645               8          5.48                11            7.53
1646               5          3.55                11            7.80
1647               3          2.42                13           10.48
1648               7          4.79                10            6.85
1649              39          4.41                51            5.76
1650               2          2.78                 6            8.33
1651               1          1.56                 3            4.69
1652               1          1.92                 4            7.69
1653               2          2.94                 3            4.41
1654               6          2.34                16            6.25
1655              18         22.50                 0            0.00
1656              11         14.29                 7            9.09
1657               7          8.14                 8            9.30
1658               6          7.69                 5            6.41
1659               8         10.26                 5            6.41
1660              12         15.58                 2            2.60
1661              11         11.96                 9            9.78
1662              13         13.00                15           15.00
1663              13         12.87                21           20.79
1664              99         12.87                72            9.36
1665               0          0.00                 0            0.00
1666               3         15.00                 0            0.00
1667               7         23.33                 2            6.67
1668               8          9.41                 8            9.41
1669              11          9.57                 5            4.35
1670              23         17.83                 3            2.33
1671              25         15.34                 7            4.29
1672              77         13.97                25            4.54

      Pacific Islander Count  Pacific Islander Pct  White Count  White Pct  \
0                          0                  0.00            3       2.11
1                          0                  0.00            1       0.69
2                          1                  0.65            0       0.00
3                          0                  0.00            0       0.00
4                          1                  0.19            4       0.75
5                          0                  0.00            1       0.75
6                          0                  0.00            2       1.89
7                          0                  0.00            1       0.94
8                          0                  0.00            0       0.00
9                          0                  0.00            4       0.89
10                         0                  0.00            0       0.00
11                         0                  0.00            0       0.00
12                         0                  0.00            3       2.52
13                         0                  0.00            4       4.17
14                         0                  0.00            7       1.27
15                         0                  0.00            0       0.00
16                         0                  0.00            0       0.00
17                         0                  0.00            0       0.00
18                         0                  0.00            0       0.00
19                         0                  0.00            0       0.00
20                         0                  0.00            1       0.88
21                         0                  0.00            0       0.00
22                         0                  0.00            0       0.00
23                         0                  0.00            2       2.30
24                         0                  0.00            3       0.73
25                         0                  0.00            0       0.00
26                         0                  0.00            2       1.77
27                         0                  0.00            2       1.72

In [6]:
enrollment_demographics[['School Name','Grade Level','Student Enrollment']]

,School Name,Grade Level,Student Enrollment
0,John Bartram High School,09,142
1,John Bartram High School,10,145
2,John Bartram High School,11,153
3,John Bartram High School,12,94
4,John Bartram High School,All Grades,534
5,West Philadelphia High School,09,134
6,West Philadelphia High School,10,106
7,West Philadelphia High School,11,106
8,West Philadelphia High School,12,102
9,West Philadelphia High School,All Grades,448
10,High School of the Future,09,200
11,High School of the Future,10,136
12,High School of the Future,11,119
13,High School of the Future,12,96
14,High School of the Future,All Grades,551
15,Paul Robeson High School for Human Services,09,75
16,Paul Robeson High School for Human Services,10,77
17,Paul Robeson High School for Human Services,11,75
18,Paul Robeson High School for Human Services,12,80
19,Paul Robeson High School for Human Services,All Grades,307
20,William L. Sayre High School,09,113
21,William L. Sayre High School,10,110
22,William L. Sayre High School,11,102
23,William L. Sayre High School,12,87
24,William L. Sayre High School,All Grades,412
25,William T. Tilden School,05,41
26,William T. Tilden School,06,113
27,William T. Tilden School,07,116
28,William T. Tilden School,08,90
29,William T. Tilden School,All Grades,360
...,...,...,...
1643,William H. Loesche School,00,153
1644,William H. Loesche School,01,175
1645,William H. Loesche School,02,146
1646,William H. Loesche School,03,141
1647,William H. Loesche School,04,124
1648,William H. Loesche School,05,146
1649,William H. Loesche School,All Grades,885
1650,The Workshop School,09,72
1651,The Workshop School,10,64
1652,The Workshop School,11,52
1653,The Workshop School,12,68
1654,The Workshop School,All Grades,256
1655,John Hancock Demonstration School,00,80
1656,John Hancock Demonstration School,01,77
1657,John Hancock Demonstration School,02,86
1658,John Hancock Demonstration School,03,78
1659,John Hancock Demonstration School,04,78
1660,John Hancock Demonstration School,05,77
1661,John Hancock Demonstration School,06,92
1662,John Hancock Demonstration School,07,100
1663,John Hancock Demonstration School,08,101
1664,John Hancock Demonstration School,All Grades,769
1665,Philadelphia Virtual Academy,06,9
1666,Philadelphia Virtual Academy,07,20
1667,Philadelphia Virtual Academy,08,30
1668,Philadelphia Virtual Academy,09,85
1669,Philadelphia Virtual Academy,10,115
1670,Philadelphia Virtual Academy,11,129
1671,Philadelphia Virtual Academy,12,163
1672,Philadelphia Virtual Academy,All Grades,551

* Here I wanted to get an idea of the enrollment of students at each school and within each grade. I think it is important to keep in mind the number of students that attend each school in order to better analyze the influence that school size may have.

* This file is an edited version of the Enrollment/Demographics file that was uploaded above.  I streamlined the original data set to just show the 65 schools that are within a three mile radius of Penn's campus.

In [7]:
penn_phl_schools = pd.read_csv('../data/penn_phl_school_ed.csv')

In [8]:
penn_phl_schools.shape

(66, 33)

In [9]:
penn_phl_schools.describe()

,SRC School ID,Student Enrollment,ELL Count,ELL Pct,Not ELL Count,Not ELL Pct,IEP Count,IEP Pct,Not IEP Count,Not IEP Pct,...,Black/African American Count,Black/African American Pct,Hispanic Count,Hispanic Pct,Multi-Race Count,Multi-Race Pct,Pacific Islander Count,Pacific Islander Pct,White Count,White Pct
count,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,...,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000,66.000000
mean,255.590909,479.090909,38.015152,7.029394,441.075758,92.970606,69.803030,16.456061,409.287879,83.543939,...,304.045455,69.095152,43.742424,7.885152,26.090909,5.303485,0.242424,0.053182,57.469697,9.889848
std,159.736030,196.900344,66.661370,10.229636,183.033525,10.229636,37.889402,8.959386,203.378598,8.959386,...,142.641393,29.396203,68.734340,10.045728,20.188136,2.957150,0.556379,0.123003,100.436313,15.067081
min,101.000000,169.000000,0.000000,0.000000,169.000000,54.070000,10.000000,0.820000,110.000000,58.980000,...,12.000000,4.290000,2.000000,0.450000,4.000000,1.040000,0.000000,0.000000,0.000000,0.000000
25%,137.250000,358.500000,3.000000,0.635000,320.500000,89.980000,48.000000,10.302500,258.750000,79.050000,...,190.250000,53.857500,8.000000,2.120000,12.250000,2.887500,0.000000,0.000000,3.000000,0.902500
50%,230.500000,454.000000,9.000000,2.025000,415.500000,97.975000,58.500000,15.010000,388.000000,84.990000,...,324.000000,82.770000,18.000000,4.315000,19.500000,4.575000,0.000000,0.000000,7.500000,1.975000
75%,264.750000,546.750000,44.500000,10.020000,495.250000,99.365000,83.750000,20.950000,479.000000,89.697500,...,400.000000,93.102500,46.500000,9.172500,33.750000,7.267500,0.000000,0.000000,66.250000,11.360000
max,878.000000,1213.000000,373.000000,45.930000,1209.000000,100.000000,205.000000,41.020000,1203.000000,99.180000,...,636.000000,96.360000,386.000000,50.990000,116.000000,12.910000,3.000000,0.640000,491.000000,65.100000

In [10]:
penn_phl_schools.columns

Index(['School Year', 'SRC School ID', 'School Name', 'Learning Network',
       'Grade Level', 'Student Enrollment', 'ELL Count', 'ELL Pct',
       'Not ELL Count', 'Not ELL Pct', 'IEP Count', 'IEP Pct', 'Not IEP Count',
       'Not IEP Pct', 'Female Count', 'Female Pct', 'Male Count', 'Male Pct',
       'American Indian Count', 'American Indian Pct', 'Asian Count',
       'Asian Pct', 'Black/African American Count',
       'Black/African American Pct', 'Hispanic Count', 'Hispanic Pct',
       'Multi-Race Count', 'Multi-Race Pct', 'Pacific Islander Count',
       'Pacific Islander Pct', 'White Count', 'White Pct',
       'CEP Economically Disadvantaged Rate'],
      dtype='object')

In [11]:
penn_phl_schools[['School Name','Student Enrollment', 'CEP Economically Disadvantaged Rate']]

,School Name,Student Enrollment,CEP Economically Disadvantaged Rate
0,John Bartram High School,534,100.00
1,West Philadelphia High School,448,100.00
2,Paul Robeson High School for Human Services,307,100.00
3,William L. Sayre High School,412,100.00
4,William T. Tilden School,360,100.00
5,Motivation High School,401,100.00
6,John Barry School,654,100.00
7,William C. Bryant School,440,100.00
8,Joseph W. Catharine School,460,100.00
9,Benjamin B. Comegys School,485,100.00
10,Sadie Alexander School,576,44.44
11,Andrew Hamilton School,499,100.00
12,Avery D. Harrington School,477,100.00
13,Henry C. Lea School,525,100.00
14,William C. Longstreth School,390,100.00
15,Morton McMichael School,358,100.00
16,S. Weir Mitchell School,534,100.00
17,Thomas G. Morton School,567,100.00
18,Samuel Powel School,244,95.74
19,James Rhoads School,510,100.00
20,Martha Washington School,350,100.00
21,Add B. Anderson School,481,100.00
22,Alain Locke School,440,100.00
23,Rudolph Blankenburg School,422,100.00
24,Middle Years Alternative School,272,100.00
25,South Philadelphia High School,617,100.00
26,Benjamin Franklin High School,425,100.00
27,High School for Creative and Performing Arts S...,747,64.69
28,Science Leadership Academy Middle School,270,80.00
29,Julia R. Masterman School,1213,31.00
...,...,...,...
36,William M. Meredith School,573,24.57
37,Robert Morris School,257,100.00
38,Girard Academic Music Program,620,52.65
39,Edwin M. Stanton School,305,100.00
40,Albert M. Greenfield School,665,25.02
41,Chester A. Arthur School,272,87.65
42,Laura W. Waring School,289,100.00
43,Andrew Jackson School,588,96.05
44,Abram S. Jenks School,280,100.00
45,Eliza B. Kirkbride School,553,100.00
46,George W. Nebinger School,468,98.12
47,Academy at Palumbo,1060,88.15
48,Southwark School,863,100.00
49,Science Leadership Academy,500,50.88
50,Constitution High School,385,94.75
51,Vare-Washington School,369,100.00
52,High School of Engineering and Science,932,68.15
53,Strawberry Mansion High School,169,100.00
54,James G. Blaine School,442,100.00
55,William Dick School,498,100.00
56,Edward Heston School,488,100.00
57,Richard R. Wright School,348,100.00
58,Edward Gideon School,257,100.00
59,William D. Kelley School,367,100.00
60,General George G. Meade School,388,100.00
61,Parkway Center City Middle College High School,496,93.23
62,Parkway West High School,319,100.00
63,Vaux High School: A Big Picture,211,100.00
64,The Workshop School,256,100.00
65,Philadelphia Virtual Academy,551,.

* I wanted to isolate the CEP rate to get a better understanding of the socioeconomic standing of the student bodies at each of the schools. By placing this alongside student enrollment, it provides each CEP percentage with a better reference point.

In [12]:
penn_phl_schools['CEP Economically Disadvantaged Rate'].value_counts()

100.00    47
50.88      1
64.69      1
88.15      1
80.00      1
99.18      1
31.00      1
68.15      1
52.65      1
44.44      1
93.23      1
95.74      1
98.12      1
87.65      1
96.05      1
69.54      1
25.02      1
24.57      1
94.75      1
.          1
Name: CEP Economically Disadvantaged Rate, dtype: int64

* This code helped me to conclude that in 47 of the 65 schools, that are within three miles of Penn's campus, all of their students are eligible for CEP.  Moving forward this information is going to be important for me to keep in mind, especially when making comparisons to the rest of the schools in the district.

* Below is a look at the schools that have the lowest CEP rates, with William M. Meredith having the lowest at 24% of students qualifying for CEP.

In [13]:
penn_phl_schools.iloc[['10', '27','29','34','36','38','40','49','52']]

,School Year,SRC School ID,School Name,Learning Network,Grade Level,Student Enrollment,ELL Count,ELL Pct,Not ELL Count,Not ELL Pct,...,Black/African American Pct,Hispanic Count,Hispanic Pct,Multi-Race Count,Multi-Race Pct,Pacific Islander Count,Pacific Islander Pct,White Count,White Pct,CEP Economically Disadvantaged Rate
10,2018-2019,128,Sadie Alexander School,Network 2,All Grades,576,63,10.94,513,89.06,...,19.97,26,4.51,66,11.46,2,0.35,248,43.06,44.44
27,2018-2019,202,High School for Creative and Performing Arts S...,Network 1,All Grades,747,9,1.20,738,98.80,...,53.55,80,10.71,34,4.55,1,0.13,183,24.50,64.69
29,2018-2019,214,Julia R. Masterman School,Network 1,All Grades,1213,4,0.33,1209,99.67,...,15.50,64,5.28,116,9.56,0,0.00,491,40.48,31.00
34,2018-2019,234,General George A. McCall School,Network 3,All Grades,711,154,21.66,557,78.34,...,11.11,28,3.94,60,8.44,0,0.00,183,25.74,69.54
36,2018-2019,238,William M. Meredith School,Network 3,All Grades,573,8,1.40,565,98.60,...,7.68,32,5.58,74,12.91,1,0.17,373,65.10,24.57
38,2018-2019,241,Girard Academic Music Program,Network 1,All Grades,620,4,0.65,616,99.35,...,24.52,35,5.65,56,9.03,0,0.00,255,41.13,52.65
40,2018-2019,247,Albert M. Greenfield School,Network 3,All Grades,665,24,3.61,641,96.39,...,18.05,39,5.86,72,10.83,0,0.00,376,56.54,25.02
49,2018-2019,265,Science Leadership Academy,Innovation,All Grades,500,11,2.20,489,97.80,...,36.60,50,10.00,23,4.60,0,0.00,188,37.60,50.88
52,2018-2019,403,High School of Engineering and Science,Network 4,All Grades,932,12,1.29,920,98.71,...,68.24,86,9.23,52,5.58,0,0.00,58,6.22,68.15

* Continuing in my exploration, I wanted to separate out all of the schools that have less than 400 total students enrolled. I wanted to take a closer look at these schools, and see if they have any other similarities amongst each other, or if any other differences arose in comparison to the schools that have upwards of 400 total students enrolled.

 * Below is a look at the schools that have under 400 students enrolled.

In [14]:
penn_phl_schools.iloc[['2', '18', '64','62', '57', '58', '59', '53', '20', '28', '37', '14','4','24','35','41','42','44','50','51']]

,School Year,SRC School ID,School Name,Learning Network,Grade Level,Student Enrollment,ELL Count,ELL Pct,Not ELL Count,Not ELL Pct,...,Black/African American Pct,Hispanic Count,Hispanic Pct,Multi-Race Count,Multi-Race Pct,Pacific Islander Count,Pacific Islander Pct,White Count,White Pct,CEP Economically Disadvantaged Rate
2,2018-2019,105,Paul Robeson High School for Human Services,Network 1,All Grades,307,9,2.93,298,97.07,...,94.46,4,1.30,10,3.26,0,0.00,0,0.00,100.00
18,2018-2019,139,Samuel Powel School,Network 2,All Grades,244,1,0.41,243,99.59,...,77.05,5,2.05,18,7.38,0,0.00,21,8.61,95.74
64,2018-2019,856,The Workshop School,Innovation,All Grades,256,9,3.52,247,96.48,...,85.55,6,2.34,16,6.25,1,0.39,5,1.95,100.00
62,2018-2019,509,Parkway West High School,Network 13,All Grades,319,7,2.19,312,97.81,...,93.42,4,1.25,10,3.13,0,0.00,3,0.94,100.00
57,2018-2019,447,Richard R. Wright School,Network 4,All Grades,348,2,0.57,346,99.43,...,90.80,16,4.60,10,2.87,0,0.00,4,1.15,100.00
58,2018-2019,453,Edward Gideon School,Network 11,All Grades,257,1,0.39,256,99.61,...,95.33,7,2.72,4,1.56,0,0.00,1,0.39,100.00
59,2018-2019,456,William D. Kelley School,Network 4,All Grades,367,0,0.00,367,100.00,...,93.19,8,2.18,11,3.00,0,0.00,4,1.09,100.00
53,2018-2019,414,Strawberry Mansion High School,Network 11,All Grades,169,0,0.00,169,100.00,...,91.12,6,3.55,4,2.37,0,0.00,3,1.78,100.00
20,2018-2019,142,Martha Washington School,Network 2,All Grades,350,2,0.57,348,99.43,...,86.29,7,2.00,33,9.43,0,0.00,7,2.00,100.00
28,2018-2019,205,Science Leadership Academy Middle School,Innovation,All Grades,270,3,1.11,267,98.89,...,62.96,19,7.04,33,12.22,0,0.00,32,11.85,80.00
37,2018-2019,239,Robert Morris School,Network 3,All Grades,257,2,0.78,255,99.22,...,89.88,13,5.06,11,4.28,0,0.00,2,0.78,100.00
14,2018-2019,135,William C. Longstreth School,Network 12,All Grades,390,10,2.56,380,97.44,...,94.87,6,1.54,13,3.33,0,0.00,0,0.00,100.00
4,2018-2019,113,William T. Tilden School,Network 10,All Grades,360,62,17.22,298,82.78,...,79.72,27,7.50,18,5.00,0,0.00,4,1.11,100.00
24,2018-2019,158,Middle Years Alternative School,Network 2,All Grades,272,27,9.93,245,90.07,...,82.72,7,2.57,10,3.68,0,0.00,3,1.10,100.00
35,2018-2019,237,Delaplaine McDaniel School,Network 12,All Grades,377,7,1.86,370,98.14,...,88.06,11,2.92,21,5.57,0,0.00,3,0.80,100.00
41,2018-2019,248,Chester A. Arthur School,Network 12,All Grades,272,6,2.21,266,97.79,...,54.78,13,4.78,25,9.19,0,0.00,71,26.10,87.65
42,2018-2019,249,Laura W. Waring School,Network 3,All Grades,289,17,5.88,272,94.12,...,77.85,26,9.00,19,6.57,0,0.00,7,2.42,100.00
44,2018-2019,252,Abram S. Jenks School,Network 10,All Grades,280,58,20.71,222,79.29,...,4.29,28,10.00,20,7.14,0,0.00,127,45.36,100.00
50,2018-2019,267,Constitution High School,Network 3,All Grades,385,17,4.42,368,95.58,...,70.39,54,14.03,16,4.16,0,0.00,18,4.68,94.75
51,2018-2019,272,Vare-Washington School,Network 3,All Grades,369,118,31.98,251,68.02,...,17.34,131,35.50,47,12.74,0,0.00,51,13.82,100.00

* Below is a look at the three schools with the lowest enrollment of students.

In [15]:
penn_phl_schools.iloc[['53','63','18']]

,School Year,SRC School ID,School Name,Learning Network,Grade Level,Student Enrollment,ELL Count,ELL Pct,Not ELL Count,Not ELL Pct,...,Black/African American Pct,Hispanic Count,Hispanic Pct,Multi-Race Count,Multi-Race Pct,Pacific Islander Count,Pacific Islander Pct,White Count,White Pct,CEP Economically Disadvantaged Rate
53,2018-2019,414,Strawberry Mansion High School,Network 11,All Grades,169,0,0.00,169,100.00,...,91.12,6,3.55,4,2.37,0,0.0,3,1.78,100.00
63,2018-2019,518,Vaux High School: A Big Picture,Innovation,All Grades,211,3,1.42,208,98.58,...,93.36,6,2.84,5,2.37,0,0.0,3,1.42,100.00
18,2018-2019,139,Samuel Powel School,Network 2,All Grades,244,1,0.41,243,99.59,...,77.05,5,2.05,18,7.38,0,0.0,21,8.61,95.74

* Below are the three schools with the most students enrolled

In [16]:
penn_phl_schools.iloc[['29','47','52']]

,School Year,SRC School ID,School Name,Learning Network,Grade Level,Student Enrollment,ELL Count,ELL Pct,Not ELL Count,Not ELL Pct,...,Black/African American Pct,Hispanic Count,Hispanic Pct,Multi-Race Count,Multi-Race Pct,Pacific Islander Count,Pacific Islander Pct,White Count,White Pct,CEP Economically Disadvantaged Rate
29,2018-2019,214,Julia R. Masterman School,Network 1,All Grades,1213,4,0.33,1209,99.67,...,15.50,64,5.28,116,9.56,0,0.0,491,40.48,31.00
47,2018-2019,262,Academy at Palumbo,Network 1,All Grades,1060,32,3.02,1028,96.98,...,43.58,112,10.57,53,5.00,0,0.0,127,11.98,88.15
52,2018-2019,403,High School of Engineering and Science,Network 4,All Grades,932,12,1.29,920,98.71,...,68.24,86,9.23,52,5.58,0,0.0,58,6.22,68.15

* This file provides a "score card" for each of the schools in the Philadelphia District.  The score card is measured across 69 metrics.  I narrowed my search in on this file to only focus on the metrics that are relevant to my research questions.  But this file helps to continue to provide more insight into each of the schools.

In [17]:
metric_scores = pd.read_csv('../data/phl_school_metric_scores_revised.csv')

In [18]:
metric_scores.shape

(321, 337)

In [19]:
metric_scores.columns

Index(['School', 'SRC School ID', 'ULCS Code', 'Report', 'Rpt Type Long',
       'Street Address', 'City', 'State', 'Zip Code', 'Phone Number',
       ...
       'FAFSA Tier', 'Student Survey College & Career Score',
       'Student Survey College & Career Pts Earn',
       'Student Survey College & Career Pts Poss',
       'Student Survey College & Career Pct Earn',
       'Student Survey College & Career Tier',
       'Teach Effect Distinguished Score', 'Teach Effect Instruction Score',
       'Teacher Attendance Score', 'Student Survey Teaching Score'],
      dtype='object', length=337)

In [20]:
metric_scores.describe()

,ULCS Code,Zip Code,Enrollment,Notes,Clim Score,Clim Pts Earn,Clim Pts Poss,Attendance (95%+) Score,Attendance (95%+) Denom,Attendance (95%+) Pts Earn,...,OSS Pts Poss,OSS Pct Earn,Parent Survey Climate Score,Parent Survey Climate Pts Earn,Parent Survey Climate Pts Poss,Parent Survey Climate Pct Earn,Parent Survey Participation Score,Parent Survey Participation Pts Earn,Parent Survey Participation Pts Poss,Parent Survey Participation Pct Earn
count,321.000000,321.000000,321.000000,0.0,321.000000,321.000000,321.000000,321.000000,321.000000,321.000000,...,321.000000,321.000000,321.000000,321.000000,321.0,321.000000,321.000000,321.000000,321.0,321.000000
mean,4502.869159,19131.847352,593.598131,NaN,54.000000,14.739003,27.408100,47.595016,646.308411,5.081090,...,3.612150,62.323988,49.809969,0.498100,1.0,49.809969,17.295950,0.231589,1.0,23.158879
std,2082.983778,12.841038,334.667406,NaN,25.404724,7.328808,4.382329,16.960004,361.301521,3.750015,...,0.657796,29.870989,41.122432,0.411224,0.0,41.122432,16.444498,0.314349,0.0,31.434898
min,1010.000000,19102.000000,67.000000,NaN,3.000000,0.700000,20.000000,7.000000,72.000000,0.000000,...,2.500000,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,0.000000,1.0,0.000000
25%,3321.000000,19123.000000,398.000000,NaN,35.000000,9.280000,20.000000,35.000000,437.000000,1.790000,...,2.500000,41.000000,0.000000,0.000000,1.0,0.000000,5.000000,0.000000,1.0,0.000000
50%,3424.000000,19133.000000,528.000000,NaN,56.000000,14.700000,30.000000,47.000000,586.000000,4.590000,...,4.000000,68.000000,76.000000,0.760000,1.0,76.000000,12.000000,0.060000,1.0,6.000000
75%,6230.000000,19143.000000,707.000000,NaN,73.000000,19.950000,30.000000,59.000000,764.000000,7.690000,...,4.000000,88.000000,85.000000,0.850000,1.0,85.000000,25.000000,0.380000,1.0,38.000000
max,8770.000000,19154.000000,3363.000000,NaN,98.000000,29.510000,30.000000,95.000000,3608.000000,12.000000,...,4.000000,100.000000,99.000000,0.990000,1.0,99.000000,83.000000,1.000000,1.0,100.000000

In [21]:
metric_scores[['School', 'Grades Served', 'Retention Score', 'Grad Score']]

,School,Grades Served,Retention Score,Grad Score
0,John Bartram High School,'9-12',71,67
1,West Philadelphia High School,'9-12',74,66
2,High School of the Future,'9-12',89,86
3,Paul Robeson High School for Human Services,'9-12',93,95
4,William L. Sayre High School,'9-12',67,49
5,William T. Tilden School,'5-8',74,.
6,Motivation High School,'9-12',86,83
7,John Barry School,'K-8',69,.
8,William C. Bryant School,'K-8',76,.
9,Joseph W. Catharine School,'K-5',77,.
10,Benjamin B. Comegys School,'K-8',74,.
11,Sadie Alexander School,'K-8',92,.
12,Andrew Hamilton School,'K-8',80,.
13,Avery D. Harrington School,'K-8',69,.
14,Henry C. Lea School,'K-8',86,.
15,William C. Longstreth School,'K-8',71,.
16,Morton McMichael School,'K-8',80,.
17,S. Weir Mitchell School,'K-8',73,.
18,Thomas G. Morton School,'K-5',73,.
19,Samuel Powel School,'K-4',90,.
20,John M. Patterson School,'K-4',79,.
21,James Rhoads School,'K-8',74,.
22,Martha Washington School,'K-8',87,.
23,Penrose School,'K-8',84,.
24,Add B. Anderson School,'K-8',78,.
25,Alain Locke School,'K-8',70,.
26,Rudolph Blankenburg School,'K-8',69,.
27,Middle Years Alternative School,'5-8',92,.
28,South Philadelphia High School,'9-12',78,53
29,Benjamin Franklin High School,'9-12',67,59
...,...,...,...,...
291,Sankofa Freedom Academy Charter School,'K-8',91,.
292,Franklin Towne Charter Elementary School,'K-8',98,.
293,Tacony Academy Charter School,'9-12',95,96
294,Tacony Academy Charter School,'K-8',96,.
295,Aspira Charter School at Stetson,'5-8',92,.
296,Mastery Charter School at Harrity,'K-8',89,.
297,Mastery Charter School at Mann,'K-6',94,.
298,Mastery Charter School at Smedley,'K-6',92,.
299,Universal Charter School at Bluford,'K-6',89,.
300,Universal Charter School at Daroff,'K-8',85,.
301,Mastery Charter School at Douglass,'K-8',79,.
302,Aspira Charter School at Olney,'9-12',78,71
303,Mastery Charter School at Clymer,'K-6',89,.
304,Mastery Charter School at Gratz,'9-12',77,62
305,Mastery Charter School at Gratz,'7-8',92,.
306,Universal Charter School at Audenried,'9-12',76,69
307,Universal Charter School at Vare,'5-8',87,.
308,Lindley Academy Charter at Birney,'K-8',92,.
309,Mastery Charter School at Cleveland,'K-8',87,.
310,Universal Charter School at Creighton,'K-8',91,.
311,The Philadelphia Charter School for Arts and S...,'K-8',91,.
312,Memphis Street Academy Charter School at J.P. ...,'5-8',83,.
313,Universal Charter School at Alcorn,'K-8',82,.
314,Mastery Charter School at Pastorius,'K-8',92,.
315,Mastery Charter School at Wister,'K-5',87,.
316,Global Leadership Academy at Huey,'K-8',91,.
317,MaST Community Charter School II,'K-4',96,.
318,TECH Freire Charter School,'9-11',72,.
319,Independence Charter School West,'K-4',93,.
320,KIPP West Philadelphia Charter School,'K-1',94,.

In [22]:
metric_scores[['School', 'Grades Served', 'Attendance (95%+) Score', 'Attendance (<80%) Score']]

,School,Grades Served,Attendance (95%+) Score,Attendance (<80%) Score
0,John Bartram High School,'9-12',26,35
1,West Philadelphia High School,'9-12',14,40
2,High School of the Future,'9-12',48,8
3,Paul Robeson High School for Human Services,'9-12',35,4
4,William L. Sayre High School,'9-12',14,49
5,William T. Tilden School,'5-8',54,10
6,Motivation High School,'9-12',68,3
7,John Barry School,'K-8',28,19
8,William C. Bryant School,'K-8',37,10
9,Joseph W. Catharine School,'K-5',49,8
10,Benjamin B. Comegys School,'K-8',33,9
11,Sadie Alexander School,'K-8',80,1
12,Andrew Hamilton School,'K-8',32,12
13,Avery D. Harrington School,'K-8',24,21
14,Henry C. Lea School,'K-8',47,10
15,William C. Longstreth School,'K-8',37,12
16,Morton McMichael School,'K-8',37,10
17,S. Weir Mitchell School,'K-8',33,12
18,Thomas G. Morton School,'K-5',40,11
19,Samuel Powel School,'K-4',60,2
20,John M. Patterson School,'K-4',50,7
21,James Rhoads School,'K-8',21,18
22,Martha Washington School,'K-8',42,9
23,Penrose School,'K-8',42,13
24,Add B. Anderson School,'K-8',40,10
25,Alain Locke School,'K-8',32,14
26,Rudolph Blankenburg School,'K-8',24,23
27,Middle Years Alternative School,'5-8',63,2
28,South Philadelphia High School,'9-12',32,27
29,Benjamin Franklin High School,'9-12',17,38
...,...,...,...,...
291,Sankofa Freedom Academy Charter School,'K-8',49,3
292,Franklin Towne Charter Elementary School,'K-8',72,0
293,Tacony Academy Charter School,'9-12',26,13
294,Tacony Academy Charter School,'K-8',55,2
295,Aspira Charter School at Stetson,'5-8',31,10
296,Mastery Charter School at Harrity,'K-8',47,6
297,Mastery Charter School at Mann,'K-6',49,5
298,Mastery Charter School at Smedley,'K-6',41,4
299,Universal Charter School at Bluford,'K-6',48,6
300,Universal Charter School at Daroff,'K-8',48,9
301,Mastery Charter School at Douglass,'K-8',29,16
302,Aspira Charter School at Olney,'9-12',7,44
303,Mastery Charter School at Clymer,'K-6',35,7
304,Mastery Charter School at Gratz,'9-12',38,19
305,Mastery Charter School at Gratz,'7-8',44,11
306,Universal Charter School at Audenried,'9-12',16,37
307,Universal Charter School at Vare,'5-8',40,13
308,Lindley Academy Charter at Birney,'K-8',45,4
309,Mastery Charter School at Cleveland,'K-8',49,4
310,Universal Charter School at Creighton,'K-8',52,7
311,The Philadelphia Charter School for Arts and S...,'K-8',46,5
312,Memphis Street Academy Charter School at J.P. ...,'5-8',31,14
313,Universal Charter School at Alcorn,'K-8',75,3
314,Mastery Charter School at Pastorius,'K-8',40,9
315,Mastery Charter School at Wister,'K-5',18,21
316,Global Leadership Academy at Huey,'K-8',49,6
317,MaST Community Charter School II,'K-4',60,1
318,TECH Freire Charter School,'9-11',35,17
319,Independence Charter School West,'K-4',47,5
320,KIPP West Philadelphia Charter School,'K-1',66,3

* Some of the metrics I found relevant and singled out; School Name and the Grades Served, Retention Rate, Graduation Rate, percentage of students attending more than 95% of instructional days, and percentage of students attending less than 80% of instructional days.

* However, I found there too be too many rows with "Not Applicable" or "Data Not Available" that I decided to go back and remove from the original spreadsheet.  I then replaced it with the clean one below.
But, note that, only the high schools' graduation rates were presented.

In [25]:
pd.read_csv('../data/phl_school_metric_scores_revised.csv')

,School,SRC School ID,ULCS Code,Report,Rpt Type Long,Street Address,City,State,Zip Code,Phone Number,...,FAFSA Tier,Student Survey College & Career Score,Student Survey College & Career Pts Earn,Student Survey College & Career Pts Poss,Student Survey College & Career Pct Earn,Student Survey College & Career Tier,Teach Effect Distinguished Score,Teach Effect Instruction Score,Teacher Attendance Score,Student Survey Teaching Score
0,John Bartram High School,101,1010,HS,High School,2401 S. 67th St.,Philadelphia,PA,19142,215-400-8100,...,INTERVENE,33,0.33,1,33,WATCH,.,.,52,43
1,West Philadelphia High School,102,1020,HS,High School,4901 Chestnut St.,Philadelphia,PA,19139,215-400-7900,...,WATCH,0,0,1,0,INTERVENE,.,.,49,0
2,High School of the Future,103,1030,HS,High School,4021 Parkside Ave.,Philadelphia,PA,19104,215-400-7790,...,REINFORCE,40,0.4,1,40,WATCH,.,.,56,36
3,Paul Robeson High School for Human Services,105,1050,HS,High School,4125 Ludlow St.,Philadelphia,PA,19104,215-400-7780,...,MODEL,39,0.39,1,39,WATCH,.,.,68,53
4,William L. Sayre High School,110,1100,HS,High School,5800 Walnut St.,Philadelphia,PA,19139,215-400-7800,...,INTERVENE,0,0,1,0,INTERVENE,.,.,71,0
5,William T. Tilden School,113,1130,MS,Middle School,6601 Elmwood Ave.,Philadelphia,PA,19142,215-400-8170,...,.,.,.,.,.,.,.,.,50,47
6,Motivation High School,119,1190,HS,High School,5900 Baltimore Ave.,Philadelphia,PA,19143,215-400-7930,...,REINFORCE,0,0,1,0,INTERVENE,.,.,54,0
7,John Barry School,120,1200,K8,K8 School,5900 Race St.,Philadelphia,PA,19139,215-400-7640,...,.,.,.,.,.,.,.,.,49,50
8,William C. Bryant School,123,1230,K8,K8 School,6001 Cedar Ave.,Philadelphia,PA,19143,215-400-7910,...,.,.,.,.,.,.,.,.,41,55
9,Joseph W. Catharine School,125,1250,ES,Elementary School,6600 Chester Ave.,Philadelphia,PA,19142,215-400-8150,...,.,.,.,.,.,.,.,.,53,68
10,Benjamin B. Comegys School,126,1260,K8,K8 School,5100 Greenway Ave.,Philadelphia,PA,19143,215-400-7860,...,.,.,.,.,.,.,.,.,58,54
11,Sadie Alexander School,128,1280,K8,K8 School,4209 Spruce St.,Philadelphia,PA,19104,215-400-7760,...,.,.,.,.,.,.,.,.,79,63
12,Andrew Hamilton School,129,1290,K8,K8 School,5640 Spruce St.,Philadelphia,PA,19139,215-400-7650,...,.,.,.,.,.,.,.,.,46,0
13,Avery D. Harrington School,130,1300,K8,K8 School,5300 Baltimore Ave.,Philadelphia,PA,19143,215-400-7920,...,.,.,.,.,.,.,.,.,44,44
14,Henry C. Lea School,134,1340,K8,K8 School,4700 Locust St.,Philadelphia,PA,19139,215-400-7660,...,.,.,.,.,.,.,.,.,50,59
15,William C. Longstreth School,135,1350,K8,K8 School,5700 Willows Ave.,Philadelphia,PA,19143,215-400-7870,...,.,.,.,.,.,.,.,.,63,53
16,Morton McMichael School,136,1360,K8,K8 School,3543 Fairmount Ave.,Philadelphia,PA,19104,215-400-7750,...,.,.,.,.,.,.,.,.,77,55
17,S. Weir Mitchell School,137,1370,K8,K8 School,5500 Kingsessing Ave.,Philadelphia,PA,19143,215-400-7880,...,.,.,.,.,.,.,.,.,61,49
18,Thomas G. Morton School,138,1380,ES,Elementary School,2501 S. 63rd St.,Philadelphia,PA,19142,215-400-8160,...,.,.,.,.,.,.,.,.,55,69
19,Samuel Powel School,139,1390,ES,Elementary School,301 N. 36th St.,Philadelphia,PA,19104,215-400-7740,...,.,.,.,.,.,.,.,.,76,76
20,John M. Patterson School,140,1400,ES,Elementary School,7000 Buist Ave.,Philadelphia,PA,19142,215-400-8190,...,.,.,.,.,.,.,.,.,49,66
21,James Rhoads School,141,1410,K8,K8 School,4901 Parrish St.,Philadelphia,PA,19139,215-400-7680,...,.,.,.,.,.,.,.,.,68,44
22,Martha Washington School,142,1420,K8,K8 School,766 N. 44th St.,Philadelphia,PA,19104,215-400-7770,...,.,.,.,.,.,.,.,.,74,60
23,Penrose School,144,1440,K8,K8 School,2515 S. 78th St.,Philadelphia,PA,19153,215-400-8310,...,.,.,.,.,.,.,.,.,56,47
24,Add B. Anderson School,146,1460,K8,K8 School,1034 S. 60th St.,Philadelphia,PA,19143,215-400-7890,...,.,.,.,.,.,.,.,.,45,45
25,Alain Locke School,147,1470,K8,K8 School,4550 Haverford Ave.,Philadelphia,PA,19139,215-400-7670,...,.,.,.,.,.,.,.,.,75,48
26,Rudolph Blankenburg School,149,1490,K8,K8 School,4600 W. Girard Ave.,Philadelphia,PA,19131,215-400-7280,...,.,.,.,.,.,.,.,.,45,48
27,Middle Years Alternative School,158,1580,MS,Middle School,4725 Fairmount Ave.,Philadelphia,PA,19139,215-400-7720,...,.,.,.,.,.,.,.,.,68,45
28,South Philadelphia High School,200,2000,HS,High School,2101 S. Broad St.,Philadelphia,PA,19148,215-400-8400,...,INTERVENE,31,0.31,1,31,WATCH,.,.,56,39
29,Benjamin Franklin High School,201,2010,HS,High School,550 N. Broad St.,Philadelphia,PA,19130,215-400-7600,...,INTERVENE,27,0.27,1,27,WATCH,.,.,49,38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,Sankofa Freedom Academy Charter School,W99,3399,K8,K8 School,2501 Kensington Ave.,Philadelphia,PA,19125,215-288-2001,...,.,.,.,.,.,.,.,.,.,50
292,Franklin Towne Charter Elementary School,X03,3403,K8,K8 School,4259 Richmond St.,Philadelphia,PA,19137,215-289-3389,...,.,.,.,.,.,.,.,.,.,65
293,Tacony Academy Charter School,X04,3404,HS,High School,1330 Rhawn St.,Philadelphia,PA,19111,215-742-5100,...,WATCH,36,0.36,1,36,WATCH,.,.,.,41
294,Tacony Academy Charter School,X04,3404,K8,K8 School,1330 Rhawn St.,Philadelphia,PA,19111,215-742-5100,...,.,.,.,.,.,.,.,.,.,63
295,Aspira Charter School at Stetson,X06,3406,MS,Middle School,3200 B. St.,Philadelphia,PA,19134,215-291-4720,...,.,.,.,.,.,.,.,.,.,54
296,Mastery Charter School at Harrity,X07,3407,K8,K8 School,5601 Christian St.,Philadelphia,PA,19143,215-471-2908,...,.,.,.,.,.,.,.,.,.,0
297,Mastery Charter School at Mann,X08,3408,ES,Elementary School,5376 W. Berks St.,Philadelphia,PA,19131,215-581-5616,...,.,.,.,.,.,.,.,.,.,0
298,Mastery Charter School at Smedley,X09,3409,ES,Elementary School,1790 Bridge St.,Philadelphia,PA,19124,215-537-2523,...,.,.,.,.,.,.,.,.,.,0
299,Universal Charter School at Bluford,X10,3410,ES,Elementary School,5801 Media St.,Philadelphia,PA,19131,215-581-5502,...,.,.,.,.,.,.,.,.,.,0
300,Universal Charter School at Daroff,X11,3411,K8,K8 School,5630 Vine St.,Philadelphia,PA,19139,215-471-2905,...,.,.,.,.,.,.,.,.,.,0
301,Mastery Charter School at Douglass,X12,3412,K8,K8 School,2118 W. Norris St.,Philadelphia,PA,19121,215-684-5063,...,.,.,.,.,.,.,.,.,.,0
302,Aspira Charter School at Olney,X14,3414,HS,High School,100 W. Duncannon Ave.,Philadelphia,PA,19120,215-456-3014,...,WATCH,40,0.4,1,40,WATCH,.,.,.,48
303,Mastery Charter School at Clymer,X15,3415,ES,Elementary School,1201 W. Rush St.,Philadelphia,PA,19133,215-223-2243,...,.,.,.,.,.,.,.,.,.,0
304,Mastery Charter School at Gratz,X16,3416,HS,High School,1798 W. Hunting Park Ave.,Philadelphia,PA,19140,215-227-4408,...,MODEL,0,0,1,0,INTERVENE,.,.,.,0
305,Mastery Charter School at Gratz,X16,3416,MS,Middle School,1798 W. Hunting Park Ave.,Philadelphia,PA,19140,215-227-4408,...,.,.,.,.,.,.,.,.,.,0
306,Universal Charter School at Audenried,X17,3417,HS,High School,3301 Tasker St.,Philadelphia,PA,19145,215-952-4801,...,WATCH,0,0,1,0,INTERVENE,.,.,.,0
307,Universal Charter School at Vare,X18,3418,MS,Middle School,2100 S. 24th St.,Philadelphia,PA,19145,215-952-8611,...,.,.,.,.,.,.,.,.,.,48
308,Lindley Academy Charter at Birney,X19,3419,K8,K8 School,900 Lindley Ave.,Philadelphia,PA,19141,215-456-3000,...,.,.,.,.,.,.,.,.,.,53
309,Mastery Charter School at Cleveland,X20,3420,K8,K8 School,3701 N. 19th St.,Philadelphia,PA,19140,215-227-5042,...,.,.,.,.,.,.,.,.,.,0
310,Universal Charter School at Creighton,X21,3421,K8,K8 School,5401 Tabor Ave.,Philadelphia,PA,19120,215-537-2531,...,.,.,.,.,.,.,.,.,.,54
311,The Philadelphia Charter School for Arts and S...,X22,3422,K8,K8 School,1197 Haworth St.,Philadelphia,PA,19124,215-537-2520,...,.,.,.,.,.,.,.,.,.,55
312,Memphis Street Academy Charter School at J.P. ...,X23,3423,MS,Middle School,2950 Memphis St.,Philadelphia,PA,19134,215-291-4709,...,.,.,.,.,.,.,.,.,.,53
313,Universal Charter School at Alcorn,X24,3424,K8,K8 School,3200 Dickinson St.,Philadelphia,PA,19146,215-952-6219,...,.,.,.,.,.,.,.,.,.,81
314,Mastery Charter School at Pastorius,X26,3426,K8,K8 School,5650 Sprague St.,Philadelphia,PA,19138,215-951-5689,...,.,.,.,.,.,.,.,.,.,0
315,Mastery Charter School at Wister,X27,3427,ES,Elementary School,67 E. Bringhurst St.,Philadelphia,PA,19144,215-951-4003,...,.,.,.,.,.,.,.,.,.,0
316,Global Leadership Academy at Huey,X28,3428,K8,K8 School,5200 Pine St.,Philadelphia,PA,19143,215-471-2978,...,.,.,.,.,.,.,.,.,.,0
317,MaST Community Charter School II,X40,3440,ES,Elementary School,6238 Rising Sun Ave.,Philadelphia,PA,19111,215-398-7960,...,.,.,.,.,.,.,.,.,.,68
318,TECH Freire Charter School,X41,3441,HS,High School,2221 N. Broad St.,Philadelphia,PA,19132,267-507-1111,...,.,35,0.35,1,35,WATCH,.,.,.,42
319,Independence Charter School West,X42,3442,ES,Elementary School,5600 Chester Ave.,Philadelphia,PA,19143,215-724-5600,...,.,.,.,.,.,.,.,.,.,0
320,KIPP West Philadelphia Charter School,X43,3443,ES,Elementary School,5070 Parkside Ave.,Philadelphia,PA,19131,267-787-5700,...,.,.,.,.,.,.,.,.,.,.

In [26]:
metric_scores_rvsd = pd.read_csv('../data/phl_school_metric_scores_revised.csv')

In [27]:
metric_scores_rvsd[['School','Teacher Attendance Score']]

,School,Teacher Attendance Score
0,John Bartram High School,52
1,West Philadelphia High School,49
2,High School of the Future,56
3,Paul Robeson High School for Human Services,68
4,William L. Sayre High School,71
5,William T. Tilden School,50
6,Motivation High School,54
7,John Barry School,49
8,William C. Bryant School,41
9,Joseph W. Catharine School,53
10,Benjamin B. Comegys School,58
11,Sadie Alexander School,79
12,Andrew Hamilton School,46
13,Avery D. Harrington School,44
14,Henry C. Lea School,50
15,William C. Longstreth School,63
16,Morton McMichael School,77
17,S. Weir Mitchell School,61
18,Thomas G. Morton School,55
19,Samuel Powel School,76
20,John M. Patterson School,49
21,James Rhoads School,68
22,Martha Washington School,74
23,Penrose School,56
24,Add B. Anderson School,45
25,Alain Locke School,75
26,Rudolph Blankenburg School,45
27,Middle Years Alternative School,68
28,South Philadelphia High School,56
29,Benjamin Franklin High School,49
...,...,...
291,Sankofa Freedom Academy Charter School,.
292,Franklin Towne Charter Elementary School,.
293,Tacony Academy Charter School,.
294,Tacony Academy Charter School,.
295,Aspira Charter School at Stetson,.
296,Mastery Charter School at Harrity,.
297,Mastery Charter School at Mann,.
298,Mastery Charter School at Smedley,.
299,Universal Charter School at Bluford,.
300,Universal Charter School at Daroff,.
301,Mastery Charter School at Douglass,.
302,Aspira Charter School at Olney,.
303,Mastery Charter School at Clymer,.
304,Mastery Charter School at Gratz,.
305,Mastery Charter School at Gratz,.
306,Universal Charter School at Audenried,.
307,Universal Charter School at Vare,.
308,Lindley Academy Charter at Birney,.
309,Mastery Charter School at Cleveland,.
310,Universal Charter School at Creighton,.
311,The Philadelphia Charter School for Arts and S...,.
312,Memphis Street Academy Charter School at J.P. ...,.
313,Universal Charter School at Alcorn,.
314,Mastery Charter School at Pastorius,.
315,Mastery Charter School at Wister,.
316,Global Leadership Academy at Huey,.
317,MaST Community Charter School II,.
318,TECH Freire Charter School,.
319,Independence Charter School West,.
320,KIPP West Philadelphia Charter School,.

* Branching off into a new segment, I wanted to separate our the "Teacher Attendance" score.  While not all of the schools had this information available, for those that did I found this information to be really relevant, especially when trying to get a holistic picture of the general culture and environment at each school.

* After revising the original file, I decided that I wanted to make my coding process a little simpler and separate out the schools that are within my selected radius ( no further than three miles outside of Penn's campus; 66 schools) from the remainder of schools in the district.

In [28]:
pd.read_csv('../data/sms_penn_schools.csv')

,School,SRC School ID,ULCS Code,Report,Rpt Type Long,Street Address,City,State,Zip Code,Phone Number,...,FAFSA Tier,Student Survey College & Career Score,Student Survey College & Career Pts Earn,Student Survey College & Career Pts Poss,Student Survey College & Career Pct Earn,Student Survey College & Career Tier,Teach Effect Distinguished Score,Teach Effect Instruction Score,Teacher Attendance Score,Student Survey Teaching Score
0,John Bartram High School,101,1010,HS,High School,2401 S. 67th St.,Philadelphia,PA,19142,215-400-8100,...,INTERVENE,33,0.33,1,33,WATCH,.,.,52,43
1,West Philadelphia High School,102,1020,HS,High School,4901 Chestnut St.,Philadelphia,PA,19139,215-400-7900,...,WATCH,0,0,1,0,INTERVENE,.,.,49,0
2,Paul Robeson High School for Human Services,105,1050,HS,High School,4125 Ludlow St.,Philadelphia,PA,19104,215-400-7780,...,MODEL,39,0.39,1,39,WATCH,.,.,68,53
3,William L. Sayre High School,110,1100,HS,High School,5800 Walnut St.,Philadelphia,PA,19139,215-400-7800,...,INTERVENE,0,0,1,0,INTERVENE,.,.,71,0
4,William T. Tilden School,113,1130,MS,Middle School,6601 Elmwood Ave.,Philadelphia,PA,19142,215-400-8170,...,.,.,.,.,.,.,.,.,50,47
5,Motivation High School,119,1190,HS,High School,5900 Baltimore Ave.,Philadelphia,PA,19143,215-400-7930,...,REINFORCE,0,0,1,0,INTERVENE,.,.,54,0
6,John Barry School,120,1200,K8,K8 School,5900 Race St.,Philadelphia,PA,19139,215-400-7640,...,.,.,.,.,.,.,.,.,49,50
7,William C. Bryant School,123,1230,K8,K8 School,6001 Cedar Ave.,Philadelphia,PA,19143,215-400-7910,...,.,.,.,.,.,.,.,.,41,55
8,Joseph W. Catharine School,125,1250,ES,Elementary School,6600 Chester Ave.,Philadelphia,PA,19142,215-400-8150,...,.,.,.,.,.,.,.,.,53,68
9,Benjamin B. Comegys School,126,1260,K8,K8 School,5100 Greenway Ave.,Philadelphia,PA,19143,215-400-7860,...,.,.,.,.,.,.,.,.,58,54
10,Sadie Alexander School,128,1280,K8,K8 School,4209 Spruce St.,Philadelphia,PA,19104,215-400-7760,...,.,.,.,.,.,.,.,.,79,63
11,Andrew Hamilton School,129,1290,K8,K8 School,5640 Spruce St.,Philadelphia,PA,19139,215-400-7650,...,.,.,.,.,.,.,.,.,46,0
12,Avery D. Harrington School,130,1300,K8,K8 School,5300 Baltimore Ave.,Philadelphia,PA,19143,215-400-7920,...,.,.,.,.,.,.,.,.,44,44
13,Henry C. Lea School,134,1340,K8,K8 School,4700 Locust St.,Philadelphia,PA,19139,215-400-7660,...,.,.,.,.,.,.,.,.,50,59
14,William C. Longstreth School,135,1350,K8,K8 School,5700 Willows Ave.,Philadelphia,PA,19143,215-400-7870,...,.,.,.,.,.,.,.,.,63,53
15,Morton McMichael School,136,1360,K8,K8 School,3543 Fairmount Ave.,Philadelphia,PA,19104,215-400-7750,...,.,.,.,.,.,.,.,.,77,55
16,S. Weir Mitchell School,137,1370,K8,K8 School,5500 Kingsessing Ave.,Philadelphia,PA,19143,215-400-7880,...,.,.,.,.,.,.,.,.,61,49
17,Thomas G. Morton School,138,1380,ES,Elementary School,2501 S. 63rd St.,Philadelphia,PA,19142,215-400-8160,...,.,.,.,.,.,.,.,.,55,69
18,Samuel Powel School,139,1390,ES,Elementary School,301 N. 36th St.,Philadelphia,PA,19104,215-400-7740,...,.,.,.,.,.,.,.,.,76,76
19,James Rhoads School,141,1410,K8,K8 School,4901 Parrish St.,Philadelphia,PA,19139,215-400-7680,...,.,.,.,.,.,.,.,.,68,44
20,Martha Washington School,142,1420,K8,K8 School,766 N. 44th St.,Philadelphia,PA,19104,215-400-7770,...,.,.,.,.,.,.,.,.,74,60
21,Add B. Anderson School,146,1460,K8,K8 School,1034 S. 60th St.,Philadelphia,PA,19143,215-400-7890,...,.,.,.,.,.,.,.,.,45,45
22,Alain Locke School,147,1470,K8,K8 School,4550 Haverford Ave.,Philadelphia,PA,19139,215-400-7670,...,.,.,.,.,.,.,.,.,75,48
23,Rudolph Blankenburg School,149,1490,K8,K8 School,4600 W. Girard Ave.,Philadelphia,PA,19131,215-400-7280,...,.,.,.,.,.,.,.,.,45,48
24,Middle Years Alternative School,158,1580,MS,Middle School,4725 Fairmount Ave.,Philadelphia,PA,19139,215-400-7720,...,.,.,.,.,.,.,.,.,68,45
25,South Philadelphia High School,200,2000,HS,High School,2101 S. Broad St.,Philadelphia,PA,19148,215-400-8400,...,INTERVENE,31,0.31,1,31,WATCH,.,.,56,39
26,Benjamin Franklin High School,201,2010,HS,High School,550 N. Broad St.,Philadelphia,PA,19130,215-400-7600,...,INTERVENE,27,0.27,1,27,WATCH,.,.,49,38
27,High School for Creative and Performing Arts,202,2020,HS,High School,901 S. Broad St.,Philadelphia,PA,19147,215-400-8140,...,MODEL,25,0.25,1,25,WATCH,.,.,63,34
28,Science Leadership Academy Middle School,205,2050,MS,Middle School,3600 Market St.,Philadelphia,PA,19104,215-400-8320,...,.,.,.,.,.,.,.,.,92,57
29,Julia R. Masterman School H.S.,214,2140,HS,High School,1699 Spring Garden St.,Philadelphia,PA,19130,215-400-7580,...,MODEL,30,0.3,1,30,WATCH,.,.,73,57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35,General George A. McCall School,234,2340,K8,K8 School,325 S. 7th St.,Philadelphia,PA,19106,215-400-7840,...,.,.,.,.,.,.,.,.,69,61
36,Delaplaine McDaniel School,237,2370,K8,K8 School,1801 S. 22nd St.,Philadelphia,PA,19145,215-400-8220,...,.,.,.,.,.,.,.,.,22,52
37,William M. Meredith School,238,2380,K8,K8 School,725 S. 5th St.,Philadelphia,PA,19147,215-400-7990,...,.,.,.,.,.,.,.,.,68,70
38,Robert Morris School,239,2390,K8,K8 School,2600 W. Thompson St.,Philadelphia,PA,19121,215-400-7320,...,.,.,.,.,.,.,.,.,70,48
39,Girard Academic Music Program H.S.,241,2410,HS,High School,2136 W. Ritner St.,Philadelphia,PA,19145,215-400-8230,...,MODEL,31,0.31,1,31,WATCH,.,.,68,54
40,Girard Academic Music Program M.S.,241,2410,MS,Middle School,2136 W. Ritner St.,Philadelphia,PA,19145,215-400-8230,...,.,.,.,.,.,.,.,.,68,64
41,Edwin M. Stanton School,245,2450,K8,K8 School,901 S. 17th St.,Philadelphia,PA,19146,215-400-7960,...,.,.,.,.,.,.,.,.,55,51
42,Albert M. Greenfield School,247,2470,K8,K8 School,2200 Chestnut St.,Philadelphia,PA,19103,215-400-7810,...,.,.,.,.,.,.,.,.,55,66
43,Chester A. Arthur School,248,2480,K8,K8 School,2000 Catharine St.,Philadelphia,PA,19146,215-400-7940,...,.,.,.,.,.,.,.,.,57,51
44,Laura W. Waring School,249,2490,K8,K8 School,1801 Green St.,Philadelphia,PA,19130,215-400-7560,...,.,.,.,.,.,.,.,.,83,64
45,Andrew Jackson School,251,2510,K8,K8 School,1213 S. 12th St.,Philadelphia,PA,19147,215-400-7970,...,.,.,.,.,.,.,.,.,75,52
46,Abram S. Jenks School,252,2520,ES,Elementary School,2501 S. 13th St.,Philadelphia,PA,19148,215-400-8240,...,.,.,.,.,.,.,.,.,67,79
47,Eliza B. Kirkbride School,258,2580,K8,K8 School,1501 S. 7th St.,Philadelphia,PA,19147,215-400-7980,...,.,.,.,.,.,.,.,.,82,55
48,George W. Nebinger School,259,2590,K8,K8 School,601 Carpenter St.,Philadelphia,PA,19147,215-400-8110,...,.,.,.,.,.,.,.,.,53,57
49,Academy at Palumbo,262,2620,HS,High School,1100 Catharine St.,Philadelphia,PA,19147,215-400-8130,...,MODEL,34,0.34,1,34,WATCH,.,.,80,48
50,Southwark School,264,2640,K8,K8 School,1835 S. 9th St.,Philadelphia,PA,19148,215-400-8280,...,.,.,.,.,.,.,.,.,55,47
51,Science Leadership Academy,265,2650,HS,High School,55 N. 22nd St.,Philadelphia,PA,19103,215-400-7830,...,MODEL,39,0.39,1,39,WATCH,.,.,66,60
52,Constitution High School,267,2670,HS,High School,18 S. 7th St.,Philadelphia,PA,19106,215-400-7850,...,MODEL,37,0.37,1,37,WATCH,.,.,81,48
53,Vare-Washington School,272,2720,K8,K8 School,1198 S. 5th St.,Philadelphia,PA,19147,215-400-8120,...,.,.,.,.,.,.,.,.,67,64
54,High School of Engineering and Science H.S.,403,4030,HS,High School,1600 W. Norris St.,Philadelphia,PA,19121,215-400-7380,...,MODEL,39,0.39,1,39,WATCH,.,.,85,43
55,High School of Engineering and Science M.S.,403,4030,MS,Middle School,1600 W. Norris St.,Philadelphia,PA,19121,215-400-7380,...,.,.,.,.,.,.,.,.,85,57
56,Strawberry Mansion High School,414,4140,HS,High School,3133 Ridge Ave.,Philadelphia,PA,19121,215-400-7500,...,INTERVENE,33,0.33,1,33,WATCH,.,.,41,35
57,James G. Blaine School,422,4220,K8,K8 School,3001 W. Berks St.,Philadelphia,PA,19121,215-400-7330,...,.,.,.,.,.,.,.,.,44,46
58,William Dick School,427,4270,K8,K8 School,2498 W. Diamond St.,Philadelphia,PA,19121,215-400-7340,...,.,.,.,.,.,.,.,.,74,64
59,Edward Heston School,430,4300,K8,K8 School,1621 N. 54th St.,Philadelphia,PA,19131,215-400-7290,...,.,.,.,.,.,.,.,.,51,47
60,William D. Kelley School,456,4560,K8,K8 School,1601 N. 28th St.,Philadelphia,PA,19121,215-400-7370,...,.,.,.,.,.,.,.,.,33,61
61,General George G. Meade School,457,4570,K8,K8 School,1600 N. 18th St.,Philadelphia,PA,19121,215-400-7310,...,.,.,.,.,.,.,.,.,69,61
62,Parkway Center City Middle College High School,508,5080,HS,High School,540 N. 13th St.,Philadelphia,PA,19123,215-400-7620,...,MODEL,30,0.3,1,30,WATCH,.,.,72,35
63,Parkway West High School,509,5090,HS,High School,4725 Fairmount Ave.,Philadelphia,PA,19139,215-400-7710,...,REINFORCE,34,0.34,1,34,WATCH,.,.,78,43
64,The Workshop School,856,8560,HS,High School,221 S. Hanson St.,Philadelphia,PA,19139,215-400-7730,...,WATCH,46,0.46,1,46,WATCH,.,.,72,50

* As a note, two schools were added into this score card spreadsheet (from the same data site but separated onto this spreadsheet) and three schools from the original Enrollment and Demographics were not featured on the list.  This all slightly edits the original list of school sites ( might not include this note ).

In [29]:
sms_penn_schools = pd.read_csv('../data/sms_penn_schools.csv')

In [30]:
sms_penn_schools.shape

(65, 337)

In [31]:
sms_penn_schools[['School', 'Grades Served', 'Retention Score', 'Grad Score']]

,School,Grades Served,Retention Score,Grad Score
0,John Bartram High School,'9-12',71,67
1,West Philadelphia High School,'9-12',74,66
2,Paul Robeson High School for Human Services,'9-12',93,95
3,William L. Sayre High School,'9-12',67,49
4,William T. Tilden School,'5-8',74,.
5,Motivation High School,'9-12',86,83
6,John Barry School,'K-8',69,.
7,William C. Bryant School,'K-8',76,.
8,Joseph W. Catharine School,'K-5',77,.
9,Benjamin B. Comegys School,'K-8',74,.
10,Sadie Alexander School,'K-8',92,.
11,Andrew Hamilton School,'K-8',80,.
12,Avery D. Harrington School,'K-8',69,.
13,Henry C. Lea School,'K-8',86,.
14,William C. Longstreth School,'K-8',71,.
15,Morton McMichael School,'K-8',80,.
16,S. Weir Mitchell School,'K-8',73,.
17,Thomas G. Morton School,'K-5',73,.
18,Samuel Powel School,'K-4',90,.
19,James Rhoads School,'K-8',74,.
20,Martha Washington School,'K-8',87,.
21,Add B. Anderson School,'K-8',78,.
22,Alain Locke School,'K-8',70,.
23,Rudolph Blankenburg School,'K-8',69,.
24,Middle Years Alternative School,'5-8',92,.
25,South Philadelphia High School,'9-12',78,53
26,Benjamin Franklin High School,'9-12',67,59
27,High School for Creative and Performing Arts,'9-12',98,95
28,Science Leadership Academy Middle School,'5-6',92,.
29,Julia R. Masterman School H.S.,'9-12',99,99
...,...,...,...,...
35,General George A. McCall School,'K-8',90,.
36,Delaplaine McDaniel School,'K-8',68,.
37,William M. Meredith School,'K-8',94,.
38,Robert Morris School,'K-8',75,.
39,Girard Academic Music Program H.S.,'9-12',98,100
40,Girard Academic Music Program M.S.,'5-8',96,.
41,Edwin M. Stanton School,'K-8',85,.
42,Albert M. Greenfield School,'K-8',94,.
43,Chester A. Arthur School,'K-8',90,.
44,Laura W. Waring School,'K-8',82,.
45,Andrew Jackson School,'K-8',91,.
46,Abram S. Jenks School,'K-5',84,.
47,Eliza B. Kirkbride School,'K-8',92,.
48,George W. Nebinger School,'K-8',91,.
49,Academy at Palumbo,'9-12',97,96
50,Southwark School,'K-8',91,.
51,Science Leadership Academy,'9-12',97,98
52,Constitution High School,'9-12',97,99
53,Vare-Washington School,'K-8',90,.
54,High School of Engineering and Science H.S.,'9-12',98,98
55,High School of Engineering and Science M.S.,'7-8',100,.
56,Strawberry Mansion High School,'9-12',54,40
57,James G. Blaine School,'K-8',77,.
58,William Dick School,'K-8',81,.
59,Edward Heston School,'K-8',68,.
60,William D. Kelley School,'K-8',75,.
61,General George G. Meade School,'K-8',84,.
62,Parkway Center City Middle College High School,'9-12',94,100
63,Parkway West High School,'9-12',83,62
64,The Workshop School,'9-12',97,93

* I once again singled out the metrics; "School" and "Grades Served" along with, "Retention Score" and "Graduation Score".  But this time only looking at 65 schools as opposed to over 300.

* As a note, to make things simpler, I will further refer to these 65 schools as "Penn" schools.

* Below are the top 10 schools of the "Penn" schools with the lowest retention rates.

In [32]:
sms_penn_schools.iloc[[56,3,26,36,59,6,12,23,22,0],[0,257]]

                            School  Retention Score
56  Strawberry Mansion High School               54
3     William L. Sayre High School               67
26   Benjamin Franklin High School               67
36      Delaplaine McDaniel School               68
59            Edward Heston School               68
6                John Barry School               69
12      Avery D. Harrington School               69
23      Rudolph Blankenburg School               69
22              Alain Locke School               70
0         John Bartram High School               71

Below are the top 10 "Penn" schools with the highest retention rates

In [33]:
sms_penn_schools.iloc[[55,29,39,54,27,30,52,51,49,40],[0,257]]

                                          School  Retention Score
55   High School of Engineering and Science M.S.              100
29                Julia R. Masterman School H.S.               99
39            Girard Academic Music Program H.S.               98
54   High School of Engineering and Science H.S.               98
27  High School for Creative and Performing Arts               98
30                 Julia R. Masterman School M.S               98
52                      Constitution High School               97
51                    Science Leadership Academy               97
49                            Academy at Palumbo               97
40            Girard Academic Music Program M.S.               96

Below are the top 10 "Penn" schools with the lowest graduation rates.

* As a note, only 18 of the schools featured a graduation rate.  Most of these schools being a high school. I still did however take this information into account.  At this point I am also flagging schools that are appearing more than once on a given list.

In [34]:
sms_penn_schools.iloc[[56,3,25,26,63,1,0,5,33],[0,290]]

                            School Grad Score
56  Strawberry Mansion High School         40
3     William L. Sayre High School         49
25  South Philadelphia High School         53
26   Benjamin Franklin High School         59
63        Parkway West High School         62
1    West Philadelphia High School         66
0         John Bartram High School         67
5           Motivation High School         83
33        Franklin Learning Center         85

* Below are the top 10 "Penn" schools with the highest graduation rates.

In [35]:
sms_penn_schools.iloc[[39,62,29,52,51,54,49,2,27],[0,290]]

                                            School Grad Score
39              Girard Academic Music Program H.S.        100
62  Parkway Center City Middle College High School        100
29                  Julia R. Masterman School H.S.         99
52                        Constitution High School         99
51                      Science Leadership Academy         98
54     High School of Engineering and Science H.S.         98
49                              Academy at Palumbo         96
2      Paul Robeson High School for Human Services         95
27    High School for Creative and Performing Arts         95

* Below are the top 10 "Penn" schools with the lowest percentage of students attending more than 95% of instructional days.

In [36]:
sms_penn_schools.iloc[[1,3,56,26,19,61,12,23,0],[0,243]]

                            School  Attendance (95%+) Score
1    West Philadelphia High School                       14
3     William L. Sayre High School                       14
56  Strawberry Mansion High School                       14
26   Benjamin Franklin High School                       17
19             James Rhoads School                       21
61  General George G. Meade School                       21
12      Avery D. Harrington School                       24
23      Rudolph Blankenburg School                       24
0         John Bartram High School                       26

* Below are the top 10 "Penn" schools with the highest percentage of students attending more than 95% of instructional days.

In [37]:
sms_penn_schools.iloc[[30,29,55,35,27,10,42,37,40,46], [0,243]]

                                          School  Attendance (95%+) Score
30                 Julia R. Masterman School M.S                       93
29                Julia R. Masterman School H.S.                       92
55   High School of Engineering and Science M.S.                       87
35               General George A. McCall School                       86
27  High School for Creative and Performing Arts                       82
10                        Sadie Alexander School                       80
42                   Albert M. Greenfield School                       80
37                    William M. Meredith School                       79
40            Girard Academic Music Program M.S.                       79
46                         Abram S. Jenks School                       77

* Below are the top 10 "Penn" schools with the lowest percentage of students attending less than 80% of instructional days.

In [38]:
sms_penn_schools.iloc[[29,30,40,10,28,35,37,42,46,47],[0,255]]

                                      School  Attendance (<80%) Score
29            Julia R. Masterman School H.S.                        0
30             Julia R. Masterman School M.S                        0
40        Girard Academic Music Program M.S.                        0
10                    Sadie Alexander School                        1
28  Science Leadership Academy Middle School                        1
35           General George A. McCall School                        1
37                William M. Meredith School                        1
42               Albert M. Greenfield School                        1
46                     Abram S. Jenks School                        1
47                 Eliza B. Kirkbride School                        1

* Below are the top 10 "Penn" schools with the highest percentage of students attending less than 80% of instructional days.

In [39]:
sms_penn_schools.iloc[[3,56,1,26,0,25,61,23,12,59],[0,255]]

                            School  Attendance (<80%) Score
3     William L. Sayre High School                       49
56  Strawberry Mansion High School                       49
1    West Philadelphia High School                       40
26   Benjamin Franklin High School                       38
0         John Bartram High School                       35
25  South Philadelphia High School                       27
61  General George G. Meade School                       24
23      Rudolph Blankenburg School                       23
12      Avery D. Harrington School                       21
59            Edward Heston School                       21

In [40]:
pd.read_csv('../data/sms_nonpenn_schools.csv')

,School,SRC School ID,ULCS Code,Report,Rpt Type Long,Street Address,City,State,Zip Code,Phone Number,...,FAFSA Tier,Student Survey College & Career Score,Student Survey College & Career Pts Earn,Student Survey College & Career Pts Poss,Student Survey College & Career Pct Earn,Student Survey College & Career Tier,Teach Effect Distinguished Score,Teach Effect Instruction Score,Teacher Attendance Score,Student Survey Teaching Score
0,John M. Patterson School,140,1400,ES,Elementary School,7000 Buist Ave.,Philadelphia,PA,19142,215-400-8190,...,.,.,.,.,.,.,.,.,49,66
1,Penrose School,144,1440,K8,K8 School,2515 S. 78th St.,Philadelphia,PA,19153,215-400-8310,...,.,.,.,.,.,.,.,.,56,47
2,Furness High School,216,2160,HS,High School,1900 S. 3rd St.,Philadelphia,PA,19148,215-400-8300,...,REINFORCE,31,0.31,1,31,WATCH,.,.,72,48
3,D. Newlin Fell School,219,2190,K8,K8 School,900 W. Oregon Ave.,Philadelphia,PA,19148,215-400-8260,...,.,.,.,.,.,.,.,.,67,59
4,F. Amedee Bregy School,224,2240,K8,K8 School,1700 Bigler St.,Philadelphia,PA,19145,215-400-8210,...,.,.,.,.,.,.,.,.,77,61
5,Francis S. Key School,254,2540,ES,Elementary School,2230 S. 8th St.,Philadelphia,PA,19148,215-400-8250,...,.,.,.,.,.,.,.,.,58,59
6,George W. Sharswood School,263,2630,K8,K8 School,2300 S. 2nd St.,Philadelphia,PA,19148,215-400-8270,...,.,.,.,.,.,.,.,.,79,62
7,The Science Leadership Academy at Beeber,268,2680,HS,High School,5925 Malvern Ave.,Philadelphia,PA,19131,215-400-7270,...,MODEL,0,0,1,0,INTERVENE,.,.,79,0
8,John H. Taggart School,269,2690,K8,K8 School,400 W. Porter St.,Philadelphia,PA,19148,215-400-8290,...,.,.,.,.,.,.,.,.,63,62
9,Overbrook High School,402,4020,HS,High School,5898 Lancaster Ave.,Philadelphia,PA,19131,215-400-7300,...,WATCH,0,0,1,0,INTERVENE,.,.,43,0
10,Murrell Dobbins Career and Technical High School,406,4060,HS,High School,2150 W. Lehigh Ave.,Philadelphia,PA,19132,215-400-7050,...,MODEL,37,0.37,1,37,WATCH,.,.,71,42
11,Lewis C. Cassidy Academics Plus School,424,4240,K8,K8 School,6523 Lansdowne Ave.,Philadelphia,PA,19151,215-400-7510,...,.,.,.,.,.,.,.,.,47,0
12,Samuel Gompers School,428,4280,K8,K8 School,5701 Wynnefield Ave.,Philadelphia,PA,19131,215-400-7250,...,.,.,.,.,.,.,.,.,72,55
13,Robert E. Lamberton School,432,4320,K8,K8 School,7501 Woodbine Ave.,Philadelphia,PA,19151,215-400-7530,...,.,.,.,.,.,.,.,.,35,0
14,E. Washington Rhodes School,435,4350,K8,K8 School,2900 W. Clearfield St.,Philadelphia,PA,19132,215-400-7060,...,.,.,.,.,.,.,.,.,55,54
15,Kenderton Elementary School,436,4360,K8,K8 School,1500 W. Ontario St.,Philadelphia,PA,19140,215-400-8340,...,.,.,.,.,.,.,.,.,49,56
16,Overbrook Elementary School,437,4370,K8,K8 School,2032 N. 62nd St.,Philadelphia,PA,19151,215-400-7520,...,.,.,.,.,.,.,.,.,58,60
17,Thomas M. Peirce School,438,4380,ES,Elementary School,2300 W. Cambria St.,Philadelphia,PA,19132,215-400-7020,...,.,.,.,.,.,.,.,.,44,61
18,Dr. Ethel Allen School,444,4440,K8,K8 School,3200 W. Lehigh Ave.,Philadelphia,PA,19132,215-400-7040,...,.,.,.,.,.,.,.,.,68,50
19,Tanner G. Duckrey School,446,4460,K8,K8 School,1501 W. Diamond St.,Philadelphia,PA,19121,215-400-7350,...,.,.,.,.,.,.,.,.,50,57
20,Richard R. Wright School,447,4470,ES,Elementary School,2201 N. 28th St.,Philadelphia,PA,19132,215-400-7030,...,.,.,.,.,.,.,.,.,64,82
21,Overbrook Educational Center,448,4480,K8,K8 School,6722 Lansdowne Ave.,Philadelphia,PA,19151,215-400-7540,...,.,.,.,.,.,.,.,.,81,53
22,Thomas A. Edison High School,502,5020,HS,High School,151 W. Luzerne St.,Philadelphia,PA,19140,215-400-3900,...,INTERVENE,31,0.31,1,31,WATCH,.,.,68,37
23,Philadelphia Military Academy,505,5050,HS,High School,2118 N. 13th St.,Philadelphia,PA,19122,215-400-7420,...,MODEL,30,0.3,1,30,WATCH,.,.,61,43
24,Jules E. Mastbaum Area Vocational Technical Hi...,506,5060,HS,High School,3116 Frankford Ave.,Philadelphia,PA,19134,215-400-7220,...,REINFORCE,31,0.31,1,31,WATCH,.,.,68,32
25,Parkway Northwest High School,507,5070,HS,High School,6200 Crittenden St.,Philadelphia,PA,19138,215-400-3390,...,MODEL,31,0.31,1,31,WATCH,.,.,67,33
26,William W. Bodine High School,515,5150,HS,High School,1101 N. 4th St.,Philadelphia,PA,19123,215-400-7630,...,MODEL,35,0.35,1,35,WATCH,.,.,75,45
27,Penn Treaty High School,516,5160,HS,High School,600 E. Thompson St.,Philadelphia,PA,19125,215-400-3800,...,MODEL,38,0.38,1,38,WATCH,.,.,59,54
28,Penn Treaty High School,516,5160,MS,Middle School,600 E. Thompson St.,Philadelphia,PA,19125,215-400-3800,...,.,.,.,.,.,.,.,.,59,48
29,Julia de Burgos School,517,5170,K8,K8 School,401 W. Lehigh Ave.,Philadelphia,PA,19133,215-400-7080,...,.,.,.,.,.,.,.,.,63,58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224,Sankofa Freedom Academy Charter School,W99,3399,K8,K8 School,2501 Kensington Ave.,Philadelphia,PA,19125,215-288-2001,...,.,.,.,.,.,.,.,.,.,50
225,Franklin Towne Charter Elementary School,X03,3403,K8,K8 School,4259 Richmond St.,Philadelphia,PA,19137,215-289-3389,...,.,.,.,.,.,.,.,.,.,65
226,Tacony Academy Charter School,X04,3404,HS,High School,1330 Rhawn St.,Philadelphia,PA,19111,215-742-5100,...,WATCH,36,0.36,1,36,WATCH,.,.,.,41
227,Tacony Academy Charter School,X04,3404,K8,K8 School,1330 Rhawn St.,Philadelphia,PA,19111,215-742-5100,...,.,.,.,.,.,.,.,.,.,63
228,Aspira Charter School at Stetson,X06,3406,MS,Middle School,3200 B. St.,Philadelphia,PA,19134,215-291-4720,...,.,.,.,.,.,.,.,.,.,54
229,Mastery Charter School at Harrity,X07,3407,K8,K8 School,5601 Christian St.,Philadelphia,PA,19143,215-471-2908,...,.,.,.,.,.,.,.,.,.,0
230,Mastery Charter School at Mann,X08,3408,ES,Elementary School,5376 W. Berks St.,Philadelphia,PA,19131,215-581-5616,...,.,.,.,.,.,.,.,.,.,0
231,Mastery Charter School at Smedley,X09,3409,ES,Elementary School,1790 Bridge St.,Philadelphia,PA,19124,215-537-2523,...,.,.,.,.,.,.,.,.,.,0
232,Universal Charter School at Bluford,X10,3410,ES,Elementary School,5801 Media St.,Philadelphia,PA,19131,215-581-5502,...,.,.,.,.,.,.,.,.,.,0
233,Universal Charter School at Daroff,X11,3411,K8,K8 School,5630 Vine St.,Philadelphia,PA,19139,215-471-2905,...,.,.,.,.,.,.,.,.,.,0
234,Mastery Charter School at Douglass,X12,3412,K8,K8 School,2118 W. Norris St.,Philadelphia,PA,19121,215-684-5063,...,.,.,.,.,.,.,.,.,.,0
235,Aspira Charter School at Olney,X14,3414,HS,High School,100 W. Duncannon Ave.,Philadelphia,PA,19120,215-456-3014,...,WATCH,40,0.4,1,40,WATCH,.,.,.,48
236,Mastery Charter School at Clymer,X15,3415,ES,Elementary School,1201 W. Rush St.,Philadelphia,PA,19133,215-223-2243,...,.,.,.,.,.,.,.,.,.,0
237,Mastery Charter School at Gratz,X16,3416,HS,High School,1798 W. Hunting Park Ave.,Philadelphia,PA,19140,215-227-4408,...,MODEL,0,0,1,0,INTERVENE,.,.,.,0
238,Mastery Charter School at Gratz,X16,3416,MS,Middle School,1798 W. Hunting Park Ave.,Philadelphia,PA,19140,215-227-4408,...,.,.,.,.,.,.,.,.,.,0
239,Universal Charter School at Audenried,X17,3417,HS,High School,3301 Tasker St.,Philadelphia,PA,19145,215-952-4801,...,WATCH,0,0,1,0,INTERVENE,.,.,.,0
240,Universal Charter School at Vare,X18,3418,MS,Middle School,2100 S. 24th St.,Philadelphia,PA,19145,215-952-8611,...,.,.,.,.,.,.,.,.,.,48
241,Lindley Academy Charter at Birney,X19,3419,K8,K8 School,900 Lindley Ave.,Philadelphia,PA,19141,215-456-3000,...,.,.,.,.,.,.,.,.,.,53
242,Mastery Charter School at Cleveland,X20,3420,K8,K8 School,3701 N. 19th St.,Philadelphia,PA,19140,215-227-5042,...,.,.,.,.,.,.,.,.,.,0
243,Universal Charter School at Creighton,X21,3421,K8,K8 School,5401 Tabor Ave.,Philadelphia,PA,19120,215-537-2531,...,.,.,.,.,.,.,.,.,.,54
244,The Philadelphia Charter School for Arts and S...,X22,3422,K8,K8 School,1197 Haworth St.,Philadelphia,PA,19124,215-537-2520,...,.,.,.,.,.,.,.,.,.,55
245,Memphis Street Academy Charter School at J.P. ...,X23,3423,MS,Middle School,2950 Memphis St.,Philadelphia,PA,19134,215-291-4709,...,.,.,.,.,.,.,.,.,.,53
246,Universal Charter School at Alcorn,X24,3424,K8,K8 School,3200 Dickinson St.,Philadelphia,PA,19146,215-952-6219,...,.,.,.,.,.,.,.,.,.,81
247,Mastery Charter School at Pastorius,X26,3426,K8,K8 School,5650 Sprague St.,Philadelphia,PA,19138,215-951-5689,...,.,.,.,.,.,.,.,.,.,0
248,Mastery Charter School at Wister,X27,3427,ES,Elementary School,67 E. Bringhurst St.,Philadelphia,PA,19144,215-951-4003,...,.,.,.,.,.,.,.,.,.,0
249,Global Leadership Academy at Huey,X28,3428,K8,K8 School,5200 Pine St.,Philadelphia,PA,19143,215-471-2978,...,.,.,.,.,.,.,.,.,.,0
250,MaST Community Charter School II,X40,3440,ES,Elementary School,6238 Rising Sun Ave.,Philadelphia,PA,19111,215-398-7960,...,.,.,.,.,.,.,.,.,.,68
251,TECH Freire Charter School,X41,3441,HS,High School,2221 N. Broad St.,Philadelphia,PA,19132,267-507-1111,...,.,35,0.35,1,35,WATCH,.,.,.,42
252,Independence Charter School West,X42,3442,ES,Elementary School,5600 Chester Ave.,Philadelphia,PA,19143,215-724-5600,...,.,.,.,.,.,.,.,.,.,0
253,KIPP West Philadelphia Charter School,X43,3443,ES,Elementary School,5070 Parkside Ave.,Philadelphia,PA,19131,267-787-5700,...,.,.,.,.,.,.,.,.,.,.

* This file contains the remainder of the schools in the Philadelphia district that were not classified as a "Penn" school, otherwise known as not being within the three mile radius of campus.

In [41]:
sms_nonpenn_schools = pd.read_csv('../data/sms_nonpenn_schools.csv')

In [42]:
sms_nonpenn_schools.shape

(254, 337)

In [43]:
sms_nonpenn_schools[['School','Grades Served','Retention Score', 'Grad Score']]

,School,Grades Served,Retention Score,Grad Score
0,John M. Patterson School,'K-4',79,.
1,Penrose School,'K-8',84,.
2,Furness High School,'9-12',86,76
3,D. Newlin Fell School,'K-8',86,.
4,F. Amedee Bregy School,'K-8',86,.
5,Francis S. Key School,'K-6',91,.
6,George W. Sharswood School,'K-8',88,.
7,The Science Leadership Academy at Beeber,'9-12',96,96
8,John H. Taggart School,'K-8',91,.
9,Overbrook High School,'9-12',64,50
10,Murrell Dobbins Career and Technical High School,'9-12',83,88
11,Lewis C. Cassidy Academics Plus School,'K-8',72,.
12,Samuel Gompers School,'K-8',82,.
13,Robert E. Lamberton School,'K-8',75,.
14,E. Washington Rhodes School,'K-8',75,.
15,Kenderton Elementary School,'K-8',74,.
16,Overbrook Elementary School,'K-8',81,.
17,Thomas M. Peirce School,'K-6',69,.
18,Dr. Ethel Allen School,'K-8',74,.
19,Tanner G. Duckrey School,'K-8',74,.
20,Richard R. Wright School,'K-5',77,.
21,Overbrook Educational Center,'K-8',96,.
22,Thomas A. Edison High School,'9-12',69,56
23,Philadelphia Military Academy,'9-12',89,91
24,Jules E. Mastbaum Area Vocational Technical Hi...,'9-12',84,91
25,Parkway Northwest High School,'9-12',89,81
26,William W. Bodine High School,'9-12',95,95
27,Penn Treaty High School,'9-12',83,72
28,Penn Treaty High School,'6-8',89,.
29,Julia de Burgos School,'K-8',87,.
...,...,...,...,...
224,Sankofa Freedom Academy Charter School,'K-8',91,.
225,Franklin Towne Charter Elementary School,'K-8',98,.
226,Tacony Academy Charter School,'9-12',95,96
227,Tacony Academy Charter School,'K-8',96,.
228,Aspira Charter School at Stetson,'5-8',92,.
229,Mastery Charter School at Harrity,'K-8',89,.
230,Mastery Charter School at Mann,'K-6',94,.
231,Mastery Charter School at Smedley,'K-6',92,.
232,Universal Charter School at Bluford,'K-6',89,.
233,Universal Charter School at Daroff,'K-8',85,.
234,Mastery Charter School at Douglass,'K-8',79,.
235,Aspira Charter School at Olney,'9-12',78,71
236,Mastery Charter School at Clymer,'K-6',89,.
237,Mastery Charter School at Gratz,'9-12',77,62
238,Mastery Charter School at Gratz,'7-8',92,.
239,Universal Charter School at Audenried,'9-12',76,69
240,Universal Charter School at Vare,'5-8',87,.
241,Lindley Academy Charter at Birney,'K-8',92,.
242,Mastery Charter School at Cleveland,'K-8',87,.
243,Universal Charter School at Creighton,'K-8',91,.
244,The Philadelphia Charter School for Arts and S...,'K-8',91,.
245,Memphis Street Academy Charter School at J.P. ...,'5-8',83,.
246,Universal Charter School at Alcorn,'K-8',82,.
247,Mastery Charter School at Pastorius,'K-8',92,.
248,Mastery Charter School at Wister,'K-5',87,.
249,Global Leadership Academy at Huey,'K-8',91,.
250,MaST Community Charter School II,'K-4',96,.
251,TECH Freire Charter School,'9-11',72,.
252,Independence Charter School West,'K-4',93,.
253,KIPP West Philadelphia Charter School,'K-1',94,.

* Once again, I start my exploration by singling out the "School" and the "Grades Served" along with, "Retention Score", and "Graduation Score".  There are 254 schools in this set so it is a bit more to look over and analyze.

* Below, are the top 10 schools of these "Non Penn" schools that have the lowest retention rate of students.

In [44]:
sms_nonpenn_schools.iloc[[79,9,65,188,17,22,56,75,11,78],[0,257]]

                                     School  Retention Score
79                Theodore Roosevelt School               58
9                     Overbrook High School               64
65           Martin Luther King High School               65
188                  Khepera Charter School               67
17                  Thomas M. Peirce School               69
22             Thomas A. Edison High School               69
56                              Building 21               70
75                 John F. McCloskey School               71
11   Lewis C. Cassidy Academics Plus School               72
78                Samuel Pennypacker School               72

* Below, are the top 10 of the "Non Penn" schools that have the highest retention rate of students.

In [45]:
sms_nonpenn_schools.iloc[[61,172,154,173,208,211,225,88,124,167],[0,257]]

                                                School  Retention Score
61                                 Central High School               99
172  Mathematics, Science, and Technology Community...               99
154             Eugenio Maria De Hostos Charter School               98
173  Mathematics, Science, and Technology Community...               98
208        Folk Arts-Cultural Treasures Charter School               98
211                   Northwood Academy Charter School               98
225           Franklin Towne Charter Elementary School               98
88           Academy for the Middle Years at Northwest               97
124                      Arts Academy at Benjamin Rush               97
167                Philadelphia Academy Charter School               94

* Below are the top 10 of the "Non Penn" schools that have the lowest graduation rate of students.

* Similarly with the last data set, not every school had an entry for their graduation rate- only 62 schools had a score.  But I once again took all of these available scores into account.

In [46]:
sms_nonpenn_schools.iloc[[65,9,90,22,237,60,93,239,53,27],[0,290]]

                                    School Grad Score
65          Martin Luther King High School         48
9                    Overbrook High School         50
90                   Frankford High School         55
22            Thomas A. Edison High School         56
237        Mastery Charter School at Gratz         62
60                  Kensington High School         63
93                 Samuel Fels High School         69
239  Universal Charter School at Audenried         69
53      Kensington Health Sciences Academy         71
27                 Penn Treaty High School         72

* Below are the top 10 of the "Non Penn" schools that have the highest graduation rate of students.

In [47]:
sms_nonpenn_schools.iloc[[89,61,124,64,172,226,7,158,26,63],[0,290]]

                                                School Grad Score
89                                Lankenau High School        100
61                                 Central High School        100
124                      Arts Academy at Benjamin Rush         99
64                  Philadelphia High School for Girls         97
172  Mathematics, Science, and Technology Community...         97
226                      Tacony Academy Charter School         96
7             The Science Leadership Academy at Beeber         96
158               Multicultural Academy Charter School         95
26                       William W. Bodine High School         95
63                          Walter B. Saul High School         94

* Below are the top 10 of the "Non Penn" schools that have the highest percentage of students attending more than 95% of instructional days

In [48]:
sms_nonpenn_schools.iloc[[190,219,193,23,188,226,218,227,153,236],[0,243]]

,School,Attendance (95%+) Score
190,Philadelphia Electrical and Technology Charter...,17
219,Antonia Pantoja Charter School,59
193,Mastery Charter School at Lenfest,43
23,Philadelphia Military Academy,40
188,Khepera Charter School,83
226,Tacony Academy Charter School,26
218,Pan American Academy Charter School,60
227,Tacony Academy Charter School,55
153,Christopher Columbus Charter School,77
236,Mastery Charter School at Clymer,35

* As I was calculating the data for attendance, I found there to be an error in the spreadsheet I was working with.  I then went back and re-formated the file and re-uploaded it.  Because I am unsure how far back the error impacted my data, I decided to re-run all of the charts for this dataset that I already computed.

In [49]:
pd.read_csv('../data/updated_sms_nonpenn_schools.csv')

,School,SRC School ID,ULCS Code,Report,Rpt Type Long,Street Address,City,State,Zip Code,Phone Number,...,FAFSA Tier,Student Survey College & Career Score,Student Survey College & Career Pts Earn,Student Survey College & Career Pts Poss,Student Survey College & Career Pct Earn,Student Survey College & Career Tier,Teach Effect Distinguished Score,Teach Effect Instruction Score,Teacher Attendance Score,Student Survey Teaching Score
0,John M. Patterson School,140,1400,ES,Elementary School,7000 Buist Ave.,Philadelphia,PA,19142,215-400-8190,...,.,.,.,.,.,.,.,.,49,66
1,Furness High School,216,2160,HS,High School,1900 S. 3rd St.,Philadelphia,PA,19148,215-400-8300,...,REINFORCE,31,0.31,1,31,WATCH,.,.,72,48
2,D. Newlin Fell School,219,2190,K8,K8 School,900 W. Oregon Ave.,Philadelphia,PA,19148,215-400-8260,...,.,.,.,.,.,.,.,.,67,59
3,F. Amedee Bregy School,224,2240,K8,K8 School,1700 Bigler St.,Philadelphia,PA,19145,215-400-8210,...,.,.,.,.,.,.,.,.,77,61
4,Francis S. Key School,254,2540,ES,Elementary School,2230 S. 8th St.,Philadelphia,PA,19148,215-400-8250,...,.,.,.,.,.,.,.,.,58,59
5,George W. Sharswood School,263,2630,K8,K8 School,2300 S. 2nd St.,Philadelphia,PA,19148,215-400-8270,...,.,.,.,.,.,.,.,.,79,62
6,The Science Leadership Academy at Beeber,268,2680,HS,High School,5925 Malvern Ave.,Philadelphia,PA,19131,215-400-7270,...,MODEL,0,0,1,0,INTERVENE,.,.,79,0
7,John H. Taggart School,269,2690,K8,K8 School,400 W. Porter St.,Philadelphia,PA,19148,215-400-8290,...,.,.,.,.,.,.,.,.,63,62
8,Overbrook High School,402,4020,HS,High School,5898 Lancaster Ave.,Philadelphia,PA,19131,215-400-7300,...,WATCH,0,0,1,0,INTERVENE,.,.,43,0
9,Murrell Dobbins Career and Technical High School,406,4060,HS,High School,2150 W. Lehigh Ave.,Philadelphia,PA,19132,215-400-7050,...,MODEL,37,0.37,1,37,WATCH,.,.,71,42
10,Lewis C. Cassidy Academics Plus School,424,4240,K8,K8 School,6523 Lansdowne Ave.,Philadelphia,PA,19151,215-400-7510,...,.,.,.,.,.,.,.,.,47,0
11,Samuel Gompers School,428,4280,K8,K8 School,5701 Wynnefield Ave.,Philadelphia,PA,19131,215-400-7250,...,.,.,.,.,.,.,.,.,72,55
12,Robert E. Lamberton School,432,4320,K8,K8 School,7501 Woodbine Ave.,Philadelphia,PA,19151,215-400-7530,...,.,.,.,.,.,.,.,.,35,0
13,E. Washington Rhodes School,435,4350,K8,K8 School,2900 W. Clearfield St.,Philadelphia,PA,19132,215-400-7060,...,.,.,.,.,.,.,.,.,55,54
14,Kenderton Elementary School,436,4360,K8,K8 School,1500 W. Ontario St.,Philadelphia,PA,19140,215-400-8340,...,.,.,.,.,.,.,.,.,49,56
15,Overbrook Elementary School,437,4370,K8,K8 School,2032 N. 62nd St.,Philadelphia,PA,19151,215-400-7520,...,.,.,.,.,.,.,.,.,58,60
16,Thomas M. Peirce School,438,4380,ES,Elementary School,2300 W. Cambria St.,Philadelphia,PA,19132,215-400-7020,...,.,.,.,.,.,.,.,.,44,61
17,Dr. Ethel Allen School,444,4440,K8,K8 School,3200 W. Lehigh Ave.,Philadelphia,PA,19132,215-400-7040,...,.,.,.,.,.,.,.,.,68,50
18,Tanner G. Duckrey School,446,4460,K8,K8 School,1501 W. Diamond St.,Philadelphia,PA,19121,215-400-7350,...,.,.,.,.,.,.,.,.,50,57
19,Overbrook Educational Center,448,4480,K8,K8 School,6722 Lansdowne Ave.,Philadelphia,PA,19151,215-400-7540,...,.,.,.,.,.,.,.,.,81,53
20,General George G. Meade School,457,4570,K8,K8 School,1600 N. 18th St.,Philadelphia,PA,19121,215-400-7310,...,.,.,.,.,.,.,.,.,69,61
21,Thomas A. Edison High School,502,5020,HS,High School,151 W. Luzerne St.,Philadelphia,PA,19140,215-400-3900,...,INTERVENE,31,0.31,1,31,WATCH,.,.,68,37
22,Philadelphia Military Academy,505,5050,HS,High School,2118 N. 13th St.,Philadelphia,PA,19122,215-400-7420,...,MODEL,30,0.3,1,30,WATCH,.,.,61,43
23,Jules E. Mastbaum Area Vocational Technical Hi...,506,5060,HS,High School,3116 Frankford Ave.,Philadelphia,PA,19134,215-400-7220,...,REINFORCE,31,0.31,1,31,WATCH,.,.,68,32
24,Parkway Northwest High School,507,5070,HS,High School,6200 Crittenden St.,Philadelphia,PA,19138,215-400-3390,...,MODEL,31,0.31,1,31,WATCH,.,.,67,33
25,William W. Bodine High School,515,5150,HS,High School,1101 N. 4th St.,Philadelphia,PA,19123,215-400-7630,...,MODEL,35,0.35,1,35,WATCH,.,.,75,45
26,Penn Treaty High School,516,5160,HS,High School,600 E. Thompson St.,Philadelphia,PA,19125,215-400-3800,...,MODEL,38,0.38,1,38,WATCH,.,.,59,54
27,Penn Treaty High School,516,5160,MS,Middle School,600 E. Thompson St.,Philadelphia,PA,19125,215-400-3800,...,.,.,.,.,.,.,.,.,59,48
28,Julia de Burgos School,517,5170,K8,K8 School,401 W. Lehigh Ave.,Philadelphia,PA,19133,215-400-7080,...,.,.,.,.,.,.,.,.,63,58
29,Alexander Adaire School,520,5200,K8,K8 School,1300 E. Palmer St.,Philadelphia,PA,19125,215-400-7480,...,.,.,.,.,.,.,.,.,96,53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224,Sankofa Freedom Academy Charter School,W99,3399,K8,K8 School,2501 Kensington Ave.,Philadelphia,PA,19125,215-288-2001,...,.,.,.,.,.,.,.,.,.,50
225,Franklin Towne Charter Elementary School,X03,3403,K8,K8 School,4259 Richmond St.,Philadelphia,PA,19137,215-289-3389,...,.,.,.,.,.,.,.,.,.,65
226,Tacony Academy Charter School,X04,3404,HS,High School,1330 Rhawn St.,Philadelphia,PA,19111,215-742-5100,...,WATCH,36,0.36,1,36,WATCH,.,.,.,41
227,Tacony Academy Charter School,X04,3404,K8,K8 School,1330 Rhawn St.,Philadelphia,PA,19111,215-742-5100,...,.,.,.,.,.,.,.,.,.,63
228,Aspira Charter School at Stetson,X06,3406,MS,Middle School,3200 B. St.,Philadelphia,PA,19134,215-291-4720,...,.,.,.,.,.,.,.,.,.,54
229,Mastery Charter School at Harrity,X07,3407,K8,K8 School,5601 Christian St.,Philadelphia,PA,19143,215-471-2908,...,.,.,.,.,.,.,.,.,.,0
230,Mastery Charter School at Mann,X08,3408,ES,Elementary School,5376 W. Berks St.,Philadelphia,PA,19131,215-581-5616,...,.,.,.,.,.,.,.,.,.,0
231,Mastery Charter School at Smedley,X09,3409,ES,Elementary School,1790 Bridge St.,Philadelphia,PA,19124,215-537-2523,...,.,.,.,.,.,.,.,.,.,0
232,Universal Charter School at Bluford,X10,3410,ES,Elementary School,5801 Media St.,Philadelphia,PA,19131,215-581-5502,...,.,.,.,.,.,.,.,.,.,0
233,Universal Charter School at Daroff,X11,3411,K8,K8 School,5630 Vine St.,Philadelphia,PA,19139,215-471-2905,...,.,.,.,.,.,.,.,.,.,0
234,Mastery Charter School at Douglass,X12,3412,K8,K8 School,2118 W. Norris St.,Philadelphia,PA,19121,215-684-5063,...,.,.,.,.,.,.,.,.,.,0
235,Aspira Charter School at Olney,X14,3414,HS,High School,100 W. Duncannon Ave.,Philadelphia,PA,19120,215-456-3014,...,WATCH,40,0.4,1,40,WATCH,.,.,.,48
236,Mastery Charter School at Clymer,X15,3415,ES,Elementary School,1201 W. Rush St.,Philadelphia,PA,19133,215-223-2243,...,.,.,.,.,.,.,.,.,.,0
237,Mastery Charter School at Gratz,X16,3416,HS,High School,1798 W. Hunting Park Ave.,Philadelphia,PA,19140,215-227-4408,...,MODEL,0,0,1,0,INTERVENE,.,.,.,0
238,Mastery Charter School at Gratz,X16,3416,MS,Middle School,1798 W. Hunting Park Ave.,Philadelphia,PA,19140,215-227-4408,...,.,.,.,.,.,.,.,.,.,0
239,Universal Charter School at Audenried,X17,3417,HS,High School,3301 Tasker St.,Philadelphia,PA,19145,215-952-4801,...,WATCH,0,0,1,0,INTERVENE,.,.,.,0
240,Universal Charter School at Vare,X18,3418,MS,Middle School,2100 S. 24th St.,Philadelphia,PA,19145,215-952-8611,...,.,.,.,.,.,.,.,.,.,48
241,Lindley Academy Charter at Birney,X19,3419,K8,K8 School,900 Lindley Ave.,Philadelphia,PA,19141,215-456-3000,...,.,.,.,.,.,.,.,.,.,53
242,Mastery Charter School at Cleveland,X20,3420,K8,K8 School,3701 N. 19th St.,Philadelphia,PA,19140,215-227-5042,...,.,.,.,.,.,.,.,.,.,0
243,Universal Charter School at Creighton,X21,3421,K8,K8 School,5401 Tabor Ave.,Philadelphia,PA,19120,215-537-2531,...,.,.,.,.,.,.,.,.,.,54
244,The Philadelphia Charter School for Arts and S...,X22,3422,K8,K8 School,1197 Haworth St.,Philadelphia,PA,19124,215-537-2520,...,.,.,.,.,.,.,.,.,.,55
245,Memphis Street Academy Charter School at J.P. ...,X23,3423,MS,Middle School,2950 Memphis St.,Philadelphia,PA,19134,215-291-4709,...,.,.,.,.,.,.,.,.,.,53
246,Universal Charter School at Alcorn,X24,3424,K8,K8 School,3200 Dickinson St.,Philadelphia,PA,19146,215-952-6219,...,.,.,.,.,.,.,.,.,.,81
247,Mastery Charter School at Pastorius,X26,3426,K8,K8 School,5650 Sprague St.,Philadelphia,PA,19138,215-951-5689,...,.,.,.,.,.,.,.,.,.,0
248,Mastery Charter School at Wister,X27,3427,ES,Elementary School,67 E. Bringhurst St.,Philadelphia,PA,19144,215-951-4003,...,.,.,.,.,.,.,.,.,.,0
249,Global Leadership Academy at Huey,X28,3428,K8,K8 School,5200 Pine St.,Philadelphia,PA,19143,215-471-2978,...,.,.,.,.,.,.,.,.,.,0
250,MaST Community Charter School II,X40,3440,ES,Elementary School,6238 Rising Sun Ave.,Philadelphia,PA,19111,215-398-7960,...,.,.,.,.,.,.,.,.,.,68
251,TECH Freire Charter School,X41,3441,HS,High School,2221 N. Broad St.,Philadelphia,PA,19132,267-507-1111,...,.,35,0.35,1,35,WATCH,.,.,.,42
252,Independence Charter School West,X42,3442,ES,Elementary School,5600 Chester Ave.,Philadelphia,PA,19143,215-724-5600,...,.,.,.,.,.,.,.,.,.,0
253,KIPP West Philadelphia Charter School,X43,3443,ES,Elementary School,5070 Parkside Ave.,Philadelphia,PA,19131,267-787-5700,...,.,.,.,.,.,.,.,.,.,.

* This is the new updated "Non Penn Schools" file.

In [50]:
upd_sms_nonpenn_schools = pd.read_csv('../data/updated_sms_nonpenn_schools.csv')

In [51]:
upd_sms_nonpenn_schools.shape

(254, 337)

In [52]:
upd_sms_nonpenn_schools[['School', 'Grades Served', 'Retention Score', 'Grad Score']]

,School,Grades Served,Retention Score,Grad Score
0,John M. Patterson School,'K-4',79,.
1,Furness High School,'9-12',86,76
2,D. Newlin Fell School,'K-8',86,.
3,F. Amedee Bregy School,'K-8',86,.
4,Francis S. Key School,'K-6',91,.
5,George W. Sharswood School,'K-8',88,.
6,The Science Leadership Academy at Beeber,'9-12',96,96
7,John H. Taggart School,'K-8',91,.
8,Overbrook High School,'9-12',64,50
9,Murrell Dobbins Career and Technical High School,'9-12',83,88
10,Lewis C. Cassidy Academics Plus School,'K-8',72,.
11,Samuel Gompers School,'K-8',82,.
12,Robert E. Lamberton School,'K-8',75,.
13,E. Washington Rhodes School,'K-8',75,.
14,Kenderton Elementary School,'K-8',74,.
15,Overbrook Elementary School,'K-8',81,.
16,Thomas M. Peirce School,'K-6',69,.
17,Dr. Ethel Allen School,'K-8',74,.
18,Tanner G. Duckrey School,'K-8',74,.
19,Overbrook Educational Center,'K-8',96,.
20,General George G. Meade School,'K-8',84,.
21,Thomas A. Edison High School,'9-12',69,56
22,Philadelphia Military Academy,'9-12',89,91
23,Jules E. Mastbaum Area Vocational Technical Hi...,'9-12',84,91
24,Parkway Northwest High School,'9-12',89,81
25,William W. Bodine High School,'9-12',95,95
26,Penn Treaty High School,'9-12',83,72
27,Penn Treaty High School,'6-8',89,.
28,Julia de Burgos School,'K-8',87,.
29,Alexander Adaire School,'K-8',94,.
...,...,...,...,...
224,Sankofa Freedom Academy Charter School,'K-8',91,.
225,Franklin Towne Charter Elementary School,'K-8',98,.
226,Tacony Academy Charter School,'9-12',95,96
227,Tacony Academy Charter School,'K-8',96,.
228,Aspira Charter School at Stetson,'5-8',92,.
229,Mastery Charter School at Harrity,'K-8',89,.
230,Mastery Charter School at Mann,'K-6',94,.
231,Mastery Charter School at Smedley,'K-6',92,.
232,Universal Charter School at Bluford,'K-6',89,.
233,Universal Charter School at Daroff,'K-8',85,.
234,Mastery Charter School at Douglass,'K-8',79,.
235,Aspira Charter School at Olney,'9-12',78,71
236,Mastery Charter School at Clymer,'K-6',89,.
237,Mastery Charter School at Gratz,'9-12',77,62
238,Mastery Charter School at Gratz,'7-8',92,.
239,Universal Charter School at Audenried,'9-12',76,69
240,Universal Charter School at Vare,'5-8',87,.
241,Lindley Academy Charter at Birney,'K-8',92,.
242,Mastery Charter School at Cleveland,'K-8',87,.
243,Universal Charter School at Creighton,'K-8',91,.
244,The Philadelphia Charter School for Arts and S...,'K-8',91,.
245,Memphis Street Academy Charter School at J.P. ...,'5-8',83,.
246,Universal Charter School at Alcorn,'K-8',82,.
247,Mastery Charter School at Pastorius,'K-8',92,.
248,Mastery Charter School at Wister,'K-5',87,.
249,Global Leadership Academy at Huey,'K-8',91,.
250,MaST Community Charter School II,'K-4',96,.
251,TECH Freire Charter School,'9-11',72,.
252,Independence Charter School West,'K-4',93,.
253,KIPP West Philadelphia Charter School,'K-1',94,.

* Below are the top 10 "Non Penn" schools with the lowest retention rates

In [53]:
upd_sms_nonpenn_schools.iloc[[78,8,64,188,16,21,55,74,10,77],[0,257]]

                                     School  Retention Score
78                Theodore Roosevelt School               58
8                     Overbrook High School               64
64           Martin Luther King High School               65
188                  Khepera Charter School               67
16                  Thomas M. Peirce School               69
21             Thomas A. Edison High School               69
55                              Building 21               70
74                 John F. McCloskey School               71
10   Lewis C. Cassidy Academics Plus School               72
77                Samuel Pennypacker School               72

* Below are the top 10 "Non Penn" schools with the highest retention rates

In [54]:
upd_sms_nonpenn_schools.iloc[[60,172,154,173,208,211,225,87,123,168],[0,257]]

                                                School  Retention Score
60                                 Central High School               99
172  Mathematics, Science, and Technology Community...               99
154             Eugenio Maria De Hostos Charter School               98
173  Mathematics, Science, and Technology Community...               98
208        Folk Arts-Cultural Treasures Charter School               98
211                   Northwood Academy Charter School               98
225           Franklin Towne Charter Elementary School               98
87           Academy for the Middle Years at Northwest               97
123                      Arts Academy at Benjamin Rush               97
168                Philadelphia Academy Charter School               97

* Below are the top 10 "Non Penn" schools with the lowest graduation rates.  
Once again, there were only 62 schools that provided a graduation rate.

In [55]:
upd_sms_nonpenn_schools.iloc[[64,8,89,237,59,92,239,52,235],[0,290]]

                                    School Grad Score
64          Martin Luther King High School         48
8                    Overbrook High School         50
89                   Frankford High School         55
237        Mastery Charter School at Gratz         62
59                  Kensington High School         63
92                 Samuel Fels High School         69
239  Universal Charter School at Audenried         69
52      Kensington Health Sciences Academy         71
235         Aspira Charter School at Olney         71

* Below are the top 10 "Non Penn" schools with the highest graduation rate.

In [56]:
upd_sms_nonpenn_schools.iloc[[88,60,123,172,63,226,6,158,25,62],[0,290]]

                                                School Grad Score
88                                Lankenau High School        100
60                                 Central High School        100
123                      Arts Academy at Benjamin Rush         99
172  Mathematics, Science, and Technology Community...         97
63                  Philadelphia High School for Girls         97
226                      Tacony Academy Charter School         96
6             The Science Leadership Academy at Beeber         96
158               Multicultural Academy Charter School         95
25                       William W. Bodine High School         95
62                          Walter B. Saul High School         94

* Below are the top 10 "Non Penn" schools with the lowest percentage of students attending more then 95% of instructional days.

In [57]:
upd_sms_nonpenn_schools.iloc[[235,8,64,239,190,193,21,18,20,89],[0,243]]

,School,Attendance (95%+) Score
235,Aspira Charter School at Olney,7
8,Overbrook High School,16
64,Martin Luther King High School,16
239,Universal Charter School at Audenried,16
190,Philadelphia Electrical and Technology Charter...,17
193,Mastery Charter School at Lenfest,43
21,Thomas A. Edison High School,19
18,Tanner G. Duckrey School,21
20,General George G. Meade School,21
89,Frankford High School,21

* Below are the top 10 "Non Penn" schools with the highest percentage of students attending more than 95% of instructional days.

In [58]:
upd_sms_nonpenn_schools.iloc[[56,198,60,208,188,204,84,146,99,153],[0,243]]

                                          School  Attendance (95%+) Score
56                                  The U School                       95
198                   Green Woods Charter School                       88
60                           Central High School                       85
208  Folk Arts-Cultural Treasures Charter School                       83
188                       Khepera Charter School                       83
204       Philadelphia Montessori Charter School                       82
84                   Hill-Freedman World Academy                       69
146                      Joseph Greenberg School                       80
99                      Benjamin Franklin School                       80
153          Christopher Columbus Charter School                       77

* Below are the top 10 "Non Penn" schools with the lowest percentage of students attending less than 80% of instructional days.

In [59]:
upd_sms_nonpenn_schools.iloc[[29,146,172,173,205,225,6,56,60,87],[0,255]]

,School,Attendance (<80%) Score
29,Alexander Adaire School,0
146,Joseph Greenberg School,0
172,"Mathematics, Science, and Technology Community...",0
173,"Mathematics, Science, and Technology Community...",0
205,Ad Prima Charter School,0
225,Franklin Towne Charter Elementary School,0
6,The Science Leadership Academy at Beeber,1
56,The U School,1
60,Central High School,1
87,Academy for the Middle Years at Northwest,1

* Below are the top 10 "Non Penn" schools with the highest percentage of students attending less than 80% of instructional days.

In [60]:
upd_sms_nonpenn_schools.iloc[[8,235,64,239,59,21,89,52,92,80],[0,255]]

                                    School  Attendance (<80%) Score
8                    Overbrook High School                       48
235         Aspira Charter School at Olney                       44
64          Martin Luther King High School                       41
239  Universal Charter School at Audenried                       37
59                  Kensington High School                       37
21            Thomas A. Edison High School                       36
89                   Frankford High School                       34
52      Kensington Health Sciences Academy                       26
92                 Samuel Fels High School                       24
80                  Edward T. Steel School                       24