### Setup

In [1]:
%matplotlib inline

import warnings
warnings.simplefilter('ignore')

import pandas as pd
import matplotlib.pyplot as plt

### Load Data

In [2]:
# Load in year data sets
gei_2005_df = pd.read_csv('../data/GEI_2005.csv')
gei_2010_df = pd.read_csv('../data/GEI_2010.csv')
gei_2012_df = pd.read_csv('../data/GEI_2012.csv')
gei_2015_df = pd.read_csv('../data/GEI_2015.csv')

# Truncate data frames to get rid of blank (NaN) cells
gei_2005_df = gei_2005_df.iloc[:29]
gei_2010_df = gei_2010_df.iloc[:29]
gei_2012_df = gei_2012_df.iloc[:29]
gei_2015_df = gei_2015_df.iloc[:29]

In [3]:
# Load in additional country information
con_info_df = pd.read_csv('../data/Country_Info.csv')

### Inspect Data

In [4]:
gei_2005_df.head(5)

,Country,Gender Equality Index,WORK,Participation,Segregation and quality of work,MONEY,Financial resources,Economic situation,KNOWLEDGE,Attainment and participation,...,Population without unmet needs for medical examination (%) T,Population without unmet needs for dental examination (%) W,Population without unmet needs for dental examination (%) M,Population without unmet needs for dental examination (%) T,Population (number) W,Population (number) M,Population (number) T,Population (%) W,Population (%) M,Population (%) T
0,EU-28,62.0,70.0,77.5,63.3,73.9,60.9,89.7,60.8,67.0,...,91.2,89.8,89.9,89.8,"205,473,251","190,389,112","395,862,363",51.9%,48.1%,100.0%
1,BE,66.0,71.0,72.3,69.8,81.3,73.9,89.5,68.1,70.7,...,99.0,97.0,97.4,97.2,"4,275,415","4,003,552","8,278,967",51.6%,48.4%,100.0%
2,BG,56.0,67.3,77.9,58.1,54.3,33.5,88.1,52.5,53.0,...,74.9,71.4,73.6,72.5,"3,282,615","3,044,971","6,327,586",51.9%,48.1%,100.0%
3,CZ,53.6,65.3,79.6,53.6,70.2,50.6,97.4,52.2,52.0,...,92.8,95.2,94.2,94.8,"4,299,258","3,995,629","8,294,887",51.8%,48.2%,100.0%
4,DK,74.6,78.9,88.5,70.3,82.7,71.2,96.1,73.7,81.1,...,98.8,94.8,93.9,94.4,"2,147,248","2,059,915","4,207,162",51.0%,49.0%,100.0%

In [5]:
gei_2010_df.head(5)

,Country,Gender Equality Index,WORK,Participation,Segregation and quality of work,MONEY,Financial resources,Economic situation,KNOWLEDGE,Attainment and participation,...,Population without unmet needs for medical examination (%) T,Population without unmet needs for dental examination (%) W,Population without unmet needs for dental examination (%) M,Population without unmet needs for dental examination (%) T,Population (number) W,Population (number) M,Population (number) T,Population (%) W,Population (%) M,Population (%) T
0,EU-28,63.8,70.5,78.1,63.7,78.4,69.4,88.6,61.8,68.5,...,93.4,92.8,92.8,92.8,"210,830,090","196,034,441","406,864,531",51.8%,48.2%,100.0%
1,BE,69.3,72.7,75.7,69.8,85.5,77.9,94.0,70.6,73.3,...,99.3,97.5,97.3,97.4,"4,451,174","4,192,013","8,643,187",51.5%,48.5%,100.0%
2,BG,55.0,67.9,81.3,56.7,60.8,44.7,82.8,50.4,53.9,...,85.5,85.5,85.5,85.5,"3,221,030","2,993,039","6,214,069",51.8%,48.2%,100.0%
3,CZ,55.6,64.9,78.9,53.3,73.8,55.1,98.7,55.4,61.4,...,96.5,95.8,94.8,95.4,"4,425,910","4,185,304","8,611,214",51.4%,48.6%,100.0%
4,DK,75.2,79.8,88.5,71.9,83.6,78.3,89.3,73.2,81.7,...,96.3,97.2,95.1,96.2,"2,199,385","2,121,639","4,321,023",50.9%,49.1%,100.0%

In [6]:
gei_2012_df.head(5)

,Country,Gender Equality Index,WORK,Participation,Segregation and quality of work,MONEY,Financial resources,Economic situation,KNOWLEDGE,Attainment and participation,...,Population without unmet needs for medical examination (%) T,Population without unmet needs for dental examination (%) W,Population without unmet needs for dental examination (%) M,Population without unmet needs for dental examination (%) T,Population (number) W,Population (number) M,Population (number) T,Population (%) W,Population (%) M,Population (%) T
0,EU-28,65.0,71.0,78.7,64.0,78.4,70.0,87.9,62.8,70.4,...,93.6,92.7,93.0,92.8,"211,813,267","196,854,919","408,668,186",51.8%,48.2%,100.0%
1,BE,70.2,72.8,75.4,70.4,85.6,78.6,93.3,70.6,72.5,...,97.7,95.5,94.4,95.0,"4,534,368","4,291,001","8,825,369",51.4%,48.6%,100.0%
2,BG,56.9,68.7,82.0,57.6,60.5,44.2,82.7,51.9,54.6,...,88.5,88.6,88.8,88.7,"3,185,762","2,958,790","6,144,552",51.8%,48.2%,100.0%
3,CZ,56.7,65.3,79.9,53.3,74.0,55.8,98.1,57.7,66.3,...,96.2,96.0,95.3,95.7,"4,449,848","4,211,832","8,661,680",51.4%,48.6%,100.0%
4,DK,75.6,79.7,88.3,72.1,85.7,80.4,91.4,71.3,80.5,...,94.4,95.3,94.4,94.8,"2,228,058","2,151,992","4,380,050",50.9%,49.1%,100.0%

In [7]:
gei_2015_df.head(5)

,Country,Gender Equality Index,WORK,Participation,Segregation and quality of work,MONEY,Financial resources,Economic situation,KNOWLEDGE,Attainment and participation,...,Population without unmet needs for medical examination (%) T,Population without unmet needs for dental examination (%) W,Population without unmet needs for dental examination (%) M,Population without unmet needs for dental examination (%) T,Population (number) W,Population (number) M,Population (number) T,Population (%) W,Population (%) M,Population (%) T
0,EU-28,66.2,71.5,79.8,64.0,79.6,73.0,86.7,63.4,72.1,...,95.0,93.7,94.0,93.9,"213,784,337","199,340,866","413,125,203",51.7%,48.3%,100.0%
1,BE,70.5,73.8,77.5,70.2,87.5,82.7,92.6,71.1,73.3,...,97.1,94.5,94.7,94.6,"4,597,186","4,359,690","8,956,876",51.3%,48.7%,100.0%
2,BG,58.0,68.6,82.7,56.9,61.9,48.2,79.5,53.3,56.1,...,93.5,93.7,93.9,93.8,"3,124,248","2,892,703","6,016,950",51.9%,48.1%,100.0%
3,CZ,53.6,66.1,81.8,53.5,75.9,58.8,98.1,57.3,66.9,...,95.4,97.3,97.1,97.2,"4,447,546","4,214,360","8,661,907",51.3%,48.7%,100.0%
4,DK,76.8,79.2,87.2,72.0,86.6,82.4,91.1,73.6,82.1,...,92.9,94.8,92.5,93.7,"2,279,774","2,213,367","4,493,141",50.7%,49.3%,100.0%

In [8]:
gei_2005_df.shape

(29, 122)

In [9]:
gei_2005_df.columns

Index(['Country', 'Gender Equality Index', 'WORK', 'Participation',
       'Segregation and quality of work', 'MONEY', 'Financial resources',
       'Economic situation', 'KNOWLEDGE', 'Attainment and participation',
       ...
       'Population without unmet needs for medical examination (%) T',
       'Population without unmet needs for dental examination (%) W',
       'Population without unmet needs for dental examination (%) M',
       'Population without unmet needs for dental examination (%) T',
       'Population (number) W', 'Population (number) M',
       'Population (number) T', 'Population (%) W', 'Population (%) M',
       'Population (%) T'],
      dtype='object', length=122)

In [10]:
gei_2005_df.describe()

,Gender Equality Index,WORK,Participation,Segregation and quality of work,MONEY,Financial resources,Economic situation,KNOWLEDGE,Attainment and participation,Segregation,...,Healthy life years at birth (years) M,Healthy life years at birth (years) T,People who don't smoke and are not involved in harmful drinking (%) M,People who don't smoke and are not involved in harmful drinking (%) T,People doing physical activities and/or consuming fruits and vegetables (%) M,People doing physical activities and/or consuming fruits and vegetables (%) T,Population without unmet needs for medical examination (%) M,Population without unmet needs for medical examination (%) T,Population without unmet needs for dental examination (%) M,Population without unmet needs for dental examination (%) T
count,29.000000,29.000000,29.000000,29.000000,29.000000,29.000000,29.000000,29.000000,29.000000,29.000000,...,29.000000,29.000000,29.000000,29.000000,29.000000,29.000000,29.000000,29.000000,29.000000,29.000000
mean,58.613793,69.406897,77.327586,62.648276,72.500000,59.931034,88.831034,56.858621,63.006897,52.065517,...,59.900000,60.665517,52.234483,62.779310,40.079310,37.982759,91.875862,91.206897,89.858621,89.834483
std,8.750417,4.560696,7.926623,5.698159,10.456167,14.609980,6.208871,8.265398,9.739497,11.005008,...,5.583458,5.419823,7.000422,5.416007,11.415321,12.923126,6.541442,7.240804,6.546783,6.734945
min,45.900000,60.800000,51.400000,53.600000,53.200000,33.500000,78.400000,43.400000,48.500000,28.700000,...,48.300000,50.400000,36.200000,52.300000,16.300000,11.700000,74.800000,70.700000,71.200000,71.000000
25%,52.200000,66.300000,74.800000,58.000000,66.500000,47.300000,83.200000,52.100000,54.300000,45.500000,...,56.400000,57.900000,46.500000,58.400000,34.000000,31.100000,86.700000,85.000000,86.700000,86.900000
50%,56.000000,70.000000,77.900000,61.400000,73.600000,62.200000,89.500000,56.600000,65.500000,53.300000,...,60.500000,61.500000,53.300000,63.200000,38.700000,35.700000,93.700000,93.600000,90.500000,91.000000
75%,64.400000,71.700000,83.500000,67.400000,81.300000,71.900000,94.500000,62.000000,67.900000,57.900000,...,64.200000,64.100000,57.200000,65.400000,47.200000,47.800000,96.500000,96.200000,93.900000,94.400000
max,78.800000,78.900000,88.700000,74.500000,93.100000,91.200000,98.000000,75.800000,85.700000,77.000000,...,68.600000,69.500000,65.600000,74.300000,59.100000,63.600000,99.500000,99.500000,99.200000,99.300000

In [11]:
gei_2005_df.sample(5)

,Country,Gender Equality Index,WORK,Participation,Segregation and quality of work,MONEY,Financial resources,Economic situation,KNOWLEDGE,Attainment and participation,...,Population without unmet needs for medical examination (%) T,Population without unmet needs for dental examination (%) W,Population without unmet needs for dental examination (%) M,Population without unmet needs for dental examination (%) T,Population (number) W,Population (number) M,Population (number) T,Population (%) W,Population (%) M,Population (%) T
9,ES,62.2,68.1,70.9,65.4,73.6,63.5,85.4,59.3,68.8,...,93.6,91.0,90.4,90.7,"18,252,050","17,408,585","35,660,635",51.2%,48.8%,100.0%
27,SE,78.8,78.7,88.7,69.9,84.1,72.2,98.0,68.1,70.6,...,85.0,87.5,87.2,87.4,"3,601,374","3,471,955","7,073,329",50.9%,49.1%,100.0%
12,IT,49.2,60.8,63.8,58.0,76.2,68.0,85.4,54.1,51.8,...,93.1,89.0,89.6,89.3,"25,002,066","22,937,269","47,939,335",52.2%,47.8%,100.0%
15,LT,55.8,71.9,84.1,61.5,57.0,40.7,80.1,55.1,66.8,...,90.1,87.9,88.9,88.3,"1,435,663","1,186,614","2,622,278",54.7%,45.3%,100.0%
7,IE,61.9,71.1,75.1,67.4,79.5,73.6,85.8,60.8,67.1,...,97.5,95.7,96.4,96.0,"1,563,935","1,525,854","3,089,789",50.6%,49.4%,100.0%

In [12]:
con_info_df.sample(5)

,Country Short,Country Long,Communist,USSR,Eurozone,Schengen Area,Religion,Region
26,ES,Spain,No,No,Yes,Yes,Catholic,Southern
0,AT,Austria,No,No,Yes,Yes,Catholic,Central
17,LT,Lithuania,Yes,Yes,Yes,Yes,Catholic,Central
11,DE,Germany,Split,No,Yes,Yes,Split Catholic and Protestant,Central
14,IE,Ireland,No,No,Yes,No,Catholic,Western

### Merge Data Frames

In [13]:
# Sort data frames so the information lines up

con_info_df = con_info_df.sort_values('Country Short')

gei_2005_df = gei_2005_df.sort_values('Country')
gei_2010_df = gei_2010_df.sort_values('Country')
gei_2012_df = gei_2012_df.sort_values('Country')
gei_2015_df = gei_2015_df.sort_values('Country')

In [14]:
con_info_df.head(5)

,Country Short,Country Long,Communist,USSR,Eurozone,Schengen Area,Religion,Region
0,AT,Austria,No,No,Yes,Yes,Catholic,Central
1,BE,Belgium,No,No,Yes,Yes,Catholic,Western
2,BG,Bulgaria,Yes,No,No,No,Orthodox,Southeastern
4,CY,Cyprus,No,No,Yes,No,Orthodox,Southeastern
5,CZ,Czech Republic,Yes,No,No,Yes,Catholic,Central

In [15]:
# Reset the indexes 

con_info_df = con_info_df.reset_index(drop=True)

gei_2005_df = gei_2005_df.reset_index(drop=True)
gei_2010_df = gei_2010_df.reset_index(drop=True)
gei_2012_df = gei_2012_df.reset_index(drop=True)
gei_2015_df = gei_2015_df.reset_index(drop=True)

In [16]:
gei_2005_df.head(5)

,Country,Gender Equality Index,WORK,Participation,Segregation and quality of work,MONEY,Financial resources,Economic situation,KNOWLEDGE,Attainment and participation,...,Population without unmet needs for medical examination (%) T,Population without unmet needs for dental examination (%) W,Population without unmet needs for dental examination (%) M,Population without unmet needs for dental examination (%) T,Population (number) W,Population (number) M,Population (number) T,Population (%) W,Population (%) M,Population (%) T
0,AT,59.5,73.7,77.0,70.6,82.5,71.9,94.6,58.9,58.9,...,98.0,97.3,97.4,97.4,"3,429,571","3,156,787","6,586,358",52.1%,47.9%,100.0%
1,BE,66.0,71.0,72.3,69.8,81.3,73.9,89.5,68.1,70.7,...,99.0,97.0,97.4,97.2,"4,275,415","4,003,552","8,278,967",51.6%,48.4%,100.0%
2,BG,56.0,67.3,77.9,58.1,54.3,33.5,88.1,52.5,53.0,...,74.9,71.4,73.6,72.5,"3,282,615","3,044,971","6,327,586",51.9%,48.1%,100.0%
3,CY,45.9,66.3,78.5,55.9,72.6,60.5,87.1,43.4,65.5,...,94.0,86.5,86.7,86.6,"286,201","266,904","553,105",51.7%,48.3%,100.0%
4,CZ,53.6,65.3,79.6,53.6,70.2,50.6,97.4,52.2,52.0,...,92.8,95.2,94.2,94.8,"4,299,258","3,995,629","8,294,887",51.8%,48.2%,100.0%

In [17]:
gei_2010_df
gei_2010_df.reset_index(drop=True)

gei_2012_df
gei_2012_df.reset_index(drop=True)

gei_2015_df
gei_2015_df.reset_index(drop=True)

,Country,Gender Equality Index,WORK,Participation,Segregation and quality of work,MONEY,Financial resources,Economic situation,KNOWLEDGE,Attainment and participation,...,Population without unmet needs for medical examination (%) T,Population without unmet needs for dental examination (%) W,Population without unmet needs for dental examination (%) M,Population without unmet needs for dental examination (%) T,Population (number) W,Population (number) M,Population (number) T,Population (%) W,Population (%) M,Population (%) T
0,AT,63.3,76.1,81.4,71.2,85.9,79.8,92.5,63.2,72.0,...,99.3,99.0,99.0,99.0,"3,657,800","3,435,520","7,093,320",51.6%,48.4%,100.0%
1,BE,70.5,73.8,77.5,70.2,87.5,82.7,92.6,71.1,73.3,...,97.1,94.5,94.7,94.6,"4,597,186","4,359,690","8,956,876",51.3%,48.7%,100.0%
2,BG,58.0,68.6,82.7,56.9,61.9,48.2,79.5,53.3,56.1,...,93.5,93.7,93.9,93.8,"3,124,248","2,892,703","6,016,950",51.9%,48.1%,100.0%
3,CY,55.1,70.7,84.7,59.0,79.2,72.1,87.1,58.5,73.3,...,97.9,94.8,95.0,94.9,"354,340","327,079","681,419",52.0%,48.0%,100.0%
4,CZ,53.6,66.1,81.8,53.5,75.9,58.8,98.1,57.3,66.9,...,95.4,97.3,97.1,97.2,"4,447,546","4,214,360","8,661,907",51.3%,48.7%,100.0%
5,DE,65.5,71.4,81.9,62.2,84.2,81.2,87.4,52.9,61.0,...,99.1,98.9,98.8,98.9,"35,008,683","33,200,470","68,209,153",51.3%,48.7%,100.0%
6,DK,76.8,79.2,87.2,72.0,86.6,82.4,91.1,73.6,82.1,...,92.9,94.8,92.5,93.7,"2,279,774","2,213,367","4,493,141",50.7%,49.3%,100.0%
7,EE,56.7,72.1,88.6,58.7,66.7,56.4,79.0,53.2,67.9,...,85.4,87.0,89.1,88.0,"580,931","489,488","1,070,419",54.3%,45.7%,100.0%
8,EL,50.0,64.2,71.0,58.0,70.7,61.4,81.4,55.6,63.9,...,85.8,85.6,86.3,86.0,"4,660,372","4,295,845","8,956,217",52.0%,48.0%,100.0%
9,ES,68.3,72.4,78.0,67.3,75.9,71.0,81.2,65.3,73.3,...,98.8,93.7,94.2,94.0,"19,584,375","18,537,066","38,121,442",51.4%,48.6%,100.0%
10,EU-28,66.2,71.5,79.8,64.0,79.6,73.0,86.7,63.4,72.1,...,95.0,93.7,94.0,93.9,"213,784,337","199,340,866","413,125,203",51.7%,48.3%,100.0%
11,FI,73.0,74.7,89.2,62.6,86.4,78.5,95.2,61.3,81.4,...,94.7,93.7,94.0,93.9,"2,253,295","2,141,738","4,395,033",51.3%,48.7%,100.0%
12,FR,72.6,72.1,82.3,63.2,86.1,80.4,92.3,66.1,77.5,...,96.4,93.4,93.9,93.7,"27,033,563","24,613,458","51,647,021",52.3%,47.7%,100.0%
13,HR,53.1,69.4,78.5,61.4,69.9,57.1,85.6,49.8,59.3,...,94.8,97.0,96.8,96.9,"1,813,204","1,645,751","3,458,955",52.4%,47.6%,100.0%
14,HU,50.8,67.2,79.6,56.7,70.7,55.2,90.5,56.9,64.6,...,92.4,93.8,93.6,93.7,"4,319,911","3,810,575","8,130,486",53.1%,46.9%,100.0%
15,IE,69.5,73.9,78.3,69.7,84.7,81.0,88.6,66.4,74.1,...,96.7,93.2,94.4,93.8,"1,764,286","1,685,945","3,450,231",51.1%,48.9%,100.0%
16,IT,62.1,62.4,66.7,58.4,78.6,73.0,84.6,61.4,56.1,...,92.1,88.4,89.4,88.9,"26,372,718","24,287,825","50,660,543",52.1%,47.9%,100.0%
17,LT,56.8,73.2,88.2,60.7,65.6,53.5,80.4,55.8,68.4,...,95.7,95.1,96.0,95.5,"1,318,013","1,074,644","2,392,657",55.1%,44.9%,100.0%
18,LU,69.0,74.0,81.3,67.4,94.4,97.0,92.0,69.4,84.1,...,95.1,97.4,96.1,96.8,"225,806","223,939","449,745",50.2%,49.8%,100.0%
19,LV,57.9,73.6,87.8,61.8,64.3,51.9,79.5,48.9,59.1,...,88.2,84.1,82.7,83.4,"904,824","731,751","1,636,575",55.3%,44.7%,100.0%
20,MT,60.1,71.0,68.9,73.1,82.4,73.3,92.8,65.2,61.3,...,98.0,97.4,97.5,97.4,"178,150","176,029","354,178",50.3%,49.7%,100.0%
21,NL,72.9,76.7,79.2,74.3,86.8,79.1,95.4,67.3,80.9,...,99.6,99.4,99.2,99.3,"6,853,925","6,619,595","13,473,520",50.9%,49.1%,100.0%
22,PL,56.8,66.8,79.5,56.2,73.3,61.4,87.5,56.0,61.3,...,87.2,92.3,92.3,92.3,"16,250,331","14,857,879","31,108,210",52.2%,47.8%,100.0%
23,PT,56.0,72.0,85.4,60.8,70.9,60.3,83.5,54.8,59.5,...,95.4,81.2,82.4,81.8,"4,561,588","3,992,640","8,554,228",53.3%,46.7%,100.0%
24,RO,52.4,67.1,77.5,58.1,59.4,45.7,77.3,51.8,52.9,...,88.5,88.8,90.5,89.6,"8,342,875","7,783,462","16,126,336",51.7%,48.3%,100.0%
25,SE,82.6,82.6,95.4,71.5,87.5,82.3,93.1,72.8,78.5,...,91.2,94.8,93.4,94.1,"3,910,212","3,849,921","7,760,133",50.4%,49.6%,100.0%
26,SI,68.4,71.8,83.5,61.7,81.6,69.8,95.5,55.0,67.4,...,99.6,98.9,99.1,99.0,"865,908","836,767","1,702,675",50.9%,49.1%,100.0%
27,SK,52.4,65.5,80.6,53.2,74.0,56.4,97.2,60.0,58.8,...,94.2,95.4,95.0,95.2,"2,290,720","2,128,363","4,419,084",51.8%,48.2%,100.0%
28,UK,71.5,76.6,83.6,70.2,81.2,77.0,85.6,71.8,82.2,...,95.0,95.1,95.1,95.1,"26,229,753","24,914,996","51,144,749",51.3%,48.7%,100.0%

In [18]:
gei_2005_df.head(5)

,Country,Gender Equality Index,WORK,Participation,Segregation and quality of work,MONEY,Financial resources,Economic situation,KNOWLEDGE,Attainment and participation,...,Population without unmet needs for medical examination (%) T,Population without unmet needs for dental examination (%) W,Population without unmet needs for dental examination (%) M,Population without unmet needs for dental examination (%) T,Population (number) W,Population (number) M,Population (number) T,Population (%) W,Population (%) M,Population (%) T
0,AT,59.5,73.7,77.0,70.6,82.5,71.9,94.6,58.9,58.9,...,98.0,97.3,97.4,97.4,"3,429,571","3,156,787","6,586,358",52.1%,47.9%,100.0%
1,BE,66.0,71.0,72.3,69.8,81.3,73.9,89.5,68.1,70.7,...,99.0,97.0,97.4,97.2,"4,275,415","4,003,552","8,278,967",51.6%,48.4%,100.0%
2,BG,56.0,67.3,77.9,58.1,54.3,33.5,88.1,52.5,53.0,...,74.9,71.4,73.6,72.5,"3,282,615","3,044,971","6,327,586",51.9%,48.1%,100.0%
3,CY,45.9,66.3,78.5,55.9,72.6,60.5,87.1,43.4,65.5,...,94.0,86.5,86.7,86.6,"286,201","266,904","553,105",51.7%,48.3%,100.0%
4,CZ,53.6,65.3,79.6,53.6,70.2,50.6,97.4,52.2,52.0,...,92.8,95.2,94.2,94.8,"4,299,258","3,995,629","8,294,887",51.8%,48.2%,100.0%

In [19]:
con_info_df.head(5)

,Country Short,Country Long,Communist,USSR,Eurozone,Schengen Area,Religion,Region
0,AT,Austria,No,No,Yes,Yes,Catholic,Central
1,BE,Belgium,No,No,Yes,Yes,Catholic,Western
2,BG,Bulgaria,Yes,No,No,No,Orthodox,Southeastern
3,CY,Cyprus,No,No,Yes,No,Orthodox,Southeastern
4,CZ,Czech Republic,Yes,No,No,Yes,Catholic,Central

In [20]:
# Attach country information data to year data frames

i_2005_df = pd.concat([gei_2005_df, con_info_df], axis=1)
i_2010_df = pd.concat([gei_2010_df, con_info_df], axis=1)
i_2012_df = pd.concat([gei_2012_df, con_info_df], axis=1)
i_2015_df = pd.concat([gei_2015_df, con_info_df], axis=1)

In [21]:
i_2005_df.sample(5)

,Country,Gender Equality Index,WORK,Participation,Segregation and quality of work,MONEY,Financial resources,Economic situation,KNOWLEDGE,Attainment and participation,...,Population (%) M,Population (%) T,Country Short,Country Long,Communist,USSR,Eurozone,Schengen Area,Religion,Region
22,PL,52.4,65.2,75.1,56.7,61.4,46.2,81.4,56.7,63.0,...,47.6%,100.0%,PL,Poland,Yes,No,No,Yes,Catholic,Central
11,FI,72.0,74.2,88.2,62.5,80.1,67.9,94.6,56.6,77.8,...,48.4%,100.0%,FI,Finland,No,No,Yes,Yes,Protestant,Northern
18,LU,64.4,68.1,70.2,66.1,93.1,91.2,95.1,62.0,65.6,...,48.9%,100.0%,LU,Luxembourg,No,No,Yes,Yes,Catholic,Central
19,LV,53.4,71.7,83.6,61.4,56.3,40.2,78.7,46.6,60.2,...,44.6%,100.0%,LV,Latvia,Yes,Yes,Yes,Yes,Split Catholic and Protestant,Central
8,EL,46.8,62.5,68.0,57.5,71.9,62.2,83.2,47.2,54.3,...,49.0%,100.0%,EL,Greece,No,No,Yes,Yes,Orthodox,Southeastern

In [22]:
# Merge year data frames

# Add year column to each data frame

i_2005_df['Year'] = '2005'

i_2010_df['Year'] = '2010'

i_2012_df['Year'] = '2012'

i_2015_df['Year'] = '2015'

In [23]:
i_2005_df.sample(5)

,Country,Gender Equality Index,WORK,Participation,Segregation and quality of work,MONEY,Financial resources,Economic situation,KNOWLEDGE,Attainment and participation,...,Population (%) T,Country Short,Country Long,Communist,USSR,Eurozone,Schengen Area,Religion,Region,Year
6,DK,74.6,78.9,88.5,70.3,82.7,71.2,96.1,73.7,81.1,...,100.0%,DK,Denmark,No,No,No,Yes,Protestant,Northern,2005
5,DE,60.0,68.1,75.6,61.4,83.3,73.7,94.1,55.3,56.7,...,100.0%,DE,Germany,Split,No,Yes,Yes,Split Catholic and Protestant,Central,2005
4,CZ,53.6,65.3,79.6,53.6,70.2,50.6,97.4,52.2,52.0,...,100.0%,CZ,Czech Republic,Yes,No,No,Yes,Catholic,Central,2005
26,SI,60.8,71.2,83.5,60.7,77.7,62.9,95.9,52.1,67.9,...,100.0%,SI,Slovenia,Yes,No,Yes,Yes,Catholic,Central,2005
0,AT,59.5,73.7,77.0,70.6,82.5,71.9,94.6,58.9,58.9,...,100.0%,AT,Austria,No,No,Yes,Yes,Catholic,Central,2005

In [24]:
i_2010_df.sample(5)

,Country,Gender Equality Index,WORK,Participation,Segregation and quality of work,MONEY,Financial resources,Economic situation,KNOWLEDGE,Attainment and participation,...,Population (%) T,Country Short,Country Long,Communist,USSR,Eurozone,Schengen Area,Religion,Region,Year
24,RO,50.8,67.9,78.8,58.6,59.8,42.5,84.2,47.2,50.1,...,100.0%,RO,Romania,Yes,No,No,No,Orthodox,Southeastern,2010
3,CY,49.0,70.5,85.2,58.3,80.7,74.8,87.1,55.5,73.6,...,100.0%,CY,Cyprus,No,No,Yes,No,Orthodox,Southeastern,2010
9,ES,66.4,71.8,77.0,66.9,77.1,70.4,84.4,63.5,71.8,...,100.0%,ES,Spain,No,No,Yes,Yes,Catholic,Southern,2010
23,PT,53.7,71.4,85.6,59.5,71.8,60.4,85.3,50.1,50.8,...,100.0%,PT,Portugal,No,No,Yes,Yes,Catholic,Southern,2010
5,DE,62.6,70.0,79.0,62.1,83.2,77.1,89.8,56.3,59.9,...,100.0%,DE,Germany,Split,No,Yes,Yes,Split Catholic and Protestant,Central,2010

In [25]:
i_2012_df.sample(5)

,Country,Gender Equality Index,WORK,Participation,Segregation and quality of work,MONEY,Financial resources,Economic situation,KNOWLEDGE,Attainment and participation,...,Population (%) T,Country Short,Country Long,Communist,USSR,Eurozone,Schengen Area,Religion,Region,Year
9,ES,67.4,72.3,77.5,67.4,76.0,69.6,82.9,64.2,73.0,...,100.0%,ES,Spain,No,No,Yes,Yes,Catholic,Southern,2012
8,EL,50.1,63.6,69.4,58.4,71.1,62.7,80.7,54.3,60.7,...,100.0%,EL,Greece,No,No,Yes,Yes,Orthodox,Southeastern,2012
5,DE,64.9,70.6,80.2,62.1,84.0,78.1,90.2,57.1,62.7,...,100.0%,DE,Germany,Split,No,Yes,Yes,Split Catholic and Protestant,Central,2012
12,FR,68.9,71.9,81.4,63.5,83.7,77.2,90.6,62.4,69.7,...,100.0%,FR,France,No,No,Yes,Yes,Catholic,Western,2012
19,LV,56.2,74.3,86.9,63.5,59.6,43.5,81.5,48.8,62.2,...,100.0%,LV,Latvia,Yes,Yes,Yes,Yes,Split Catholic and Protestant,Central,2012

In [26]:
i_2015_df.sample(5)

,Country,Gender Equality Index,WORK,Participation,Segregation and quality of work,MONEY,Financial resources,Economic situation,KNOWLEDGE,Attainment and participation,...,Population (%) T,Country Short,Country Long,Communist,USSR,Eurozone,Schengen Area,Religion,Region,Year
14,HU,50.8,67.2,79.6,56.7,70.7,55.2,90.5,56.9,64.6,...,100.0%,HU,Hungary,Yes,No,No,Yes,Catholic,Central,2015
20,MT,60.1,71.0,68.9,73.1,82.4,73.3,92.8,65.2,61.3,...,100.0%,MT,Malta,No,No,Yes,Yes,Catholic,Southern,2015
22,PL,56.8,66.8,79.5,56.2,73.3,61.4,87.5,56.0,61.3,...,100.0%,PL,Poland,Yes,No,No,Yes,Catholic,Central,2015
2,BG,58.0,68.6,82.7,56.9,61.9,48.2,79.5,53.3,56.1,...,100.0%,BG,Bulgaria,Yes,No,No,No,Orthodox,Southeastern,2015
1,BE,70.5,73.8,77.5,70.2,87.5,82.7,92.6,71.1,73.3,...,100.0%,BE,Belgium,No,No,Yes,Yes,Catholic,Western,2015

In [27]:
# Merge the 4 data frames

frames = [i_2005_df, i_2010_df, i_2012_df, i_2015_df]

gei_df = pd.concat(frames)

In [28]:
gei_df.sample(5)

,Country,Gender Equality Index,WORK,Participation,Segregation and quality of work,MONEY,Financial resources,Economic situation,KNOWLEDGE,Attainment and participation,...,Population (%) T,Country Short,Country Long,Communist,USSR,Eurozone,Schengen Area,Religion,Region,Year
4,CZ,53.6,65.3,79.6,53.6,70.2,50.6,97.4,52.2,52.0,...,100.0%,CZ,Czech Republic,Yes,No,No,Yes,Catholic,Central,2005
12,FR,65.2,70.5,79.1,62.9,81.6,71.4,93.2,62.3,67.1,...,100.0%,FR,France,No,No,Yes,Yes,Catholic,Western,2005
16,IT,62.1,62.4,66.7,58.4,78.6,73.0,84.6,61.4,56.1,...,100.0%,IT,Italy,No,No,Yes,Yes,Catholic,Southern,2015
26,SI,62.7,71.9,84.4,61.3,80.3,67.3,95.8,55.0,68.4,...,100.0%,SI,Slovenia,Yes,No,Yes,Yes,Catholic,Central,2010
21,NL,72.9,76.7,79.2,74.3,86.8,79.1,95.4,67.3,80.9,...,100.0%,NL,Netherlands,No,No,Yes,Yes,Split Catholic and Protestant,Western,2015

In [29]:
# Save dataframe ("gei_df") to data folder as "whole_GEI_dataset"

gei_df.to_csv('../data/whole_GEI_dataset.csv', index=False)