This notebook is dedicated to investigating and cleaning the anxiety dataset.

In [1]:
%matplotlib inline
import warnings
warnings.simplefilter('ignore')
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
anxiety_df = pd.read_csv('../data/Raw/with-anxiety-disorders.csv')

In [3]:
anxiety_df.shape

(6468, 4)

In [4]:
anxiety_df.head()

,Entity,Code,Year,Prevalence - Anxiety disorders - Sex: Both - Age: Age-standardized (Percent) (%)
0,Afghanistan,AFG,1990,4.828830
1,Afghanistan,AFG,1991,4.829740
2,Afghanistan,AFG,1992,4.831108
3,Afghanistan,AFG,1993,4.830864
4,Afghanistan,AFG,1994,4.829423

In [5]:
anxiety_df['Year'].unique()

array([1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000,
       2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012, 2013, 2014, 2015, 2016, 2017])

In [6]:
anxiety_df['Entity'].nunique()

231

After making some oberservations about what is included in the data, I rename one of the colums to make it easier to manipulate.

In [7]:
anxiety_df = anxiety_df.rename(columns={'Prevalence - Anxiety disorders - Sex: Both - Age: Age-standardized (Percent) (%)':'Anxiety_percent'})

Since the datasheet lacks information about which continent each country is from, I upload a dataset that includes the names of the countries and continents.

In [8]:
continents_df = pd.read_csv('../data/Raw/countries_continents2.csv')
continents_df.head()

   Unnamed: 0         Country           Region Continent
0           0     Afghanistan    Southern Asia      Asia
1           1   Åland Islands  Northern Europe    Europe
2           2         Albania  Southern Europe    Europe
3           3         Algeria  Northern Africa    Africa
4           4  American Samoa        Polynesia   Oceania

In [9]:
continents_df['Country'].unique()

array(['Afghanistan', 'Åland Islands', 'Albania', 'Algeria',
       'American Samoa', 'Andorra', 'Angola', 'Anguilla', 'Antarctica',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bermuda', 'Bhutan', 'Bolivia', 'Bonaire, Sint Eustatius and Saba',
       'Bosnia and Herzegovina', 'Botswana', 'Bouvet Island', 'Brazil',
       'British Indian Ocean Territory', 'British Virgin Islands',
       'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cape Verde',
       'Cambodia', 'Cameroon', 'Canada', 'Cayman Islands',
       'Central African Republic', 'Chad', 'Chile', 'China',
       'China, Hong Kong Special Administrative Region',
       'China, Macao Special Administrative Region', 'Christmas Island',
       'Cocos (Keeling) Islands', 'Colombia', 'Comoros', 'Congo',
       'Cook Islands', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba',
       'Curaçao', 'Cyprus', 'Cezch Republic', 'North Korea',
       'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Swaziland', 'Ethiopia', 'Falkland Islands (Malvinas)',
       'Faroe Islands', 'Fiji', 'Finland', 'France', 'French Guiana',
       'French Polynesia', 'French Southern Territories', 'Gabon',
       'Gambia', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece',
       'Greenland', 'Grenada', 'Guadeloupe', 'Guam', 'Guatemala',
       'Guernsey', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti',
       'Heard Island and McDonald Islands', 'Holy See', 'Honduras',
       'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq',
       'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica', 'Japan',
       'Jersey', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait',
       'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia',
       'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar',
       'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Martinique', 'Mauritania', 'Mauritius',
       'Mayotte', 'Mexico', 'Micronesia (country)', 'Monaco', 'Mongolia',
       'Montenegro', 'Montserrat', 'Morocco', 'Mozambique', 'Myanmar',
       'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Caledonia',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue',
       'Norfolk Island', 'North Macedonia', 'Northern Mariana Islands',
       'Norway', 'Oman', 'Pakistan', 'Palau', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Pitcairn',
       'Poland', 'Portugal', 'Puerto Rico', 'Qatar', 'South Korea',
       'Moldova', 'Réunion', 'Romania', 'Russia', 'Rwanda',
       'Saint Barthélemy', 'Saint Helena', 'Saint Kitts and Nevis',
       'Saint Lucia', 'Saint Martin (French Part)',
       'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines',
       'Samoa', 'San Marino', 'Sao Tome and Principe', 'Sark',
       'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone',
       'Singapore', 'Sint Maarten (Dutch part)', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa',
       'South Georgia and the South Sandwich Islands', 'South Sudan',
       'Spain', 'Sri Lanka', 'Palestine', 'Sudan', 'Suriname',
       'Svalbard and Jan Mayen Islands', 'Sweden', 'Switzerland', 'Syria',
       'Tajikistan', 'Thailand', 'Timor', 'Togo', 'Tokelau', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'Tanzania',
       'United States Minor Outlying Islands', 'United States',
       'United States Virgin Islands', 'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela', 'Vietnam', 'Wallis and Futuna Islands',
       'Western Sahara', 'Yemen', 'Zambia', 'Zimbabwe'], dtype=object)

I then merge this data set with the anxiety dataset, and see how many countries merged.

In [10]:
merged_df = anxiety_df.merge(continents_df, left_on='Entity', right_on='Country')
merged_df.shape

(5348, 8)

In [11]:
merged_df['Entity'].nunique()

191

I am specifically interested in exploring rates of anxiety in countries of the world. Both the anxiety and continents dataset contain more locations than when they are merged together. However, I still have 191 unique entities in the new merged dataset, which is roughly equal to the number of countries in the world. I am satisfied that this is enough for analysis, recognizing that some data points are being excluded from analysis.

I then examine the mean, min, and max values for anxiety per continent:

In [12]:
merged_df.groupby('Continent')['Anxiety_percent'].agg(['mean', 'min','max'])

                   mean       min       max
Continent
Africa         3.427705  2.835318  5.072361
Asia           3.777915  2.023393  7.174615
Europe         4.461878  2.867995  7.680800
North America  4.290270  2.799207  6.971995
Oceania        3.868394  3.150086  8.967330
South America  4.837711  2.512714  6.397380

To further analyze the data, I imported a dataset that includes the population of each countries for every year represented in the anxiety dataset.

In [13]:
pop_df = pd.read_csv('../data/Cleaned/world_pop_1000s_clean')
pop_df.shape

(285, 32)

In [14]:
pop_df.head()

,code,Location,1990,1991,1992,1993,1994,1995,1996,1997,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,Average
0,900,World,5327231.0,5414289.0,5498920.0,5581598.0,5663150.0,5744213.0,5824892.0,5905046.0,...,6956824.0,7041194.0,7125828.0,7210582.0,7295291.0,7379797.0,7464022.0,7547859.0,7631091.0,6.472563e+06
1,901,More developed regions,1145508.0,1150893.0,1155966.0,1160737.0,1165232.0,1169481.0,1173490.0,1177284.0,...,1234768.0,1239557.0,1244115.0,1248454.0,1252615.0,1256622.0,1260479.0,1264146.0,1267559.0,1.207273e+06
2,902,Less developed regions,4181723.0,4263396.0,4342953.0,4420861.0,4497919.0,4574731.0,4651402.0,4727762.0,...,5722056.0,5801637.0,5881713.0,5962129.0,6042676.0,6123175.0,6203543.0,6283713.0,6363532.0,5.265290e+06
3,941,Least developed countries,506276.0,520262.0,534731.0,549559.0,564581.0,579682.0,594801.0,609983.0,...,836615.0,856471.0,876867.0,897793.0,919223.0,941131.0,963520.0,986385.0,1009691.0,7.370169e+05
4,934,"Less developed regions, excluding least develo...",3675448.0,3743134.0,3808222.0,3871301.0,3933338.0,3995050.0,4056601.0,4117778.0,...,4885441.0,4945165.0,5004846.0,5064335.0,5123453.0,5182043.0,5240024.0,5297327.0,5353841.0,4.528273e+06

In [15]:
merged_df['Entity'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra',
       'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina',
       'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso',
       'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde',
       'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
       'Comoros', 'Congo', 'Costa Rica', "Cote d'Ivoire", 'Croatia',
       'Cuba', 'Cyprus', 'Denmark', 'Djibouti', 'Dominica',
       'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador',
       'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia', 'Fiji',
       'Finland', 'France', 'Gabon', 'Gambia', 'Georgia', 'Germany',
       'Ghana', 'Greece', 'Greenland', 'Grenada', 'Guam', 'Guatemala',
       'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras',
       'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq',
       'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan', 'Laos',
       'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Lithuania',
       'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives',
       'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius',
       'Mexico', 'Micronesia (country)', 'Moldova', 'Mongolia',
       'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
       'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger',
       'Nigeria', 'North Korea', 'Northern Mariana Islands', 'Norway',
       'Oman', 'Pakistan', 'Palestine', 'Panama', 'Papua New Guinea',
       'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal',
       'Puerto Rico', 'Qatar', 'Romania', 'Russia', 'Rwanda',
       'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Korea',
       'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname',
       'Swaziland', 'Sweden', 'Switzerland', 'Syria', 'Tajikistan',
       'Tanzania', 'Thailand', 'Timor', 'Togo', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom',
       'United States', 'United States Virgin Islands', 'Uruguay',
       'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam', 'Yemen', 'Zambia',
       'Zimbabwe'], dtype=object)

In [16]:
pop_df.head()

,code,Location,1990,1991,1992,1993,1994,1995,1996,1997,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,Average
0,900,World,5327231.0,5414289.0,5498920.0,5581598.0,5663150.0,5744213.0,5824892.0,5905046.0,...,6956824.0,7041194.0,7125828.0,7210582.0,7295291.0,7379797.0,7464022.0,7547859.0,7631091.0,6.472563e+06
1,901,More developed regions,1145508.0,1150893.0,1155966.0,1160737.0,1165232.0,1169481.0,1173490.0,1177284.0,...,1234768.0,1239557.0,1244115.0,1248454.0,1252615.0,1256622.0,1260479.0,1264146.0,1267559.0,1.207273e+06
2,902,Less developed regions,4181723.0,4263396.0,4342953.0,4420861.0,4497919.0,4574731.0,4651402.0,4727762.0,...,5722056.0,5801637.0,5881713.0,5962129.0,6042676.0,6123175.0,6203543.0,6283713.0,6363532.0,5.265290e+06
3,941,Least developed countries,506276.0,520262.0,534731.0,549559.0,564581.0,579682.0,594801.0,609983.0,...,836615.0,856471.0,876867.0,897793.0,919223.0,941131.0,963520.0,986385.0,1009691.0,7.370169e+05
4,934,"Less developed regions, excluding least develo...",3675448.0,3743134.0,3808222.0,3871301.0,3933338.0,3995050.0,4056601.0,4117778.0,...,4885441.0,4945165.0,5004846.0,5064335.0,5123453.0,5182043.0,5240024.0,5297327.0,5353841.0,4.528273e+06

In [17]:
pop_df.shape

(285, 32)

In [18]:
pop_df['Location'].unique()

array(['World', 'More developed regions', 'Less developed regions',
       'Least developed countries',
       'Less developed regions, excluding least developed countries',
       'Less developed regions, excluding China',
       'Land-locked Developing Countries (LLDC)',
       'Small Island Developing States (SIDS)', 'High-income countries',
       'Middle-income countries', 'Upper-middle-income countries',
       'Lower-middle-income countries', 'Low-income countries',
       'No income group available', 'Africa', 'Asia', 'Europe',
       'Latin America and the Caribbean', 'Northern America', 'Oceania',
       'Sub-Saharan Africa', 'Eastern Africa', 'Burundi', 'Comoros',
       'Djibouti', 'Eritrea', 'Ethiopia', 'Kenya', 'Madagascar', 'Malawi',
       'Mauritius', 'Mayotte', 'Mozambique', 'Réunion', 'Rwanda',
       'Seychelles', 'Somalia', 'South Sudan', 'Uganda', 'Tanzania',
       'Zambia', 'Zimbabwe', ' Middle Africa', 'Angola', 'Cameroon',
       'Central African Republic', 'Chad', 'Congo', 'Equatorial Guinea',
       'Gabon', 'Sao Tome and Principe', 'Southern Africa', 'Botswana',
       'Swaziland', 'Lesotho', 'Namibia', 'South Africa',
       'Western Africa', 'Benin', 'Burkina Faso', 'Cape Verde',
       "Côte d'Ivoire", 'Gambia', 'Ghana', 'Guinea', 'Guinea-Bissau',
       'Liberia', 'Mali', 'Mauritania', 'Niger', 'Nigeria',
       'Saint Helena', 'Senegal', 'Sierra Leone', 'Togo',
       'Northern Africa and Western Asia', ' Northern Africa', 'Algeria',
       'Egypt', 'Libya', 'Morocco', 'Sudan', 'Tunisia', 'Western Sahara',
       'Western Asia', 'Armenia', 'Azerbaijan', 'Bahrain', 'Cyprus',
       'Georgia', 'Iraq', 'Israel', 'Jordan', 'Kuwait', 'Lebanon', 'Oman',
       'Qatar', 'Saudi Arabia', 'Palestine', 'Syria', 'Turkey',
       'United Arab Emirates', 'Yemen', 'Central and Southern Asia',
       ' Central Asia', 'Kazakhstan', 'Kyrgyzstan', 'Tajikistan',
       'Turkmenistan', 'Uzbekistan', 'Southern Asia', 'Afghanistan',
       'Bangladesh', 'Bhutan', 'India', 'Iran', 'Maldives', 'Nepal',
       'Pakistan', 'Sri Lanka', 'Eastern and South-Eastern Asia',
       'Eastern Asia', 'China', 'China, Hong Kong SAR',
       'China, Macao SAR', 'China, Taiwan Province of China',
       "Dem. People's Republic of Korea", 'Japan', 'Mongolia',
       'South Korea', 'South-Eastern Asia', 'Brunei', 'Cambodia',
       'Indonesia', 'Laos', 'Malaysia', 'Myanmar', 'Philippines',
       'Singapore', 'Thailand', 'Timor', 'Vietnam', ' Caribbean',
       'Anguilla', 'Antigua and Barbuda', 'Aruba', 'Bahamas', 'Barbados',
       'Bonaire, Sint Eustatius and Saba', 'British Virgin Islands',
       'Cayman Islands', 'Cuba', 'Curaçao', 'Dominica',
       'Dominican Republic', 'Grenada', 'Guadeloupe', 'Haiti', 'Jamaica',
       'Martinique', 'Montserrat', 'Puerto Rico', 'Saint Barthélemy',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Martin (French part)', 'Saint Vincent and the Grenadines',
       'Sint Maarten (Dutch part)', 'Trinidad and Tobago',
       'Turks and Caicos Islands', 'United States Virgin Islands',
       'Central America', 'Belize', 'Costa Rica', 'El Salvador',
       'Guatemala', 'Honduras', 'Mexico', 'Nicaragua', 'Panama',
       ' South America', 'Argentina', 'Bolivia', 'Brazil', 'Chile',
       'Colombia', 'Ecuador', 'Falkland Islands (Malvinas)',
       'French Guiana', 'Guyana', 'Paraguay', 'Peru', 'Suriname',
       'Uruguay', 'Venezuela', 'Australia/New Zealand', 'Australia',
       'New Zealand', 'Oceania (excluding Australia and New Zealand)',
       'Melanesia', 'Fiji', 'New Caledonia', 'Papua New Guinea',
       'Solomon Islands', 'Vanuatu', ' Micronesia', 'Guam', 'Kiribati',
       'Marshall Islands', 'Micronesia (country)', 'Nauru',
       'Northern Mariana Islands', 'Palau', 'Polynesia', 'American Samoa',
       'Cook Islands', 'French Polynesia', 'Niue', 'Samoa', 'Tokelau',
       'Tonga', 'Tuvalu', 'Wallis and Futuna Islands',
       'Europe and Northern America', 'Eastern Europe', 'Belarus',
       'Bulgaria', 'Czech Republic', 'Hungary', 'Poland', 'Moldova',
       'Romania', 'Russia', 'Slovakia', 'Ukraine', 'Northern Europe',
       'ChannelIslands', 'Denmark', 'Estonia', 'Faroe Islands', 'Finland',
       'Iceland', 'Ireland', 'Isle of Man', 'Latvia', 'Lithuania',
       'Norway', 'Sweden', 'United Kingdom', 'Southern Europe', 'Albania',
       'Andorra', 'Bosnia and Herzegovina', 'Croatia', 'Gibraltar',
       'Greece', 'Holy See', 'Italy', 'Malta', 'Montenegro',
       'North Macedonia', 'Portugal', 'San Marino', 'Serbia', 'Slovenia',
       'Spain', 'Western Europe', 'Austria', 'Belgium', 'France',
       'Germany', 'Liechtenstein', 'Luxembourg', 'Monaco', 'Netherlands',
       'Switzerland', 'Bermuda', 'Canada', 'Greenland',
       'Saint Pierre and Miquelon', 'United States'], dtype=object)

After importing and analyzing the population dataset, I realized that its country names were different from my anxiety dataset (for example, one had United States and another had United States of America). I went back into the population dataset to rename all of the countries so that they match (see XXXX).

The population in the population dataset for each country was listed horizontally by year in one row, under columns for each year. However, in the anxiety dataset, the year was a variable and there were rows for each year. Therefore, I melted the population dataset so that it have each year as its own row.

In [19]:
pop_long_df=pop_df.melt(id_vars=['code','Location','Average'])

I then did some evaluations just to make sure everything had transferred correctly.

In [20]:
pop_df['Location'].unique()

array(['World', 'More developed regions', 'Less developed regions',
       'Least developed countries',
       'Less developed regions, excluding least developed countries',
       'Less developed regions, excluding China',
       'Land-locked Developing Countries (LLDC)',
       'Small Island Developing States (SIDS)', 'High-income countries',
       'Middle-income countries', 'Upper-middle-income countries',
       'Lower-middle-income countries', 'Low-income countries',
       'No income group available', 'Africa', 'Asia', 'Europe',
       'Latin America and the Caribbean', 'Northern America', 'Oceania',
       'Sub-Saharan Africa', 'Eastern Africa', 'Burundi', 'Comoros',
       'Djibouti', 'Eritrea', 'Ethiopia', 'Kenya', 'Madagascar', 'Malawi',
       'Mauritius', 'Mayotte', 'Mozambique', 'Réunion', 'Rwanda',
       'Seychelles', 'Somalia', 'South Sudan', 'Uganda', 'Tanzania',
       'Zambia', 'Zimbabwe', ' Middle Africa', 'Angola', 'Cameroon',
       'Central African Republic', 'Chad', 'Congo', 'Equatorial Guinea',
       'Gabon', 'Sao Tome and Principe', 'Southern Africa', 'Botswana',
       'Swaziland', 'Lesotho', 'Namibia', 'South Africa',
       'Western Africa', 'Benin', 'Burkina Faso', 'Cape Verde',
       "Côte d'Ivoire", 'Gambia', 'Ghana', 'Guinea', 'Guinea-Bissau',
       'Liberia', 'Mali', 'Mauritania', 'Niger', 'Nigeria',
       'Saint Helena', 'Senegal', 'Sierra Leone', 'Togo',
       'Northern Africa and Western Asia', ' Northern Africa', 'Algeria',
       'Egypt', 'Libya', 'Morocco', 'Sudan', 'Tunisia', 'Western Sahara',
       'Western Asia', 'Armenia', 'Azerbaijan', 'Bahrain', 'Cyprus',
       'Georgia', 'Iraq', 'Israel', 'Jordan', 'Kuwait', 'Lebanon', 'Oman',
       'Qatar', 'Saudi Arabia', 'Palestine', 'Syria', 'Turkey',
       'United Arab Emirates', 'Yemen', 'Central and Southern Asia',
       ' Central Asia', 'Kazakhstan', 'Kyrgyzstan', 'Tajikistan',
       'Turkmenistan', 'Uzbekistan', 'Southern Asia', 'Afghanistan',
       'Bangladesh', 'Bhutan', 'India', 'Iran', 'Maldives', 'Nepal',
       'Pakistan', 'Sri Lanka', 'Eastern and South-Eastern Asia',
       'Eastern Asia', 'China', 'China, Hong Kong SAR',
       'China, Macao SAR', 'China, Taiwan Province of China',
       "Dem. People's Republic of Korea", 'Japan', 'Mongolia',
       'South Korea', 'South-Eastern Asia', 'Brunei', 'Cambodia',
       'Indonesia', 'Laos', 'Malaysia', 'Myanmar', 'Philippines',
       'Singapore', 'Thailand', 'Timor', 'Vietnam', ' Caribbean',
       'Anguilla', 'Antigua and Barbuda', 'Aruba', 'Bahamas', 'Barbados',
       'Bonaire, Sint Eustatius and Saba', 'British Virgin Islands',
       'Cayman Islands', 'Cuba', 'Curaçao', 'Dominica',
       'Dominican Republic', 'Grenada', 'Guadeloupe', 'Haiti', 'Jamaica',
       'Martinique', 'Montserrat', 'Puerto Rico', 'Saint Barthélemy',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Martin (French part)', 'Saint Vincent and the Grenadines',
       'Sint Maarten (Dutch part)', 'Trinidad and Tobago',
       'Turks and Caicos Islands', 'United States Virgin Islands',
       'Central America', 'Belize', 'Costa Rica', 'El Salvador',
       'Guatemala', 'Honduras', 'Mexico', 'Nicaragua', 'Panama',
       ' South America', 'Argentina', 'Bolivia', 'Brazil', 'Chile',
       'Colombia', 'Ecuador', 'Falkland Islands (Malvinas)',
       'French Guiana', 'Guyana', 'Paraguay', 'Peru', 'Suriname',
       'Uruguay', 'Venezuela', 'Australia/New Zealand', 'Australia',
       'New Zealand', 'Oceania (excluding Australia and New Zealand)',
       'Melanesia', 'Fiji', 'New Caledonia', 'Papua New Guinea',
       'Solomon Islands', 'Vanuatu', ' Micronesia', 'Guam', 'Kiribati',
       'Marshall Islands', 'Micronesia (country)', 'Nauru',
       'Northern Mariana Islands', 'Palau', 'Polynesia', 'American Samoa',
       'Cook Islands', 'French Polynesia', 'Niue', 'Samoa', 'Tokelau',
       'Tonga', 'Tuvalu', 'Wallis and Futuna Islands',
       'Europe and Northern America', 'Eastern Europe', 'Belarus',
       'Bulgaria', 'Czech Republic', 'Hungary', 'Poland', 'Moldova',
       'Romania', 'Russia', 'Slovakia', 'Ukraine', 'Northern Europe',
       'ChannelIslands', 'Denmark', 'Estonia', 'Faroe Islands', 'Finland',
       'Iceland', 'Ireland', 'Isle of Man', 'Latvia', 'Lithuania',
       'Norway', 'Sweden', 'United Kingdom', 'Southern Europe', 'Albania',
       'Andorra', 'Bosnia and Herzegovina', 'Croatia', 'Gibraltar',
       'Greece', 'Holy See', 'Italy', 'Malta', 'Montenegro',
       'North Macedonia', 'Portugal', 'San Marino', 'Serbia', 'Slovenia',
       'Spain', 'Western Europe', 'Austria', 'Belgium', 'France',
       'Germany', 'Liechtenstein', 'Luxembourg', 'Monaco', 'Netherlands',
       'Switzerland', 'Bermuda', 'Canada', 'Greenland',
       'Saint Pierre and Miquelon', 'United States'], dtype=object)

In [21]:
pop_long_df['Location'].value_counts()

Northern America                                 58
Latin America and the Caribbean                  58
Europe                                           58
Congo                                            58
Dominican Republic                               29
 Middle Africa                                   29
Marshall Islands                                 29
Trinidad and Tobago                              29
Namibia                                          29
Colombia                                         29
United States Virgin Islands                     29
Northern Africa and Western Asia                 29
Hungary                                          29
Kazakhstan                                       29
China, Taiwan Province of China                  29
Nicaragua                                        29
Least developed countries                        29
Timor                                            29
Bangladesh                                       29
Oceania (excluding Australia and New Zealand)    29
Moldova                                          29
Georgia                                          29
Eastern and South-Eastern Asia                   29
Samoa                                            29
Thailand                                         29
Bermuda                                          29
Puerto Rico                                      29
Europe and Northern America                      29
Anguilla                                         29
World                                            29
                                                 ..
Liechtenstein                                    29
Montenegro                                       29
Curaçao                                          29
Bahamas                                          29
Rwanda                                           29
Tonga                                            29
China                                            29
Paraguay                                         29
Lebanon                                          29
United States                                    29
Libya                                            29
Mali                                             29
Algeria                                          29
Land-locked Developing Countries (LLDC)          29
Burundi                                          29
India                                            29
China, Hong Kong SAR                             29
Poland                                           29
Small Island Developing States (SIDS)            29
Zambia                                           29
Kenya                                            29
Mauritania                                       29
Serbia                                           29
Philippines                                      29
Bhutan                                           29
Middle-income countries                          29
Sub-Saharan Africa                               29
Bulgaria                                         29
Uganda                                           29
Angola                                           29
Name: Location, Length: 281, dtype: int64

In [22]:
29*285

8265

In [23]:
pop_long_df['Location'].unique()

array(['World', 'More developed regions', 'Less developed regions',
       'Least developed countries',
       'Less developed regions, excluding least developed countries',
       'Less developed regions, excluding China',
       'Land-locked Developing Countries (LLDC)',
       'Small Island Developing States (SIDS)', 'High-income countries',
       'Middle-income countries', 'Upper-middle-income countries',
       'Lower-middle-income countries', 'Low-income countries',
       'No income group available', 'Africa', 'Asia', 'Europe',
       'Latin America and the Caribbean', 'Northern America', 'Oceania',
       'Sub-Saharan Africa', 'Eastern Africa', 'Burundi', 'Comoros',
       'Djibouti', 'Eritrea', 'Ethiopia', 'Kenya', 'Madagascar', 'Malawi',
       'Mauritius', 'Mayotte', 'Mozambique', 'Réunion', 'Rwanda',
       'Seychelles', 'Somalia', 'South Sudan', 'Uganda', 'Tanzania',
       'Zambia', 'Zimbabwe', ' Middle Africa', 'Angola', 'Cameroon',
       'Central African Republic', 'Chad', 'Congo', 'Equatorial Guinea',
       'Gabon', 'Sao Tome and Principe', 'Southern Africa', 'Botswana',
       'Swaziland', 'Lesotho', 'Namibia', 'South Africa',
       'Western Africa', 'Benin', 'Burkina Faso', 'Cape Verde',
       "Côte d'Ivoire", 'Gambia', 'Ghana', 'Guinea', 'Guinea-Bissau',
       'Liberia', 'Mali', 'Mauritania', 'Niger', 'Nigeria',
       'Saint Helena', 'Senegal', 'Sierra Leone', 'Togo',
       'Northern Africa and Western Asia', ' Northern Africa', 'Algeria',
       'Egypt', 'Libya', 'Morocco', 'Sudan', 'Tunisia', 'Western Sahara',
       'Western Asia', 'Armenia', 'Azerbaijan', 'Bahrain', 'Cyprus',
       'Georgia', 'Iraq', 'Israel', 'Jordan', 'Kuwait', 'Lebanon', 'Oman',
       'Qatar', 'Saudi Arabia', 'Palestine', 'Syria', 'Turkey',
       'United Arab Emirates', 'Yemen', 'Central and Southern Asia',
       ' Central Asia', 'Kazakhstan', 'Kyrgyzstan', 'Tajikistan',
       'Turkmenistan', 'Uzbekistan', 'Southern Asia', 'Afghanistan',
       'Bangladesh', 'Bhutan', 'India', 'Iran', 'Maldives', 'Nepal',
       'Pakistan', 'Sri Lanka', 'Eastern and South-Eastern Asia',
       'Eastern Asia', 'China', 'China, Hong Kong SAR',
       'China, Macao SAR', 'China, Taiwan Province of China',
       "Dem. People's Republic of Korea", 'Japan', 'Mongolia',
       'South Korea', 'South-Eastern Asia', 'Brunei', 'Cambodia',
       'Indonesia', 'Laos', 'Malaysia', 'Myanmar', 'Philippines',
       'Singapore', 'Thailand', 'Timor', 'Vietnam', ' Caribbean',
       'Anguilla', 'Antigua and Barbuda', 'Aruba', 'Bahamas', 'Barbados',
       'Bonaire, Sint Eustatius and Saba', 'British Virgin Islands',
       'Cayman Islands', 'Cuba', 'Curaçao', 'Dominica',
       'Dominican Republic', 'Grenada', 'Guadeloupe', 'Haiti', 'Jamaica',
       'Martinique', 'Montserrat', 'Puerto Rico', 'Saint Barthélemy',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Martin (French part)', 'Saint Vincent and the Grenadines',
       'Sint Maarten (Dutch part)', 'Trinidad and Tobago',
       'Turks and Caicos Islands', 'United States Virgin Islands',
       'Central America', 'Belize', 'Costa Rica', 'El Salvador',
       'Guatemala', 'Honduras', 'Mexico', 'Nicaragua', 'Panama',
       ' South America', 'Argentina', 'Bolivia', 'Brazil', 'Chile',
       'Colombia', 'Ecuador', 'Falkland Islands (Malvinas)',
       'French Guiana', 'Guyana', 'Paraguay', 'Peru', 'Suriname',
       'Uruguay', 'Venezuela', 'Australia/New Zealand', 'Australia',
       'New Zealand', 'Oceania (excluding Australia and New Zealand)',
       'Melanesia', 'Fiji', 'New Caledonia', 'Papua New Guinea',
       'Solomon Islands', 'Vanuatu', ' Micronesia', 'Guam', 'Kiribati',
       'Marshall Islands', 'Micronesia (country)', 'Nauru',
       'Northern Mariana Islands', 'Palau', 'Polynesia', 'American Samoa',
       'Cook Islands', 'French Polynesia', 'Niue', 'Samoa', 'Tokelau',
       'Tonga', 'Tuvalu', 'Wallis and Futuna Islands',
       'Europe and Northern America', 'Eastern Europe', 'Belarus',
       'Bulgaria', 'Czech Republic', 'Hungary', 'Poland', 'Moldova',
       'Romania', 'Russia', 'Slovakia', 'Ukraine', 'Northern Europe',
       'ChannelIslands', 'Denmark', 'Estonia', 'Faroe Islands', 'Finland',
       'Iceland', 'Ireland', 'Isle of Man', 'Latvia', 'Lithuania',
       'Norway', 'Sweden', 'United Kingdom', 'Southern Europe', 'Albania',
       'Andorra', 'Bosnia and Herzegovina', 'Croatia', 'Gibraltar',
       'Greece', 'Holy See', 'Italy', 'Malta', 'Montenegro',
       'North Macedonia', 'Portugal', 'San Marino', 'Serbia', 'Slovenia',
       'Spain', 'Western Europe', 'Austria', 'Belgium', 'France',
       'Germany', 'Liechtenstein', 'Luxembourg', 'Monaco', 'Netherlands',
       'Switzerland', 'Bermuda', 'Canada', 'Greenland',
       'Saint Pierre and Miquelon', 'United States'], dtype=object)

I converted the names of years in the population dataset from strings to integers.

In [24]:
pop_long_df['variable']=pop_long_df['variable'].astype('int')

I was finally able to merge my anxiety dataset with the population, and found that I successfully merged it with 189 of the geographic entities.

In [25]:
ap_df = merged_df.merge(pop_long_df, left_on=['Year', 'Entity'], right_on=['variable', 'Location'])
ap_df['Entity'].nunique()

189

In [26]:
pop_long_df['Location'].unique()

array(['World', 'More developed regions', 'Less developed regions',
       'Least developed countries',
       'Less developed regions, excluding least developed countries',
       'Less developed regions, excluding China',
       'Land-locked Developing Countries (LLDC)',
       'Small Island Developing States (SIDS)', 'High-income countries',
       'Middle-income countries', 'Upper-middle-income countries',
       'Lower-middle-income countries', 'Low-income countries',
       'No income group available', 'Africa', 'Asia', 'Europe',
       'Latin America and the Caribbean', 'Northern America', 'Oceania',
       'Sub-Saharan Africa', 'Eastern Africa', 'Burundi', 'Comoros',
       'Djibouti', 'Eritrea', 'Ethiopia', 'Kenya', 'Madagascar', 'Malawi',
       'Mauritius', 'Mayotte', 'Mozambique', 'Réunion', 'Rwanda',
       'Seychelles', 'Somalia', 'South Sudan', 'Uganda', 'Tanzania',
       'Zambia', 'Zimbabwe', ' Middle Africa', 'Angola', 'Cameroon',
       'Central African Republic', 'Chad', 'Congo', 'Equatorial Guinea',
       'Gabon', 'Sao Tome and Principe', 'Southern Africa', 'Botswana',
       'Swaziland', 'Lesotho', 'Namibia', 'South Africa',
       'Western Africa', 'Benin', 'Burkina Faso', 'Cape Verde',
       "Côte d'Ivoire", 'Gambia', 'Ghana', 'Guinea', 'Guinea-Bissau',
       'Liberia', 'Mali', 'Mauritania', 'Niger', 'Nigeria',
       'Saint Helena', 'Senegal', 'Sierra Leone', 'Togo',
       'Northern Africa and Western Asia', ' Northern Africa', 'Algeria',
       'Egypt', 'Libya', 'Morocco', 'Sudan', 'Tunisia', 'Western Sahara',
       'Western Asia', 'Armenia', 'Azerbaijan', 'Bahrain', 'Cyprus',
       'Georgia', 'Iraq', 'Israel', 'Jordan', 'Kuwait', 'Lebanon', 'Oman',
       'Qatar', 'Saudi Arabia', 'Palestine', 'Syria', 'Turkey',
       'United Arab Emirates', 'Yemen', 'Central and Southern Asia',
       ' Central Asia', 'Kazakhstan', 'Kyrgyzstan', 'Tajikistan',
       'Turkmenistan', 'Uzbekistan', 'Southern Asia', 'Afghanistan',
       'Bangladesh', 'Bhutan', 'India', 'Iran', 'Maldives', 'Nepal',
       'Pakistan', 'Sri Lanka', 'Eastern and South-Eastern Asia',
       'Eastern Asia', 'China', 'China, Hong Kong SAR',
       'China, Macao SAR', 'China, Taiwan Province of China',
       "Dem. People's Republic of Korea", 'Japan', 'Mongolia',
       'South Korea', 'South-Eastern Asia', 'Brunei', 'Cambodia',
       'Indonesia', 'Laos', 'Malaysia', 'Myanmar', 'Philippines',
       'Singapore', 'Thailand', 'Timor', 'Vietnam', ' Caribbean',
       'Anguilla', 'Antigua and Barbuda', 'Aruba', 'Bahamas', 'Barbados',
       'Bonaire, Sint Eustatius and Saba', 'British Virgin Islands',
       'Cayman Islands', 'Cuba', 'Curaçao', 'Dominica',
       'Dominican Republic', 'Grenada', 'Guadeloupe', 'Haiti', 'Jamaica',
       'Martinique', 'Montserrat', 'Puerto Rico', 'Saint Barthélemy',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Martin (French part)', 'Saint Vincent and the Grenadines',
       'Sint Maarten (Dutch part)', 'Trinidad and Tobago',
       'Turks and Caicos Islands', 'United States Virgin Islands',
       'Central America', 'Belize', 'Costa Rica', 'El Salvador',
       'Guatemala', 'Honduras', 'Mexico', 'Nicaragua', 'Panama',
       ' South America', 'Argentina', 'Bolivia', 'Brazil', 'Chile',
       'Colombia', 'Ecuador', 'Falkland Islands (Malvinas)',
       'French Guiana', 'Guyana', 'Paraguay', 'Peru', 'Suriname',
       'Uruguay', 'Venezuela', 'Australia/New Zealand', 'Australia',
       'New Zealand', 'Oceania (excluding Australia and New Zealand)',
       'Melanesia', 'Fiji', 'New Caledonia', 'Papua New Guinea',
       'Solomon Islands', 'Vanuatu', ' Micronesia', 'Guam', 'Kiribati',
       'Marshall Islands', 'Micronesia (country)', 'Nauru',
       'Northern Mariana Islands', 'Palau', 'Polynesia', 'American Samoa',
       'Cook Islands', 'French Polynesia', 'Niue', 'Samoa', 'Tokelau',
       'Tonga', 'Tuvalu', 'Wallis and Futuna Islands',
       'Europe and Northern America', 'Eastern Europe', 'Belarus',
       'Bulgaria', 'Czech Republic', 'Hungary', 'Poland', 'Moldova',
       'Romania', 'Russia', 'Slovakia', 'Ukraine', 'Northern Europe',
       'ChannelIslands', 'Denmark', 'Estonia', 'Faroe Islands', 'Finland',
       'Iceland', 'Ireland', 'Isle of Man', 'Latvia', 'Lithuania',
       'Norway', 'Sweden', 'United Kingdom', 'Southern Europe', 'Albania',
       'Andorra', 'Bosnia and Herzegovina', 'Croatia', 'Gibraltar',
       'Greece', 'Holy See', 'Italy', 'Malta', 'Montenegro',
       'North Macedonia', 'Portugal', 'San Marino', 'Serbia', 'Slovenia',
       'Spain', 'Western Europe', 'Austria', 'Belgium', 'France',
       'Germany', 'Liechtenstein', 'Luxembourg', 'Monaco', 'Netherlands',
       'Switzerland', 'Bermuda', 'Canada', 'Greenland',
       'Saint Pierre and Miquelon', 'United States'], dtype=object)

I renamed the population column.

In [27]:
ap_df.rename(columns={'value' : 'Population'})

,Entity,Code,Year,Anxiety_percent,Unnamed: 0,Country,Region,Continent,code,Location,Average,variable,Population
0,Afghanistan,AFG,1990,4.828830,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,1990,12412.0
1,Afghanistan,AFG,1991,4.829740,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,1991,13299.0
2,Afghanistan,AFG,1992,4.831108,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,1992,14486.0
3,Afghanistan,AFG,1993,4.830864,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,1993,15817.0
4,Afghanistan,AFG,1994,4.829423,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,1994,17076.0
5,Afghanistan,AFG,1995,4.828337,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,1995,18111.0
6,Afghanistan,AFG,1996,4.828083,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,1996,18853.0
7,Afghanistan,AFG,1997,4.827726,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,1997,19357.0
8,Afghanistan,AFG,1998,4.826971,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,1998,19738.0
9,Afghanistan,AFG,1999,4.826413,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,1999,20171.0
10,Afghanistan,AFG,2000,4.827047,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2000,20780.0
11,Afghanistan,AFG,2001,4.831409,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2001,21607.0
12,Afghanistan,AFG,2002,4.838318,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2002,22601.0
13,Afghanistan,AFG,2003,4.845538,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2003,23681.0
14,Afghanistan,AFG,2004,4.851512,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2004,24727.0
15,Afghanistan,AFG,2005,4.854684,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2005,25654.0
16,Afghanistan,AFG,2006,4.856685,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2006,26433.0
17,Afghanistan,AFG,2007,4.858861,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2007,27101.0
18,Afghanistan,AFG,2008,4.860437,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2008,27722.0
19,Afghanistan,AFG,2009,4.861533,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2009,28395.0
20,Afghanistan,AFG,2010,4.862777,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2010,29186.0
21,Afghanistan,AFG,2011,4.864773,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2011,30117.0
22,Afghanistan,AFG,2012,4.867283,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2012,31161.0
23,Afghanistan,AFG,2013,4.869701,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2013,32270.0
24,Afghanistan,AFG,2014,4.872256,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2014,33371.0
25,Afghanistan,AFG,2015,4.875201,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2015,34414.0
26,Afghanistan,AFG,2016,4.878875,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2016,35383.0
27,Afghanistan,AFG,2017,4.882481,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2017,36296.0
28,Albania,ALB,1990,3.327587,2,Albania,Southern Europe,Europe,8,Albania,3055.275862,1990,3286.0
29,Albania,ALB,1991,3.330348,2,Albania,Southern Europe,Europe,8,Albania,3055.275862,1991,3280.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5290,Zambia,ZMB,2016,3.592016,247,Zambia,Eastern Africa,Africa,894,Zambia,11953.689655,2016,16363.0
5291,Zambia,ZMB,2017,3.599714,247,Zambia,Eastern Africa,Africa,894,Zambia,11953.689655,2017,16854.0
5292,Zimbabwe,ZWE,1990,3.078261,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,1990,10432.0
5293,Zimbabwe,ZWE,1991,3.081906,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,1991,10681.0
5294,Zimbabwe,ZWE,1992,3.085368,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,1992,10901.0
5295,Zimbabwe,ZWE,1993,3.088568,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,1993,11093.0
5296,Zimbabwe,ZWE,1994,3.091593,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,1994,11262.0
5297,Zimbabwe,ZWE,1995,3.094271,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,1995,11411.0
5298,Zimbabwe,ZWE,1996,3.096630,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,1996,11541.0
5299,Zimbabwe,ZWE,1997,3.098486,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,1997,11653.0
5300,Zimbabwe,ZWE,1998,3.099782,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,1998,11747.0
5301,Zimbabwe,ZWE,1999,3.100378,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,1999,11823.0
5302,Zimbabwe,ZWE,2000,3.100264,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2000,11881.0
5303,Zimbabwe,ZWE,2001,3.098659,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2001,11924.0
5304,Zimbabwe,ZWE,2002,3.095492,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2002,11954.0
5305,Zimbabwe,ZWE,2003,3.091844,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2003,11982.0
5306,Zimbabwe,ZWE,2004,3.088682,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2004,12020.0
5307,Zimbabwe,ZWE,2005,3.086927,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2005,12077.0
5308,Zimbabwe,ZWE,2006,3.085964,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2006,12155.0
5309,Zimbabwe,ZWE,2007,3.084816,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2007,12256.0
5310,Zimbabwe,ZWE,2008,3.083928,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2008,12380.0
5311,Zimbabwe,ZWE,2009,3.083515,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2009,12527.0
5312,Zimbabwe,ZWE,2010,3.083865,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2010,12698.0
5313,Zimbabwe,ZWE,2011,3.085099,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2011,12894.0
5314,Zimbabwe,ZWE,2012,3.087210,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2012,13115.0
5315,Zimbabwe,ZWE,2013,3.090168,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2013,13350.0
5316,Zimbabwe,ZWE,2014,3.093964,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2014,13587.0
5317,Zimbabwe,ZWE,2015,3.098687,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2015,13815.0
5318,Zimbabwe,ZWE,2016,3.104294,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2016,14030.0
5319,Zimbabwe,ZWE,2017,3.110926,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2017,14237.0

The population dataset gave the population in thousands. I converted it into its actual numeric amount.

In [28]:
ap_df['Population']=ap_df['value']*1000

In [29]:
ap_df.head()

,Entity,Code,Year,Anxiety_percent,Unnamed: 0,Country,Region,Continent,code,Location,Average,variable,value,Population
0,Afghanistan,AFG,1990,4.828830,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.62069,1990,12412.0,12412000.0
1,Afghanistan,AFG,1991,4.829740,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.62069,1991,13299.0,13299000.0
2,Afghanistan,AFG,1992,4.831108,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.62069,1992,14486.0,14486000.0
3,Afghanistan,AFG,1993,4.830864,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.62069,1993,15817.0,15817000.0
4,Afghanistan,AFG,1994,4.829423,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.62069,1994,17076.0,17076000.0

I created a new variable for each row that had the number of people in the population who have anxiety.

In [30]:
ap_df['Anxiety_population']=ap_df['Anxiety_percent']/100 * ap_df['Population']
ap_df.head()

,Entity,Code,Year,Anxiety_percent,Unnamed: 0,Country,Region,Continent,code,Location,Average,variable,value,Population,Anxiety_population
0,Afghanistan,AFG,1990,4.828830,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.62069,1990,12412.0,12412000.0,599354.342985
1,Afghanistan,AFG,1991,4.829740,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.62069,1991,13299.0,13299000.0,642307.172127
2,Afghanistan,AFG,1992,4.831108,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.62069,1992,14486.0,14486000.0,699834.357854
3,Afghanistan,AFG,1993,4.830864,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.62069,1993,15817.0,15817000.0,764097.693301
4,Afghanistan,AFG,1994,4.829423,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.62069,1994,17076.0,17076000.0,824672.301042

I then dropped some duplicated datasets, renamed some columns, and exported the new cleaned anxiety dataset to a CSV.

In [31]:
ap2_df = ap_df.drop(['Country', 'Location','value', 'variable', 'code'], axis=1)

In [32]:
ap3_df = ap2_df.rename(columns={'Average':'Average_pop'})

In [33]:
ap3_df.to_csv('../data/Cleaned/anxiety_clean', index=False)

I also imported the new, long population dataset to a CSV.

In [34]:
pop_long_df.to_csv('../data/Cleaned/world_pop_long', index=False)

In [35]:
ap_df

,Entity,Code,Year,Anxiety_percent,Unnamed: 0,Country,Region,Continent,code,Location,Average,variable,value,Population,Anxiety_population
0,Afghanistan,AFG,1990,4.828830,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,1990,12412.0,12412000.0,5.993543e+05
1,Afghanistan,AFG,1991,4.829740,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,1991,13299.0,13299000.0,6.423072e+05
2,Afghanistan,AFG,1992,4.831108,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,1992,14486.0,14486000.0,6.998344e+05
3,Afghanistan,AFG,1993,4.830864,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,1993,15817.0,15817000.0,7.640977e+05
4,Afghanistan,AFG,1994,4.829423,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,1994,17076.0,17076000.0,8.246723e+05
5,Afghanistan,AFG,1995,4.828337,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,1995,18111.0,18111000.0,8.744602e+05
6,Afghanistan,AFG,1996,4.828083,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,1996,18853.0,18853000.0,9.102385e+05
7,Afghanistan,AFG,1997,4.827726,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,1997,19357.0,19357000.0,9.345029e+05
8,Afghanistan,AFG,1998,4.826971,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,1998,19738.0,19738000.0,9.527476e+05
9,Afghanistan,AFG,1999,4.826413,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,1999,20171.0,20171000.0,9.735357e+05
10,Afghanistan,AFG,2000,4.827047,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2000,20780.0,20780000.0,1.003060e+06
11,Afghanistan,AFG,2001,4.831409,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2001,21607.0,21607000.0,1.043923e+06
12,Afghanistan,AFG,2002,4.838318,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2002,22601.0,22601000.0,1.093508e+06
13,Afghanistan,AFG,2003,4.845538,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2003,23681.0,23681000.0,1.147472e+06
14,Afghanistan,AFG,2004,4.851512,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2004,24727.0,24727000.0,1.199633e+06
15,Afghanistan,AFG,2005,4.854684,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2005,25654.0,25654000.0,1.245421e+06
16,Afghanistan,AFG,2006,4.856685,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2006,26433.0,26433000.0,1.283767e+06
17,Afghanistan,AFG,2007,4.858861,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2007,27101.0,27101000.0,1.316800e+06
18,Afghanistan,AFG,2008,4.860437,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2008,27722.0,27722000.0,1.347410e+06
19,Afghanistan,AFG,2009,4.861533,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2009,28395.0,28395000.0,1.380432e+06
20,Afghanistan,AFG,2010,4.862777,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2010,29186.0,29186000.0,1.419250e+06
21,Afghanistan,AFG,2011,4.864773,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2011,30117.0,30117000.0,1.465124e+06
22,Afghanistan,AFG,2012,4.867283,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2012,31161.0,31161000.0,1.516694e+06
23,Afghanistan,AFG,2013,4.869701,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2013,32270.0,32270000.0,1.571453e+06
24,Afghanistan,AFG,2014,4.872256,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2014,33371.0,33371000.0,1.625921e+06
25,Afghanistan,AFG,2015,4.875201,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2015,34414.0,34414000.0,1.677752e+06
26,Afghanistan,AFG,2016,4.878875,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2016,35383.0,35383000.0,1.726292e+06
27,Afghanistan,AFG,2017,4.882481,0,Afghanistan,Southern Asia,Asia,4,Afghanistan,24737.620690,2017,36296.0,36296000.0,1.772145e+06
28,Albania,ALB,1990,3.327587,2,Albania,Southern Europe,Europe,8,Albania,3055.275862,1990,3286.0,3286000.0,1.093445e+05
29,Albania,ALB,1991,3.330348,2,Albania,Southern Europe,Europe,8,Albania,3055.275862,1991,3280.0,3280000.0,1.092354e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5290,Zambia,ZMB,2016,3.592016,247,Zambia,Eastern Africa,Africa,894,Zambia,11953.689655,2016,16363.0,16363000.0,5.877615e+05
5291,Zambia,ZMB,2017,3.599714,247,Zambia,Eastern Africa,Africa,894,Zambia,11953.689655,2017,16854.0,16854000.0,6.066958e+05
5292,Zimbabwe,ZWE,1990,3.078261,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,1990,10432.0,10432000.0,3.211242e+05
5293,Zimbabwe,ZWE,1991,3.081906,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,1991,10681.0,10681000.0,3.291784e+05
5294,Zimbabwe,ZWE,1992,3.085368,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,1992,10901.0,10901000.0,3.363360e+05
5295,Zimbabwe,ZWE,1993,3.088568,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,1993,11093.0,11093000.0,3.426148e+05
5296,Zimbabwe,ZWE,1994,3.091593,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,1994,11262.0,11262000.0,3.481752e+05
5297,Zimbabwe,ZWE,1995,3.094271,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,1995,11411.0,11411000.0,3.530872e+05
5298,Zimbabwe,ZWE,1996,3.096630,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,1996,11541.0,11541000.0,3.573820e+05
5299,Zimbabwe,ZWE,1997,3.098486,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,1997,11653.0,11653000.0,3.610666e+05
5300,Zimbabwe,ZWE,1998,3.099782,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,1998,11747.0,11747000.0,3.641314e+05
5301,Zimbabwe,ZWE,1999,3.100378,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,1999,11823.0,11823000.0,3.665577e+05
5302,Zimbabwe,ZWE,2000,3.100264,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2000,11881.0,11881000.0,3.683423e+05
5303,Zimbabwe,ZWE,2001,3.098659,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2001,11924.0,11924000.0,3.694841e+05
5304,Zimbabwe,ZWE,2002,3.095492,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2002,11954.0,11954000.0,3.700352e+05
5305,Zimbabwe,ZWE,2003,3.091844,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2003,11982.0,11982000.0,3.704648e+05
5306,Zimbabwe,ZWE,2004,3.088682,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2004,12020.0,12020000.0,3.712596e+05
5307,Zimbabwe,ZWE,2005,3.086927,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2005,12077.0,12077000.0,3.728082e+05
5308,Zimbabwe,ZWE,2006,3.085964,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2006,12155.0,12155000.0,3.750989e+05
5309,Zimbabwe,ZWE,2007,3.084816,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2007,12256.0,12256000.0,3.780750e+05
5310,Zimbabwe,ZWE,2008,3.083928,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2008,12380.0,12380000.0,3.817903e+05
5311,Zimbabwe,ZWE,2009,3.083515,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2009,12527.0,12527000.0,3.862719e+05
5312,Zimbabwe,ZWE,2010,3.083865,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2010,12698.0,12698000.0,3.915892e+05
5313,Zimbabwe,ZWE,2011,3.085099,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2011,12894.0,12894000.0,3.977926e+05
5314,Zimbabwe,ZWE,2012,3.087210,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2012,13115.0,13115000.0,4.048876e+05
5315,Zimbabwe,ZWE,2013,3.090168,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2013,13350.0,13350000.0,4.125375e+05
5316,Zimbabwe,ZWE,2014,3.093964,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2014,13587.0,13587000.0,4.203769e+05
5317,Zimbabwe,ZWE,2015,3.098687,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2015,13815.0,13815000.0,4.280836e+05
5318,Zimbabwe,ZWE,2016,3.104294,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2016,14030.0,14030000.0,4.355325e+05
5319,Zimbabwe,ZWE,2017,3.110926,248,Zimbabwe,Eastern Africa,Africa,716,Zimbabwe,12271.206897,2017,14237.0,14237000.0,4.429025e+05