The purpose of this notebook is to merge together all of my datasets to manipulate and compare variables.

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import plotly_express as px
import math
import geopandas as gpd
from shapely.geometry import Point
import json

In [2]:
anxiety_df = pd.read_csv('../data/Cleaned/anxiety_clean')
anxiety_df['Entity'].nunique()

189

In [3]:
countries_df = pd.read_csv('../data/Cleaned/countries.geojson')
countries_df.columns

Index(['Unnamed: 0', 'ADMIN', 'ISO_A3', 'ISO_A2', 'geometry'], dtype='object')

In [4]:
depression_df = pd.read_csv('../data/Cleaned/depression_clean')
depression_df['Entity'].nunique()

189

I merged together my anxiety and depression datasets.

In [5]:
ad_df = anxiety_df.merge(depression_df, left_on=['Entity', 'Year'], right_on=['Entity', 'Year'])

In [6]:
anxiety_df.shape

(5320, 10)

In [7]:
depression_df.shape

(5320, 10)

In [8]:
ad_df.shape

(5376, 18)

No data was lost in the merge. I then dropped an irrelevant column.

In [9]:
ad_df.drop(['Average'], axis=1)

,Entity,Code_x,Year,Anxiety_percent,Unnamed: 0_x,Region_x,Continent_x,Average_pop,Population_x,Anxiety_population,Code_y,Depression_percent,Unnamed: 0_y,Region_y,Continent_y,Population_y,Depression_population
0,Afghanistan,AFG,1990,4.828830,0,Southern Asia,Asia,24737.620690,12412000.0,5.993543e+05,AFG,4.071831,0,Southern Asia,Asia,12412000.0,5.053957e+05
1,Afghanistan,AFG,1991,4.829740,0,Southern Asia,Asia,24737.620690,13299000.0,6.423072e+05,AFG,4.079531,0,Southern Asia,Asia,13299000.0,5.425368e+05
2,Afghanistan,AFG,1992,4.831108,0,Southern Asia,Asia,24737.620690,14486000.0,6.998344e+05,AFG,4.088358,0,Southern Asia,Asia,14486000.0,5.922396e+05
3,Afghanistan,AFG,1993,4.830864,0,Southern Asia,Asia,24737.620690,15817000.0,7.640977e+05,AFG,4.096190,0,Southern Asia,Asia,15817000.0,6.478944e+05
4,Afghanistan,AFG,1994,4.829423,0,Southern Asia,Asia,24737.620690,17076000.0,8.246723e+05,AFG,4.099582,0,Southern Asia,Asia,17076000.0,7.000446e+05
5,Afghanistan,AFG,1995,4.828337,0,Southern Asia,Asia,24737.620690,18111000.0,8.744602e+05,AFG,4.104207,0,Southern Asia,Asia,18111000.0,7.433130e+05
6,Afghanistan,AFG,1996,4.828083,0,Southern Asia,Asia,24737.620690,18853000.0,9.102385e+05,AFG,4.107500,0,Southern Asia,Asia,18853000.0,7.743871e+05
7,Afghanistan,AFG,1997,4.827726,0,Southern Asia,Asia,24737.620690,19357000.0,9.345029e+05,AFG,4.110834,0,Southern Asia,Asia,19357000.0,7.957341e+05
8,Afghanistan,AFG,1998,4.826971,0,Southern Asia,Asia,24737.620690,19738000.0,9.527476e+05,AFG,4.114438,0,Southern Asia,Asia,19738000.0,8.121077e+05
9,Afghanistan,AFG,1999,4.826413,0,Southern Asia,Asia,24737.620690,20171000.0,9.735357e+05,AFG,4.117633,0,Southern Asia,Asia,20171000.0,8.305679e+05
10,Afghanistan,AFG,2000,4.827047,0,Southern Asia,Asia,24737.620690,20780000.0,1.003060e+06,AFG,4.118610,0,Southern Asia,Asia,20780000.0,8.558472e+05
11,Afghanistan,AFG,2001,4.831409,0,Southern Asia,Asia,24737.620690,21607000.0,1.043923e+06,AFG,4.121381,0,Southern Asia,Asia,21607000.0,8.905068e+05
12,Afghanistan,AFG,2002,4.838318,0,Southern Asia,Asia,24737.620690,22601000.0,1.093508e+06,AFG,4.124928,0,Southern Asia,Asia,22601000.0,9.322750e+05
13,Afghanistan,AFG,2003,4.845538,0,Southern Asia,Asia,24737.620690,23681000.0,1.147472e+06,AFG,4.125230,0,Southern Asia,Asia,23681000.0,9.768958e+05
14,Afghanistan,AFG,2004,4.851512,0,Southern Asia,Asia,24737.620690,24727000.0,1.199633e+06,AFG,4.126384,0,Southern Asia,Asia,24727000.0,1.020331e+06
15,Afghanistan,AFG,2005,4.854684,0,Southern Asia,Asia,24737.620690,25654000.0,1.245421e+06,AFG,4.126908,0,Southern Asia,Asia,25654000.0,1.058717e+06
16,Afghanistan,AFG,2006,4.856685,0,Southern Asia,Asia,24737.620690,26433000.0,1.283767e+06,AFG,4.128638,0,Southern Asia,Asia,26433000.0,1.091323e+06
17,Afghanistan,AFG,2007,4.858861,0,Southern Asia,Asia,24737.620690,27101000.0,1.316800e+06,AFG,4.129728,0,Southern Asia,Asia,27101000.0,1.119197e+06
18,Afghanistan,AFG,2008,4.860437,0,Southern Asia,Asia,24737.620690,27722000.0,1.347410e+06,AFG,4.129656,0,Southern Asia,Asia,27722000.0,1.144823e+06
19,Afghanistan,AFG,2009,4.861533,0,Southern Asia,Asia,24737.620690,28395000.0,1.380432e+06,AFG,4.129972,0,Southern Asia,Asia,28395000.0,1.172706e+06
20,Afghanistan,AFG,2010,4.862777,0,Southern Asia,Asia,24737.620690,29186000.0,1.419250e+06,AFG,4.130874,0,Southern Asia,Asia,29186000.0,1.205637e+06
21,Afghanistan,AFG,2011,4.864773,0,Southern Asia,Asia,24737.620690,30117000.0,1.465124e+06,AFG,4.130862,0,Southern Asia,Asia,30117000.0,1.244092e+06
22,Afghanistan,AFG,2012,4.867283,0,Southern Asia,Asia,24737.620690,31161000.0,1.516694e+06,AFG,4.132485,0,Southern Asia,Asia,31161000.0,1.287724e+06
23,Afghanistan,AFG,2013,4.869701,0,Southern Asia,Asia,24737.620690,32270000.0,1.571453e+06,AFG,4.134661,0,Southern Asia,Asia,32270000.0,1.334255e+06
24,Afghanistan,AFG,2014,4.872256,0,Southern Asia,Asia,24737.620690,33371000.0,1.625921e+06,AFG,4.133526,0,Southern Asia,Asia,33371000.0,1.379399e+06
25,Afghanistan,AFG,2015,4.875201,0,Southern Asia,Asia,24737.620690,34414000.0,1.677752e+06,AFG,4.135419,0,Southern Asia,Asia,34414000.0,1.423163e+06
26,Afghanistan,AFG,2016,4.878875,0,Southern Asia,Asia,24737.620690,35383000.0,1.726292e+06,AFG,4.135694,0,Southern Asia,Asia,35383000.0,1.463333e+06
27,Afghanistan,AFG,2017,4.882481,0,Southern Asia,Asia,24737.620690,36296000.0,1.772145e+06,AFG,4.136347,0,Southern Asia,Asia,36296000.0,1.501329e+06
28,Albania,ALB,1990,3.327587,2,Southern Europe,Europe,3055.275862,3286000.0,1.093445e+05,ALB,2.139903,2,Southern Europe,Europe,3286000.0,7.031721e+04
29,Albania,ALB,1991,3.330348,2,Southern Europe,Europe,3055.275862,3280000.0,1.092354e+05,ALB,2.141201,2,Southern Europe,Europe,3280000.0,7.023140e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5346,Zambia,ZMB,2016,3.592016,247,Eastern Africa,Africa,11953.689655,16363000.0,5.877615e+05,ZMB,3.608843,247,Eastern Africa,Africa,16363000.0,5.905149e+05
5347,Zambia,ZMB,2017,3.599714,247,Eastern Africa,Africa,11953.689655,16854000.0,6.066958e+05,ZMB,3.641811,247,Eastern Africa,Africa,16854000.0,6.137909e+05
5348,Zimbabwe,ZWE,1990,3.078261,248,Eastern Africa,Africa,12271.206897,10432000.0,3.211242e+05,ZWE,3.040364,248,Eastern Africa,Africa,10432000.0,3.171708e+05
5349,Zimbabwe,ZWE,1991,3.081906,248,Eastern Africa,Africa,12271.206897,10681000.0,3.291784e+05,ZWE,3.060225,248,Eastern Africa,Africa,10681000.0,3.268627e+05
5350,Zimbabwe,ZWE,1992,3.085368,248,Eastern Africa,Africa,12271.206897,10901000.0,3.363360e+05,ZWE,3.077426,248,Eastern Africa,Africa,10901000.0,3.354702e+05
5351,Zimbabwe,ZWE,1993,3.088568,248,Eastern Africa,Africa,12271.206897,11093000.0,3.426148e+05,ZWE,3.089601,248,Eastern Africa,Africa,11093000.0,3.427295e+05
5352,Zimbabwe,ZWE,1994,3.091593,248,Eastern Africa,Africa,12271.206897,11262000.0,3.481752e+05,ZWE,3.100224,248,Eastern Africa,Africa,11262000.0,3.491472e+05
5353,Zimbabwe,ZWE,1995,3.094271,248,Eastern Africa,Africa,12271.206897,11411000.0,3.530872e+05,ZWE,3.107312,248,Eastern Africa,Africa,11411000.0,3.545754e+05
5354,Zimbabwe,ZWE,1996,3.096630,248,Eastern Africa,Africa,12271.206897,11541000.0,3.573820e+05,ZWE,3.105739,248,Eastern Africa,Africa,11541000.0,3.584333e+05
5355,Zimbabwe,ZWE,1997,3.098486,248,Eastern Africa,Africa,12271.206897,11653000.0,3.610666e+05,ZWE,3.094765,248,Eastern Africa,Africa,11653000.0,3.606329e+05
5356,Zimbabwe,ZWE,1998,3.099782,248,Eastern Africa,Africa,12271.206897,11747000.0,3.641314e+05,ZWE,3.083283,248,Eastern Africa,Africa,11747000.0,3.621933e+05
5357,Zimbabwe,ZWE,1999,3.100378,248,Eastern Africa,Africa,12271.206897,11823000.0,3.665577e+05,ZWE,3.074554,248,Eastern Africa,Africa,11823000.0,3.635045e+05
5358,Zimbabwe,ZWE,2000,3.100264,248,Eastern Africa,Africa,12271.206897,11881000.0,3.683423e+05,ZWE,3.069722,248,Eastern Africa,Africa,11881000.0,3.647136e+05
5359,Zimbabwe,ZWE,2001,3.098659,248,Eastern Africa,Africa,12271.206897,11924000.0,3.694841e+05,ZWE,3.072727,248,Eastern Africa,Africa,11924000.0,3.663920e+05
5360,Zimbabwe,ZWE,2002,3.095492,248,Eastern Africa,Africa,12271.206897,11954000.0,3.700352e+05,ZWE,3.080942,248,Eastern Africa,Africa,11954000.0,3.682958e+05
5361,Zimbabwe,ZWE,2003,3.091844,248,Eastern Africa,Africa,12271.206897,11982000.0,3.704648e+05,ZWE,3.089274,248,Eastern Africa,Africa,11982000.0,3.701568e+05
5362,Zimbabwe,ZWE,2004,3.088682,248,Eastern Africa,Africa,12271.206897,12020000.0,3.712596e+05,ZWE,3.096351,248,Eastern Africa,Africa,12020000.0,3.721814e+05
5363,Zimbabwe,ZWE,2005,3.086927,248,Eastern Africa,Africa,12271.206897,12077000.0,3.728082e+05,ZWE,3.102648,248,Eastern Africa,Africa,12077000.0,3.747068e+05
5364,Zimbabwe,ZWE,2006,3.085964,248,Eastern Africa,Africa,12271.206897,12155000.0,3.750989e+05,ZWE,3.104970,248,Eastern Africa,Africa,12155000.0,3.774091e+05
5365,Zimbabwe,ZWE,2007,3.084816,248,Eastern Africa,Africa,12271.206897,12256000.0,3.780750e+05,ZWE,3.104822,248,Eastern Africa,Africa,12256000.0,3.805270e+05
5366,Zimbabwe,ZWE,2008,3.083928,248,Eastern Africa,Africa,12271.206897,12380000.0,3.817903e+05,ZWE,3.103491,248,Eastern Africa,Africa,12380000.0,3.842122e+05
5367,Zimbabwe,ZWE,2009,3.083515,248,Eastern Africa,Africa,12271.206897,12527000.0,3.862719e+05,ZWE,3.102520,248,Eastern Africa,Africa,12527000.0,3.886527e+05
5368,Zimbabwe,ZWE,2010,3.083865,248,Eastern Africa,Africa,12271.206897,12698000.0,3.915892e+05,ZWE,3.105459,248,Eastern Africa,Africa,12698000.0,3.943311e+05
5369,Zimbabwe,ZWE,2011,3.085099,248,Eastern Africa,Africa,12271.206897,12894000.0,3.977926e+05,ZWE,3.109526,248,Eastern Africa,Africa,12894000.0,4.009422e+05
5370,Zimbabwe,ZWE,2012,3.087210,248,Eastern Africa,Africa,12271.206897,13115000.0,4.048876e+05,ZWE,3.118072,248,Eastern Africa,Africa,13115000.0,4.089352e+05
5371,Zimbabwe,ZWE,2013,3.090168,248,Eastern Africa,Africa,12271.206897,13350000.0,4.125375e+05,ZWE,3.128192,248,Eastern Africa,Africa,13350000.0,4.176137e+05
5372,Zimbabwe,ZWE,2014,3.093964,248,Eastern Africa,Africa,12271.206897,13587000.0,4.203769e+05,ZWE,3.140290,248,Eastern Africa,Africa,13587000.0,4.266712e+05
5373,Zimbabwe,ZWE,2015,3.098687,248,Eastern Africa,Africa,12271.206897,13815000.0,4.280836e+05,ZWE,3.155710,248,Eastern Africa,Africa,13815000.0,4.359613e+05
5374,Zimbabwe,ZWE,2016,3.104294,248,Eastern Africa,Africa,12271.206897,14030000.0,4.355325e+05,ZWE,3.174134,248,Eastern Africa,Africa,14030000.0,4.453310e+05
5375,Zimbabwe,ZWE,2017,3.110926,248,Eastern Africa,Africa,12271.206897,14237000.0,4.429025e+05,ZWE,3.192789,248,Eastern Africa,Africa,14237000.0,4.545574e+05

In [10]:
disorders_df = pd.read_csv('../data/Cleaned/disorders_clean')
disorders_df['Country'].nunique()

189

In [11]:
disorders_df.shape

(5320, 10)

I then merged the anxiety-depression dataset with the disorders dataset.

In [12]:
add_df = ad_df.merge(disorders_df, left_on=['Entity', 'Year'], right_on=['Country', 'Year'])

In [13]:
add_df['Entity'].nunique()

189

In [14]:
add_df.columns

Index(['Entity', 'Code_x', 'Year', 'Anxiety_percent', 'Unnamed: 0_x',
       'Region_x', 'Continent_x', 'Average_pop_x', 'Population_x',
       'Anxiety_population', 'Code_y', 'Depression_percent', 'Unnamed: 0_y',
       'Region_y', 'Continent_y', 'Average', 'Population_y',
       'Depression_population', 'Country', 'Code', 'Disorders(%)',
       'Unnamed: 0', 'Region', 'Continent', 'Average_pop_y', 'Population',
       'Disorders_population'],
      dtype='object')

I dropped irrelevant columns.

In [15]:
add2_df = add_df.drop(['Code_y', 'Region_y'], axis=1)

In [16]:
add_df.shape

(5488, 27)

In [17]:
add_df.head()

,Entity,Code_x,Year,Anxiety_percent,Unnamed: 0_x,Region_x,Continent_x,Average_pop_x,Population_x,Anxiety_population,...,Depression_population,Country,Code,Disorders(%),Unnamed: 0,Region,Continent,Average_pop_y,Population,Disorders_population
0,Afghanistan,AFG,1990,4.828830,0,Southern Asia,Asia,24737.62069,12412000.0,599354.342985,...,505395.685697,Afghanistan,AFG,17.553463,0,Southern Asia,Asia,24737.62069,12412000.0,2.178736e+06
1,Afghanistan,AFG,1991,4.829740,0,Southern Asia,Asia,24737.62069,13299000.0,642307.172127,...,542536.819099,Afghanistan,AFG,17.837032,0,Southern Asia,Asia,24737.62069,13299000.0,2.372147e+06
2,Afghanistan,AFG,1992,4.831108,0,Southern Asia,Asia,24737.62069,14486000.0,699834.357854,...,592239.575077,Afghanistan,AFG,18.092542,0,Southern Asia,Asia,24737.62069,14486000.0,2.620886e+06
3,Afghanistan,AFG,1993,4.830864,0,Southern Asia,Asia,24737.62069,15817000.0,764097.693301,...,647894.356027,Afghanistan,AFG,18.294931,0,Southern Asia,Asia,24737.62069,15817000.0,2.893709e+06
4,Afghanistan,AFG,1994,4.829423,0,Southern Asia,Asia,24737.62069,17076000.0,824672.301042,...,700044.550287,Afghanistan,AFG,18.428908,0,Southern Asia,Asia,24737.62069,17076000.0,3.146920e+06

In [18]:
add_df.shape

(5488, 27)

In [19]:
add2_df.drop(['Average'], axis=1)
add2_df.shape

(5488, 25)

In [20]:
add_df.head()

,Entity,Code_x,Year,Anxiety_percent,Unnamed: 0_x,Region_x,Continent_x,Average_pop_x,Population_x,Anxiety_population,...,Depression_population,Country,Code,Disorders(%),Unnamed: 0,Region,Continent,Average_pop_y,Population,Disorders_population
0,Afghanistan,AFG,1990,4.828830,0,Southern Asia,Asia,24737.62069,12412000.0,599354.342985,...,505395.685697,Afghanistan,AFG,17.553463,0,Southern Asia,Asia,24737.62069,12412000.0,2.178736e+06
1,Afghanistan,AFG,1991,4.829740,0,Southern Asia,Asia,24737.62069,13299000.0,642307.172127,...,542536.819099,Afghanistan,AFG,17.837032,0,Southern Asia,Asia,24737.62069,13299000.0,2.372147e+06
2,Afghanistan,AFG,1992,4.831108,0,Southern Asia,Asia,24737.62069,14486000.0,699834.357854,...,592239.575077,Afghanistan,AFG,18.092542,0,Southern Asia,Asia,24737.62069,14486000.0,2.620886e+06
3,Afghanistan,AFG,1993,4.830864,0,Southern Asia,Asia,24737.62069,15817000.0,764097.693301,...,647894.356027,Afghanistan,AFG,18.294931,0,Southern Asia,Asia,24737.62069,15817000.0,2.893709e+06
4,Afghanistan,AFG,1994,4.829423,0,Southern Asia,Asia,24737.62069,17076000.0,824672.301042,...,700044.550287,Afghanistan,AFG,18.428908,0,Southern Asia,Asia,24737.62069,17076000.0,3.146920e+06

I imported the suicide dataset and merged it with the add dataset.

In [21]:
suicide_df = pd.read_csv('../data/Cleaned/suicide-clean')
suicide_df.head()

,Country,Sex,Region,Continent,Year,Suicides_per100000,Average_pop,Population,#suicides
0,Afghanistan,Both sexes,Southern Asia,Asia,2016,4.7,24737.620690,35383000.0,1663.001
1,Albania,Both sexes,Southern Europe,Europe,2016,6.3,3055.275862,2886000.0,181.818
2,Algeria,Both sexes,Northern Africa,Africa,2016,3.2,33273.448276,40551000.0,1297.632
3,Angola,Both sexes,Middle Africa,Africa,2016,4.7,19765.931034,28842000.0,1355.574
4,Antigua and Barbuda,Both sexes,Caribbean,North America,2016,0.5,80.137931,95000.0,0.475

In [22]:
suicide_df.shape

(895, 9)

In [23]:
adds = add_df.merge(suicide_df, left_on=['Entity', 'Year', 'Region', 'Continent', 'Population'], right_on=['Country', 'Year', 'Region', 'Continent', 'Population'])

In [24]:
adds['Entity'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia',
       'Cameroon', 'Canada', 'Cape Verde', 'Central African Republic',
       'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo',
       'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Denmark', 'Djibouti',
       'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador',
       'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia', 'Fiji',
       'Finland', 'France', 'Gabon', 'Gambia', 'Georgia', 'Germany',
       'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea',
       'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hungary',
       'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland',
       'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan',
       'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia',
       'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Lithuania',
       'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives',
       'Mali', 'Malta', 'Mauritania', 'Mauritius', 'Mexico',
       'Micronesia (country)', 'Moldova', 'Mongolia', 'Montenegro',
       'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nepal',
       'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
       'Norway', 'Oman', 'Pakistan', 'Panama', 'Papua New Guinea',
       'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar',
       'Romania', 'Russia', 'Rwanda', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Korea',
       'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname',
       'Swaziland', 'Sweden', 'Switzerland', 'Syria', 'Tajikistan',
       'Tanzania', 'Thailand', 'Timor', 'Togo', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom',
       'United States', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela',
       'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe'], dtype=object)

In [25]:
adds.shape

(925, 32)

In [26]:
adds.columns

Index(['Entity', 'Code_x', 'Year', 'Anxiety_percent', 'Unnamed: 0_x',
       'Region_x', 'Continent_x', 'Average_pop_x', 'Population_x',
       'Anxiety_population', 'Code_y', 'Depression_percent', 'Unnamed: 0_y',
       'Region_y', 'Continent_y', 'Average', 'Population_y',
       'Depression_population', 'Country_x', 'Code', 'Disorders(%)',
       'Unnamed: 0', 'Region', 'Continent', 'Average_pop_y', 'Population',
       'Disorders_population', 'Country_y', 'Sex', 'Suicides_per100000',
       'Average_pop', '#suicides'],
      dtype='object')

In [27]:
add_df['Entity'].nunique()

189

In [28]:
adds['Entity'].nunique()

178

Only 8 countries were lost in this large merge.

In [29]:
adds.shape

(925, 32)

I exported this combination of four datasets into a new CSV.

In [30]:
adds.to_csv('../data/Cleaned/suicideanxietydepressiondisorders', index=False)

In [31]:
adds['Entity'].nunique()

178

I then imported the resources dataset, the least geographically representative one and then I merged it with the previous large one to create the "megaset."

In [32]:
resources_df = pd.read_csv('../data/Cleaned/resources_clean')
resources_df['Country'].nunique()

151

In [33]:
the_megaset = adds.merge(resources_df, left_on=['Entity', 'Year'], right_on=['Country', 'Year'])

In [34]:
the_megaset['Entity'].nunique()

123

In [35]:
the_megaset.columns

Index(['Entity', 'Code_x', 'Year', 'Anxiety_percent', 'Unnamed: 0_x',
       'Region_x', 'Continent_x', 'Average_pop_x', 'Population_x',
       'Anxiety_population', 'Code_y', 'Depression_percent', 'Unnamed: 0_y',
       'Region_y', 'Continent_y', 'Average', 'Population_y',
       'Depression_population', 'Country_x', 'Code', 'Disorders(%)',
       'Unnamed: 0', 'Region_x', 'Continent_x', 'Average_pop_y',
       'Population_x', 'Disorders_population', 'Country_y', 'Sex',
       'Suicides_per100000', 'Average_pop', '#suicides', 'Country',
       'Psychiatrists_per100000', 'Nurses_per100000',
       'Social_workers_per100000', 'Psychologists_per100000', 'Region_y',
       'Continent_y', 'Population_y', '#psychiatrists', '#nurses',
       '#social_workers', '#psychologists', 'Total_resources'],
      dtype='object')

I then dropped irrelevant columns and renamed the relevant ones.

In [36]:
the_megaset2 = the_megaset.drop(['Average', 'Average_pop_y', 'Country_x', 'Country_y', 'Country', 'Unnamed: 0_y', 'Code_y', 'Unnamed: 0_x'], axis=1)

In [37]:
the_megaset3 = the_megaset2.rename(columns={'Average_pop_x':'Average_pop', 'Year_y':'Year', 'Continent_x':'Continent'})

In [38]:
the_megaset3.shape

(138, 37)

I merged this dataset with a GeoJson file that contained coordinated for each country, and dropped irrelevant columns.

In [39]:
the_megaset4 = the_megaset3.merge(countries_df, left_on=['Entity', 'Code'], right_on=['ADMIN', 'ISO_A3'])
the_megaset4.head()

,Entity,Code_x,Year,Anxiety_percent,Region_x,Continent,Average_pop,Population_x,Anxiety_population,Depression_percent,...,#psychiatrists,#nurses,#social_workers,#psychologists,Total_resources,Unnamed: 0_y,ADMIN,ISO_A3,ISO_A2,geometry
0,Afghanistan,AFG,2016,4.878875,Southern Asia,Asia,24737.620690,35383000.0,1.726292e+06,4.135694,...,81.73473,34.67534,NaN,104.73368,NaN,1,Afghanistan,AFG,AF,MULTIPOLYGON (((71.04980228700009 38.408664450...
1,Albania,ALB,2016,3.386891,Southern Europe,Europe,3055.275862,2886000.0,9.774569e+04,2.206507,...,42.45306,198.44136,30.59160,35.52666,307.01268,4,Albania,ALB,AL,MULTIPOLYGON (((19.74776574700007 42.578900859...
2,Angola,AGO,2016,3.294534,Middle Africa,Africa,19765.931034,28842000.0,9.502095e+05,4.157841,...,16.43994,190.35720,6.34524,51.62718,264.76956,2,Angola,AGO,AO,MULTIPOLYGON (((11.73751945100014 -16.69257798...
3,Antigua and Barbuda,ATG,2016,4.607747,Caribbean,North America,80.137931,95000.0,4.377360e+03,2.551108,...,0.95095,6.65475,3.80285,NaN,NaN,14,Antigua and Barbuda,ATG,AG,MULTIPOLYGON (((-61.77301998599992 17.12653229...
4,Argentina,ARG,2016,6.280932,South America,South America,38496.068966,43508000.0,2.732708e+06,3.661312,...,9443.41140,NaN,NaN,96836.62576,NaN,8,Argentina,ARG,AR,MULTIPOLYGON (((-68.65412350199998 -54.8862443...

In [40]:
the_megaset5=the_megaset4.drop(['ADMIN', 'ISO_A3', 'ISO_A2'], axis=1)
the_megaset5.head()

,Entity,Code_x,Year,Anxiety_percent,Region_x,Continent,Average_pop,Population_x,Anxiety_population,Depression_percent,...,Region_y,Continent_y,Population_y,#psychiatrists,#nurses,#social_workers,#psychologists,Total_resources,Unnamed: 0_y,geometry
0,Afghanistan,AFG,2016,4.878875,Southern Asia,Asia,24737.620690,35383000.0,1.726292e+06,4.135694,...,Southern Asia,Asia,35383000.0,81.73473,34.67534,NaN,104.73368,NaN,1,MULTIPOLYGON (((71.04980228700009 38.408664450...
1,Albania,ALB,2016,3.386891,Southern Europe,Europe,3055.275862,2886000.0,9.774569e+04,2.206507,...,Southern Europe,Europe,2886000.0,42.45306,198.44136,30.59160,35.52666,307.01268,4,MULTIPOLYGON (((19.74776574700007 42.578900859...
2,Angola,AGO,2016,3.294534,Middle Africa,Africa,19765.931034,28842000.0,9.502095e+05,4.157841,...,Middle Africa,Africa,28842000.0,16.43994,190.35720,6.34524,51.62718,264.76956,2,MULTIPOLYGON (((11.73751945100014 -16.69257798...
3,Antigua and Barbuda,ATG,2016,4.607747,Caribbean,North America,80.137931,95000.0,4.377360e+03,2.551108,...,Caribbean,North America,95000.0,0.95095,6.65475,3.80285,NaN,NaN,14,MULTIPOLYGON (((-61.77301998599992 17.12653229...
4,Argentina,ARG,2016,6.280932,South America,South America,38496.068966,43508000.0,2.732708e+06,3.661312,...,South America,South America,43508000.0,9443.41140,NaN,NaN,96836.62576,NaN,8,MULTIPOLYGON (((-68.65412350199998 -54.8862443...

In [41]:
the_megaset5.columns

Index(['Entity', 'Code_x', 'Year', 'Anxiety_percent', 'Region_x', 'Continent',
       'Average_pop', 'Population_x', 'Anxiety_population',
       'Depression_percent', 'Region_y', 'Continent_y', 'Population_y',
       'Depression_population', 'Code', 'Disorders(%)', 'Unnamed: 0_x',
       'Region_x', 'Continent', 'Population_x', 'Disorders_population', 'Sex',
       'Suicides_per100000', 'Average_pop', '#suicides',
       'Psychiatrists_per100000', 'Nurses_per100000',
       'Social_workers_per100000', 'Psychologists_per100000', 'Region_y',
       'Continent_y', 'Population_y', '#psychiatrists', '#nurses',
       '#social_workers', '#psychologists', 'Total_resources', 'Unnamed: 0_y',
       'geometry'],
      dtype='object')

I renamed some columns.

In [42]:
the_megaset6=the_megaset5.rename(columns={'Code_x':'Code', 'Year_x':'Year', 'Region_x':'Region', 'Continent_x':'Continent'})

In [53]:
the_megaset6.shape

(120, 39)

In [55]:
the_megaset6['Entity'].value_counts()

South Africa    1
Rwanda          1
Cyprus          1
Syria           1
Mozambique      1
Belarus         1
Tajikistan      1
Romania         1
Kyrgyzstan      1
Sudan           1
Luxembourg      1
Hungary         1
Vanuatu         1
Japan           1
Peru            1
Samoa           1
New Zealand     1
Colombia        1
Grenada         1
Cuba            1
Angola          1
Panama          1
Argentina       1
Afghanistan     1
Togo            1
Haiti           1
Australia       1
Albania         1
Burkina Faso    1
Thailand        1
               ..
Guyana          1
Chile           1
Guinea          1
Philippines     1
Barbados        1
Moldova         1
Slovenia        1
Mexico          1
Bolivia         1
Ecuador         1
Saint Lucia     1
Georgia         1
Armenia         1
Fiji            1
Seychelles      1
Mongolia        1
Mali            1
Liberia         1
Netherlands     1
Zambia          1
Latvia          1
Egypt           1
Guatemala       1
Brazil          1
Poland          1
Bulgaria        1
Jamaica         1
Eritrea         1
Costa Rica      1
Lebanon         1
Name: Entity, Length: 120, dtype: int64

Complete, I exported this new "megaset." I recognize this data lacks much of my other data and is flawed, but it will still be helpful.

In [56]:
the_megaset6.to_csv('../data/Cleaned/megaset', index=False)

In [44]:
resources_df.shape

(152, 14)

In [45]:
suicide_df.head()

,Country,Sex,Region,Continent,Year,Suicides_per100000,Average_pop,Population,#suicides
0,Afghanistan,Both sexes,Southern Asia,Asia,2016,4.7,24737.620690,35383000.0,1663.001
1,Albania,Both sexes,Southern Europe,Europe,2016,6.3,3055.275862,2886000.0,181.818
2,Algeria,Both sexes,Northern Africa,Africa,2016,3.2,33273.448276,40551000.0,1297.632
3,Angola,Both sexes,Middle Africa,Africa,2016,4.7,19765.931034,28842000.0,1355.574
4,Antigua and Barbuda,Both sexes,Caribbean,North America,2016,0.5,80.137931,95000.0,0.475

I returned to the subset of the data that only included anxiety, depression, and disorders, as this was the most geographically representative and comprehensive subset. I then merged it with the geographical data.

In [46]:
add_df['Entity'].nunique()

189

In [47]:
addc_df = add_df.merge(countries_df, left_on='Entity', right_on='ADMIN')

In [48]:
addc_df.columns

Index(['Entity', 'Code_x', 'Year', 'Anxiety_percent', 'Unnamed: 0_x',
       'Region_x', 'Continent_x', 'Average_pop_x', 'Population_x',
       'Anxiety_population', 'Code_y', 'Depression_percent', 'Unnamed: 0_y',
       'Region_y', 'Continent_y', 'Average', 'Population_y',
       'Depression_population', 'Country', 'Code', 'Disorders(%)',
       'Unnamed: 0_x', 'Region', 'Continent', 'Average_pop_y', 'Population',
       'Disorders_population', 'Unnamed: 0_y', 'ADMIN', 'ISO_A3', 'ISO_A2',
       'geometry'],
      dtype='object')

I renamed the columns.

In [49]:
addc3_df = addc_df.rename(columns={'Code_x':'Code',
                                   'Region_x':'Region',
                                   'Continent_x':'Continent',
                                   'Average_pop_x':'Average_pop',
                                   'Population_x':'Population'})

In [50]:
addc3_df['Entity'].nunique()

186

I exported this subset as a CSV.

In [51]:
addc3_df.to_csv('../data/Cleaned/anxietydepressiondisorders', index=False)